### ISSUE TITLE
URIMismatchError: Failed to construct URL from string "//www.googletagmanager.com/ns.html?id=xxx" relative to URL "about:blank".

### ISSUE THREAD

**Issue by vjpr** [capricorn86/happy-dom#1003]
**Describe the bug**

**To Reproduce**

Create a page with an iframe with a src with no protocol specified.

```
<noscript>
    <iframe
        src="//www.googletagmanager.com/ns.html?id=xxx"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
```

**Expected behavior**

**Screenshots**

**Device:**

**Additional context**

**Comment by uovol** [comment]
i have same issue

**Comment by uovol** [comment]
My temporary solution is to add the full domain name to iframe's src.

**Comment by capricorn86** [comment]
Thank you for reporting @vjpr and @uovol! :slightly_smiling_face: 

There is a fix released now:
https://github.com/capricorn86/happy-dom/releases/tag/v10.8.1

Note that you need to set a URL on the main document in order for the iframe URL to be relative to it. The main document defaults to "about:blank" if no URL has been set (see #868).
