### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'name') on Button element

### ISSUE THREAD

**Issue by tinaboyce** [capricorn86/happy-dom#1008]
**Describe the bug**
Receiving the following error while trying to run Vitest with any happy-dom version after 10.5.2
```
TypeError: Cannot read properties of null (reading 'name')
 ❯ HTMLButtonElementNamedNodeMap.removeNamedItem node_modules/happy-dom/src/nodes/html-button-element/HTMLButtonElementNamedNodeMap.ts:45:17
 ❯ HTMLButtonElement.removeAttribute node_modules/happy-dom/src/nodes/element/Element.ts:650:19
 ❯ setValueForProperty node_modules/react-dom/cjs/react-dom.development.js:1326:10
 ❯ setInitialDOMProperties node_modules/react-dom/cjs/react-dom.development.js:5831:7
 ❯ setInitialProperties node_modules/react-dom/cjs/react-dom.development.js:6026:3
 ❯ finalizeInitialChildren node_modules/react-dom/cjs/react-dom.development.js:7499:3
 ❯ completeWork node_modules/react-dom/cjs/react-dom.development.js:18978:17
 ❯ completeUnitOfWork node_modules/react-dom/cjs/react-dom.development.js:22189:16
 ❯ performUnitOfWork node_modules/react-dom/cjs/react-dom.development.js:22165:12
 ❯ workLoopSync node_modules/react-dom/cjs/react-dom.development.js:22130:22
```

**To Reproduce**
Update happy-dom from 10.5.2 to any version after 10.5.2 and run a test with a button element. Test is using testing-library and Vitest.

**Expected behavior**
Test to not fail like when using happy-dom 10.5.2

**Screenshots**
![Screenshot 2023-08-04 at 9 48 52 am](https://github.com/capricorn86/happy-dom/assets/12929562/4f62475d-2caf-4ecc-8ba1-1e119eba94e7)
![Screenshot 2023-08-04 at 9 44 07 am](https://github.com/capricorn86/happy-dom/assets/12929562/a2bbdd8b-0dce-4956-adf9-5bfb086faa82)

**Device:**
 - OS: Mac OSX Ventura 13.4

**Comment by capricorn86** [comment]
Thank you for reporting @tinaboyce! :slightly_smiling_face: 

This has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.8.0

**Comment by tinaboyce** [comment]
Can confirm the issue has been fixed in 10.8.0. Thanks for fixing it.

**Comment by capricorn86** [comment]
It was thanks to @maxmilton who contributed with a fix :star2:

**Comment by tinaboyce** [comment]
Massive thanks to you @maxmilton ! 🌟
