### ISSUE TITLE
style="`width: calc(${percent}% - 1px)`" is not returning any value.

### ISSUE THREAD

**Issue by danielwwc** [capricorn86/happy-dom#1014]
**Describe the bug**
style="`width: calc(${percent}% - 1px)`" is not returning any value.

**To Reproduce**
Mount the DOM with:
```html
<div
   class="color-red"
   :style="`width: calc(${percent}% - 1px)`"
/>
```

**Expected behavior**
```html
<div class="color-red" style="10%"></div>
```

**Screenshots / Output**
```html
<div class="color-red" style=""></div>
```

**Device:**
 - OS: MacOS
 - Browser Chrome
 - Version: happy-dom 10.9.0

**Comment by btea** [comment]
@danielwwc Can you provide a reproduction link?

**Comment by capricorn86** [comment]
Thank you for reporting @danielwwc! :slightly_smiling_face: 

I have made a fix that adds support for "calc()" in CSS values.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.10.4
