### ISSUE TITLE
`Content-Type` header is not set while constructing Request object

### ISSUE THREAD

**Issue by orionmiz** [capricorn86/happy-dom#1016]
**Describe the bug**
`Content-Type` header is not set while constructing Request object.

**To Reproduce**
```js
const request = new Request(TEST_URL, { method: "POST", body: "Hello World" })
console.log(request.headers.get("Content-Type")) // null
```

**Expected behavior**
Above `request.headers.get("Content-Type")` should return `"text/plain;charset=UTF-8"`

**Additional context**
I'll fix it.

**Comment by capricorn86** [comment]
Your fix has been released and is available here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.10.0
