### ISSUE TITLE
React input element missing checked attribute

### ISSUE THREAD

**Issue by ArrayKnight** [capricorn86/happy-dom#1023]
**Describe the bug**
When an input of type checkbox or radio is provided the checked prop with a value of true, the resulting dom doesn't include the expected checked attribute.

**Expected behavior**
Elements should have checked attribute, tests should pass

**Screenshots**
<img width="1287" alt="image" src="https://github.com/capricorn86/happy-dom/assets/5431637/f041c7da-0d67-484e-ad9c-909bc3b01124">

**Device:**
 - OS: macOS 13.4.1 (22F82)
 - Browser [e.g. chrome, safari]: Vitest
 - Version [e.g. 22] 0.34.2

**Additional context**
Running the exact same tests using jsdom run and pass as expected

"@testing-library/dom": "^9.3.1",
"@testing-library/jest-dom": "^6.0.1",
"@testing-library/react": "^14.0.0",
"@testing-library/user-event": "^14.4.3",
"happy-dom": "^10.10.4",
"jsdom": "^22.1.0",
"typescript": "^5.1.6",
"vite": "^4.4.9",
"vitest": "0.34.2"

**Comment by timkindberg** [comment]
Same thing happens for me, when clicking the checkbox label it doesn't work.

```js
// App.js

import './App.css';

function App() {
  return (
    <label data-testid="my-checkbox">
      <input name="terms_and_conditions" type="checkbox" value="false"/>
      I agree to the Terms of Use
    </label>
  );
}

export default App;
```

```js
// App.test.js

import { fireEvent, render, screen } from '@testing-library/react';
import App from './App';

test('allows clicking checkbox label', () => {
  // Validate that we are using HappyDOM, not JSDOM
  const isJSDOM = typeof navigator !== "undefined" && navigator.userAgent.includes("jsdom");
  expect(isJSDOM).toBe(false)
  expect(window.happyDOM).toBeDefined();

  render(<App />);
  const label = screen.getByTestId('my-checkbox');
  const checkbox = screen.getByLabelText('I agree to the Terms of Use');
  expect(checkbox).not.toBeChecked();

  // Clicking the input itself should work
  fireEvent.click(checkbox)
  expect(checkbox).toBeChecked();
  fireEvent.click(checkbox)
  expect(checkbox).not.toBeChecked();

  // Clicking Label should also work!
  fireEvent.click(label);
  expect(checkbox).toBeChecked(); // THIS LINE FAILS
});
```

Output:
```
    Received element is not checked:
      <input name="terms_and_conditions" type="checkbox" value="false" />

      16 |   // Clicking Label should also work!
      17 |   fireEvent.click(label);
    > 18 |   expect(checkbox).toBeChecked();
         |                    ^
      19 |
      20 |   // Validate that we are using HappyDOM, not JSDOM
      21 |   // const isJSDOM = typeof navigator !== "undefined" && navigator.userAgent.includes("jsdom");

```

**Comment by capricorn86** [comment]
Thank you for reporting @ArrayKnight and @timkindberg! :slightly_smiling_face: 

The issue has been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.6.0
