### ISSUE TITLE
"eval" in a Window is always scoped to the Window

### ISSUE THREAD

**Issue by joeframbach** [capricorn86/happy-dom#1025]
**Describe the bug**
`eval` has two modes -- a "direct" eval which has access to local scope, and an "indirect" eval which has access only to global scope. The `eval` which executes in a HappyDom document is indirect-only. Behavior in Happy-Dom is different from a real browser.

**To Reproduce**

Execute the script in node:

```
var HappyDom = require('happy-dom');
new HappyDom.Window().document.write(`<!doctype html>
  <script type="text/javascript">
    var globalVariable = 'globalVariableValue';
    (function () {
      var localVariable = 'localVariableValue';
      console.log(eval('globalVariable'));
      console.log(eval('localVariable'));
    })();
  </script>
`);
```

See output

```
globalVariableValue
evalmachine.<anonymous>:1
localVariable
^

ReferenceError: localVariable is not defined
```

Then execute this script in a browser:

```
    var globalVariable = 'globalVariableValue';
    (function () {
      var localVariable = 'localVariableValue';
      console.log(eval('globalVariable'));
      console.log(eval('localVariable'));
    })();
```

See output

```
globalVariableValue
localVariableValue
```

**Expected behavior**

Expected to see "globalVariableValue" and "localVariableValue" in both node and browser.

**Screenshots**
N/A

**Device:**

happy-dom 10.11.0

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#direct_and_indirect_eval

**Comment by joeframbach** [comment]
I found that the `eval` is a "direct" eval, but the issue is that it is always scoped from the Window, not from the scope where it is called in client code.

https://github.com/capricorn86/happy-dom/blob/1f598077b56905c47e4c81b8599bcecb83d5a82b/packages/happy-dom/src/window/Window.ts#L632

Test case:

```
<!doctype html>
<html>
  <script type="text/javascript">
    (function () {
      console.log(eval('this.location'));
    }).call({});
  </script>
</html>
```

In browser:

```
undefined
```

In happy-dom:

```
Location {
  href: 'https://example.com',
  ...
```

**Comment by capricorn86** [comment]
Thanks again for reporting and contributing @joeframbach! :slightly_smiling_face: 

There is a fix released now.

You can read more about it here:
[1](https://github.com/capricorn86/happy-dom/releases/tag/v11.0.0)
