### ISSUE TITLE
Uncaught exceptions thrown asynchronously are not handled by window.onerror

### ISSUE THREAD

**Issue by joeframbach** [capricorn86/happy-dom#1030]
**Describe the bug**

If an uncaught exception is thrown inside a `setTimeout` or other async context, then `window.onerror` does not handle it.

**To Reproduce**

Execute the script:

```
var HappyDom = require('happy-dom');
new HappyDom.Window().document.write(`<!doctype html>
  <script>
    window.onerror = function (error) {
      console.log('intercepted error:', error);
      return true;
    };
    setTimeout(function () {
      throw new Error('oops!');
    });
  </script>
`);
```

and see the output throws `Error: oops!     at evalmachine.<anonymous>:7:13`.

**Expected behavior**

Expected to see `intercepted error: oops!` and not escape the VM.

**Screenshots**

N/A

**Device:**

happy-dom 10.11.0

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event

**Comment by capricorn86** [comment]
Thank you for reporting @joeframbach! :slightly_smiling_face: 

I did not realize that you reported this issue as well until now.

The fix is released now.

You can read more about it here:
https://github.com/capricorn86/happy-dom/releases/tag/v11.0.0
