### ISSUE TITLE
Add support for "g" SVG element

### ISSUE THREAD

**Issue by ottoszika** [capricorn86/happy-dom#1034]
**Is your feature request related to a problem? Please describe.**
SVG `<g>` elements are parsed as HTMLUnknownElement.

**Describe the solution you'd like**
Following the existing conventions is enough to parse them as SVGElement.

**Describe alternatives you've considered**
Maybe parsing them as SVGGElement would be more precise, but this involves changing other graphic elements` behavior (circle, line, etc.) for consistency. Keeping the actual implementation untouched, the solution above works the best.

**Comment by capricorn86** [comment]
@ottoszika your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v11.1.0
