### ISSUE TITLE
can not parse correctly html with nested ul and li tags.

### ISSUE THREAD

**Issue by lovetingyuan** [capricorn86/happy-dom#1039]
**Describe the bug**
can not parse correctly html with nested ul and li tags.

**To Reproduce**
1. just run this code:
```js
import { Window } from 'happy-dom'

const window = new Window({})
const document = window.document
document.write('<div id="app"></div>')
const container = document.querySelector('#app')
container.innerHTML = `
<ul>
  <li>
    <ul>
      <li>aaaaa</li>
      <li>bbbbb</li>
    </ul>
  </li>
</ul>
`
console.log(container.outerHTML)

/**
 * the output is wrong: 
 * <div id="app">
<ul>
  <li>
    <ul>
      </ul></li><li>aaaaa</li>
      <li>bbbbb</li>
    </ul>


</div>
 */

```
2. check the output, it should be same as input html but in fact is wrong.

**Expected behavior**
the right answer is 
```html
<ul>
  <li>
    <ul>
      <li>aaaaa</li>
      <li>bbbbb</li>
    </ul>
  </li>
</ul>
```

**Device:**
 - happy-dom version: "10.11.2"
 - node version: 18.15.0

**Comment by danielbush** [comment]
I think I've got a similar issue.  I thought I'd post it here rather than make a new issue - but I can do that if it's clearer.

- happy-dom: 12.10.3
- bun: 1.0.18

```js
import { Window } from 'happy-dom';

const window = new Window({
  url: 'https://localhost:8080',
  width: 1024,
  height: 768,
});
const document = window.document;

document.body.innerHTML =
  '<ul id="ul"><li id="li1">item 1</li><li id="li2"><ul ><li >trap</li></ul></li><li id="li3">item 3</li></ul>';

console.log(document.body.outerHTML);

window.happyDOM.cancelAsync();
```

gives:

```html
<body><ul id="ul"><li id="li1">item 1</li><li id="li2"><ul></ul></li><li>trap</li></ul><li id="li3">item 3</li></body>
```

`#li2` should contain a nested list with item "trap", but the nested list is empty, "trap" becomes a sibling alongside it and the outer `ul` fails to enclose `#li3`.

**Comment by tq-xyy** [comment]
I also have this issue. Did the author have some questions for solving the issue?

**Comment by tq-xyy** [comment]
```
import { Window } from 'happy-dom'

const document = new Window().document

const ul = document.createElement('ul')

// There are two cases.
// Case 1: It will output `<ul><li><ul><li>From sub list</li></ul></li></ul>` (right)
const li = document.createElement('li')
li.innerHTML = '<ul><li>From sub list</li></ul>'
ul.appendChild(li)

// Case 2: It will output `<ul><li><ul></ul></li><li>From sub list</li></ul>` (error)
// ul.innerHTML = '<li><ul><li>From sub list</li></ul></li>'
// document.body.appendChild(ul)

console.log(document.body.innerHTML)
```

It seemed that the problem happened when putting the `<ul>` element in `<li>`. And it is the problem of `XMLParser`.

The best method is to rewrite `XMLParser`. Now you can try to write a parser yourself to avoid it.

**Comment by tq-xyy** [comment]
This is a patch.
```js
import UnnestableElements from 'happy-dom/lib/config/UnnestableElements.js'
delete UnnestableElements.LI
```

**Comment by danbentley** [comment]
Thanks @lovetingyuan, we've encountered the same issue that left us scratching our heads when writing tests.

We also found that, as @tq-xyy suggests, removing `LI` from the Unnestable element config ([`happy-dom/src/config/UnnestableElements.ts`](https://github.com/capricorn86/happy-dom/blob/4970c699d07d97c4a9839e25c831eef230445abf/packages/happy-dom/src/config/HTMLElementUnnestable.ts#L13)) will allow nested `<li>` elements. Running your test snippet now correctly outputs the markup.

I've [submitted a PR](https://github.com/danbentley/happy-dom/commit/b8c0bbdf78a639f67ad7e5c73e4e3b19a0bfd166) with this fix and updated the tests accordingly.

**Comment by capricorn86** [comment]
Thank you for contributing @danbentley! :star2: 

I'm currently working on an implementation for this as well:
https://github.com/capricorn86/happy-dom/tree/1039-can-not-parse-correctly-html-with-nested-ul-and-li-tags

The problem is that `<li>` elements are not allowed to be nested when they are a direct child of another `<li>` element, but it seems like they are when they are not a direct child.

**Example**
```javascript
var container = document.createElement('div');
container.innerHTML = '<li><li><span>Test</span></li></li>';

// Outputs "<li></li><li><span>Test</span></li>"
console.log(container.innerHTML);
```

**Spec**
https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element

**Comment by danbentley** [comment]
Thanks @capricorn86 for the explanation, that makes sense and it's something that occurred to me.

I suppose some elements are more "unnestable" than others, with `<li>` being the least unnestable of them all!

Sounds like an interesting challenge. I'm looking forward to see how you solve it!

**Comment by capricorn86** [comment]
The problem should be fixed now :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v13.8.3
