### ISSUE TITLE
Parsing SVGs adds additional tags around the parsed data. 

### ISSUE THREAD

**Issue by drtimwright** [capricorn86/happy-dom#1040]
**Describe the bug**
Parsing SVGs using:
``` parser.parseFromString(svg, "image/svg+xml"); ```
adds HTML and BODY tags around the SVG. 

Wheras doing this using JSDOM or in the browser console does not add the additional tags. This means happy-dom is not a drop-replacement for jsdom and does not emulate browser behaviour.

**To Reproduce**

See git repo here with jsdom and happydom examples:
https://github.com/drtimwright/happy-dom-tests/tree/main/src

I'd expect this command to return "svg" not "html":

```new DOMParser().parseFromString("<svg><g></g></svg>", "image/svg+xml").getRootNode().childNodes[0].nodeName;```

**Expected behavior**
* parsing XML that is not HTML should not add HTML tags.

**Device:**
 - OS: Windows (but probably all)
 - Browser N/A
 - Version: 10.11.2

**Additional context**
I'll try to make a PR for this, but no promises!

**Comment by drtimwright** [comment]
![image](https://github.com/capricorn86/happy-dom/assets/7540034/a54c9cd0-8be0-4049-a539-8233dbeb4fbe)

**Comment by capricorn86** [comment]
@drtimwright your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v11.1.1

**Comment by drtimwright** [comment]
Awesome thanks!
