### ISSUE TITLE
`window.dispatchEvent(new Event('Test'))` throws error

### ISSUE THREAD

**Issue by AntonioGargaro** [capricorn86/happy-dom#1049]
**Describe the bug**
When attempting to pass an event to `window.eventDispatch` using `new Event('Test')`, an error is thrown.

`TypeError: Cannot set property eventPhase of #<Event> which has only a getter`

I've replicated this in both ts-node and bun.

**To Reproduce**
Go to link and try `npm run start`
https://stackblitz.com/edit/node-typescript-playground-usrrbn?file=src%2Findex.ts

**Expected behavior**
The event should be dispatched without error.

**Screenshots**

<img width="815" alt="Screenshot 2023-09-07 at 13 09 33" src="https://github.com/capricorn86/happy-dom/assets/38767071/513844ea-def3-41ea-8764-3247befe5035">

**Device:**
ts-node

**Additional context**

**Comment by AntonioGargaro** [comment]
Thanks for the workaround, I'd guess it is likely something in the `GlobalRegistrator` not working correctly 😅?

**Comment by capricorn86** [comment]
The current solution in `GlobalRegistrator` is to not override any property in global. I guess we need to let it override, but restore the properties to their original state when unregistering.

**Comment by alshdotme** [comment]
I'm also getting a similar error with the latest bun and happy-dom

```
TypeError: Attempted to assign to readonly property.
      at new Node (/Users/<redacted>/node_modules/happy-dom/lib/nodes/node/Node.js:32:8)
      at new Element (/Users/<redacted>/node_modules/happy-dom/lib/nodes/element/Element.js:24:8)
      at new HTMLElement (/Users/<redacted>/node_modules/happy-dom/lib/nodes/html-element/HTMLElement.js:17:8)
      at createElementNS (/Users/<redacted>/node_modules/happy-dom/lib/nodes/document/Document.js:704:24)
      at render (/Users/<redacted>/node_modules/@testing-library/react/dist/pure.js:218:40)
27 |         this.DOCUMENT_POSITION_FOLLOWING = NodeDocumentPositionEnum.following;
28 |         this.DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = NodeDocumentPositionEnum.implementationSpecific;
29 |         this.DOCUMENT_POSITION_PRECEDING = NodeDocumentPositionEnum.preceding;
30 |         this.ownerDocument = null;
31 |         this.parentNode = null;
32 |         this.isConnected = false;
            ^
```

**Comment by stevecrozz** [comment]
@capricorn86 Here is a small failing example:

~~~ts
import { GlobalRegistrator } from '@happy-dom/global-registrator';

GlobalRegistrator.register();

window.dispatchEvent(new CustomEvent('some-silly-event'));
~~~

~~~
$ bun test
bun test v1.0.2 (37edd5a6)

app/index.spec.jsx:
80 |                         break;
81 |                     }
82 |                 }
83 |             }
84 |             // At target phase
85 |             event.eventPhase = EventPhaseEnum.atTarget;
                ^
TypeError: Attempted to assign to readonly property.
      at dispatchEvent (/Users/stevecrozz/app/node_modules/happy-dom/lib/event/EventTarget.js:85:12)
      at /Users/stevecrozz/app/happydom.ts:5:0

 0 pass
 1 fail
Ran 1 tests across 1 files. [155.00ms]
~~~

**Comment by capricorn86** [comment]
@AntonioGargaro, @piotrkulpinski, @alshdotme, @TkDodo and @stevecrozz the bug related to Happy DOM not overwriting properties in global has now been fixed :slightly_smiling_face: 

I'm not sure this will fix all problems related to Bun. Feel free to open new bugs in that case.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.1.3

**Comment by capricorn86** [comment]
I found more related issue with GlobalRegistrator which has also been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.1.4
