### ISSUE TITLE
Support `crypto`

### ISSUE THREAD

**Issue by Ayc0** [capricorn86/happy-dom#1050]
In the DOM, there is `window.crypto`:

<img width="273" alt="image" src="https://github.com/capricorn86/happy-dom/assets/22725671/ff68f177-dc51-4620-b716-63b45ddfdd99">

Should it be built within HappyDOM?
Note: it can be built using the native node's cypto's webcrypto:

```js
import { webcrypto } from 'node:crypto';
```

**Comment by capricorn86** [comment]
Yes it should be part of Window, but it has not been added yet. Using 'node:crypto' sounds like a good idea.

**Comment by Ayc0** [comment]
I opened https://github.com/capricorn86/happy-dom/pull/1061 to fix this issue
