### ISSUE TITLE
Is there a way to configure Window?

### ISSUE THREAD

**Issue by uladzimirdev** [capricorn86/happy-dom#1052]
Hi, thanks for the lib!

I'm trying to migrate my old codebase from jsdom and one issue that poped up is overriding `offsetHeight` property on the window object. I know it's readonly, so there should be another way of overriding properties, right? 

what I did before:

```
Object.defineProperty(HTMLElement.prototype, "offsetHeight", {
      configurable: true,
      value: 500,
    });
    Object.defineProperty(HTMLElement.prototype, "offsetWidth", {
      configurable: true,
      value: 500,
    });
```

Any suggestion on how to change offsetHeight properly? 

Error:
`TypeError: Cannot assign to read only property 'offsetHeight' of object '[object Object]'`

> new HTMLElement (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:25:30)
      at HTMLDocument.createElementNS (node_modules/happy-dom/src/nodes/document/Document.ts:822:19)
      at HTMLDocument.createElement (node_modules/happy-dom/src/nodes/document/Document.ts:791:15)
      at render (node_modules/@testing-library/react/dist/pure.js:84:50)

**Comment by capricorn86** [comment]
Hi @uladzimirdev! :slightly_smiling_face:

This is most likely a Typescript typing problem as there is nothing stopping you from setting the properties in Happy DOM.

You can try to add "writable":
```javascript
Object.defineProperty(HTMLElement.prototype, "offsetHeight", {
    configurable: true,
    writable: true,
    value: 500,
});
Object.defineProperty(HTMLElement.prototype, "offsetWidth", {
    configurable: true,
    writable: true,
    value: 500,
});
```

You can also try:
```typescript
(<number>(<unknown>HTMLElement.prototype.offsetHeight)) = 500;
(<number>(<unknown>HTMLElement.prototype.offsetWidth)) = 500;
```

**Comment by uladzimirdev** [comment]
fair, I don't see such error in the console anymore, thanks
