### ISSUE TITLE
HTML doctype parsing/rendering issue

### ISSUE THREAD

**Issue by Seldszar** [capricorn86/happy-dom#106]
If the document contains a doctype, the parser doesn't include it in the right place, making the rendered HTML invalid.

Here's an example: https://runkit.com/seldszar/5f8355a85cf17a001aa0525c

**Comment by capricorn86** [comment]
Thanks for reporting @Seldszar! 🙂 

I will try to fix it Today. Otherwise I fix it Tomorrow.

**Comment by capricorn86** [comment]
@Seldszar support for parsing doctype has now been added :slightly_smiling_face: 

Read more about whats included in the release:
https://github.com/capricorn86/happy-dom/releases/tag/v1.5.0
