### ISSUE TITLE
HTMLDialogElement.close() emits a close Event even when the dialog is already closed

### ISSUE THREAD

**Issue by Schleuse** [capricorn86/happy-dom#1064]
**Describe the bug**
`HTMLDialogElement.close()` emits an close Event even when the dialog is already closed.
This behaviour differs from the implementation in Chrome or Firefox where calls to the `close` method on already closed dialogs don't trigger 'close' Events.

The [Spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-close) says:

> The close(returnValue) method steps are:
> 
> If returnValue is not given, then set it to null.
> 
> [Close the dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#close-the-dialog) [this](https://webidl.spec.whatwg.org/#this) with returnValue.
> 
> When a [dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) element subject is to be closed, with null or a string result, run these steps:
> 
> If subject does not have an [open](https://html.spec.whatwg.org/multipage/interactive-elements.html#attr-dialog-open) attribute, then return.
> 
> Remove subject's [open](https://html.spec.whatwg.org/multipage/interactive-elements.html#attr-dialog-open) attribute.
> 
> If the [is modal](https://html.spec.whatwg.org/multipage/interactive-elements.html#is-modal) flag of subject is true, then [request an element to be removed from the top layer](https://drafts.csswg.org/css-position-4/#request-an-element-to-be-removed-from-the-top-layer) given subject.
> 
> Let wasModal be the value of subject's [is modal](https://html.spec.whatwg.org/multipage/interactive-elements.html#is-modal) flag.
> 
> Set the [is modal](https://html.spec.whatwg.org/multipage/interactive-elements.html#is-modal) flag of subject to false.
> 
> If result is not null, then set the [returnValue](https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-returnvalue) attribute to result.
> 
> If subject's [previously focused element](https://html.spec.whatwg.org/multipage/interactive-elements.html#previously-focused-element) is not null, then:
> 
> Let element be subject's [previously focused element](https://html.spec.whatwg.org/multipage/interactive-elements.html#previously-focused-element).
> 
> Set subject's [previously focused element](https://html.spec.whatwg.org/multipage/interactive-elements.html#previously-focused-element) to null.
> 
> If subject's [node document](https://dom.spec.whatwg.org/#concept-node-document)'s [focused area of the document](https://html.spec.whatwg.org/multipage/interaction.html#focused-area-of-the-document)'s [DOM anchor](https://html.spec.whatwg.org/multipage/interaction.html#dom-anchor) is a [shadow-including inclusive descendant](https://dom.spec.whatwg.org/#concept-shadow-including-inclusive-descendant) of element, or wasModal is true, then run the [focusing steps](https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps) for element; the viewport should not be scrolled by doing this step.
> 
> [Queue an element task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-an-element-task) on the [user interaction task source](https://html.spec.whatwg.org/multipage/webappapis.html#user-interaction-task-source) given the subject element to [fire an event](https://dom.spec.whatwg.org/#concept-event-fire) named [close](https://html.spec.whatwg.org/multipage/indices.html#event-close) at subject.
> 
> The returnValue IDL attribute, on getting, must return the last value to which it was set. On setting, it must be set to the new value. When the element is created, it must be set to the empty string.

**To Reproduce**
1. Create a closed Dialog-Element
2. Register a event handler to the `close` event
3. Call `close()` on the Dialog Element
4. The Handler shouldn't be called, but it get's called

**Expected behavior**
The `close`-Event shouldn't be emitted when the dialog is already closed

**Comment by Schleuse** [comment]
I've created a simple example to examine the current browser behaviour:

https://codepen.io/Schleuse/pen/dywRvMZ

**Comment by capricorn86** [comment]
@Schleuse your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v11.1.2
