### ISSUE TITLE
__proto__ points to an error after Blob instantiation

### ISSUE THREAD

**Issue by wenyejie** [capricorn86/happy-dom#1066]
**Describe the bug**

As title

``` javascript
const blob = new Blob(['test'], { type: 'text/plain' })
console.log(blob.__proto__, Blob)
```

In happy-dom

```
// when i use environment: 'happy-dom',
{} [class Blob]
```

In Node

```
// when i unuse environment: 'happy-dom',
Object [Blob] {
  type: [Getter],
  size: [Getter],
  slice: [Function: slice],
  arrayBuffer: [Function: arrayBuffer],
  text: [AsyncFunction: text],
  stream: [Function: stream]
} [class Blob]
```

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/capricorn86/happy-dom/assets/4539115/5cb2cfd0-5ea5-4af9-bde6-3d1884db4e1a)

**Device:**
 - OS: Window 11 x64
 - Browser [Node vitest]
 - Version [11.0.2]

**Additional context**
``` javascript
// vite.config.js
const test = {
  include: ['./tests/*.test.ts'],
  environment: 'happy-dom',
  browser: {
    enabled: false,
    name: 'chrome',
  },
}
```

```json5
// package.json
"devDependencies": {
  "@types/node": "^20.5.9",
  "@vitest/coverage-v8": "^0.34.3",
  "happy-dom": "^11.0.2",
  "prettier": "^3.0.3",
  "typescript": "^5.2.2",
  "vite": "^4.4.9",
  "vitest": "^0.34.3"
},
```

**Comment by capricorn86** [comment]
Thank you for reporting @wenyejie! :slightly_smiling_face: 

I'm not sure what the bug is here? Happy DOM uses its own Blob inside the environment to be able to work better with features such as fetch.

**Comment by wenyejie** [comment]
@capricorn86 
like this
```javascript
const isBlob = obj => {
  return Object.prototype.toString.call(obj).slice(8, -1) === 'Blob'
}
```

**Comment by davidortner-ipex** [comment]
> @capricorn86 like this
> 
> ```js
> const isBlob = obj => {
>   return Object.prototype.toString.call(obj).slice(8, -1) === 'Blob'
> }
> ```

Here are two other way of testing it that I think is more reliable
1. `return obj instanceof Blob`
2. `return obj.constructor.name === 'Blob'`

**Comment by capricorn86** [comment]
> @capricorn86 like this
> 
> ```js
> const isBlob = obj => {
>   return Object.prototype.toString.call(obj).slice(8, -1) === 'Blob'
> }
> ```

Here are two other ways of testing it that I think is more reliable
1. `return obj instanceof Blob`
2. `return obj.constructor.name === 'Blob'`

**Comment by wenyejie** [comment]
> > @capricorn86 like this
> > ```js
> > const isBlob = obj => {
> >   return Object.prototype.toString.call(obj).slice(8, -1) === 'Blob'
> > }
> > ```
> 
> Here are two other ways of testing it that I think is more reliable
> 
> 1. `return obj instanceof Blob`
> 2. `return obj.constructor.name === 'Blob'`

thx, for your answer.

I have already tried

yes, i think so,  maybe you are right. but it is not consistent with ecmascript here
