### ISSUE TITLE
Upgrading from 11.0.2 -> 12.0.0: ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by dflock** [capricorn86/happy-dom#1069]
**Describe the bug**
My vitest tests run fine using happy-dom 11.0.2. After upgrading to 12.0.0, I get this for every test suite:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
ReferenceError: __dirname is not defined
 ❯ Function.getHappyDOMVersion node_modules/.pnpm/happy-dom@12.0.0/node_modules/happy-dom/src/navigator/NavigatorUtility.ts:14:45
 ❯ new Window node_modules/.pnpm/happy-dom@12.0.0/node_modules/happy-dom/src/window/Window.ts:215:132
 ❯ new GlobalWindow node_modules/.pnpm/happy-dom@12.0.0/node_modules/happy-dom/lib/window/GlobalWindow.js:11:9
 ❯ Object.setup node_modules/.pnpm/vitest@0.34.4_@vitest+ui@0.34.4_happy-dom@12.0.0_lightningcss@1.21.7/node_modules/vitest/dist/vendor-environments.c9c96bf7.js:559:17
 ❯ withEnv node_modules/.pnpm/vitest@0.34.4_@vitest+ui@0.34.4_happy-dom@12.0.0_lightningcss@1.21.7/node_modules/vitest/dist/entry.js:71:15
 ❯ run node_modules/.pnpm/vitest@0.34.4_@vitest+ui@0.34.4_happy-dom@12.0.0_lightningcss@1.21.7/node_modules/vitest/dist/entry.js:95:3
 ❯ run node_modules/.pnpm/vitest@0.34.4_@vitest+ui@0.34.4_happy-dom@12.0.0_lightningcss@1.21.7/node_modules/vitest/dist/worker.js:87:5
 ❯ node_modules/.pnpm/tinypool@0.7.0/node_modules/tinypool/dist/esm/worker.js:109:20
```

**To Reproduce**
1. vitest --ui --coverage.enabled=true

**Expected behavior**
Tests to run fine, as before.

**Screenshots**

**Device:**
 - OS: Windows 10
 - Browser: Running vitest in Windows Terminal
 - Version: 

**Additional context**
Am using these versions of relevant packages:

- "vitest": "^0.34.4",
- "vite": "^4.4.9",
- "happy-dom": "^11.0.2",
- "@vitest/coverage-v8": "^0.34.4",
- "@vitest/ui": "^0.34.4",

**Comment by dflock** [comment]
Downgrading again fixes the error.
What other information can I provide to help figure this out?

**Comment by ekwoka** [comment]
I am having the same issue.

**Comment by belgattitude** [comment]
Same issue. Not urgent for me but if it helps to debug: 

https://github.com/belgattitude/nextjs-monorepo-example/pull/4377

Keep the good work. 1000's thx btw.

**Comment by capricorn86** [comment]
Thank you @dflock, @ekwoka, @belgattitude and @tobua for reporting! :slightly_smiling_face: 

Big thanks to @ekwoka for providing with a partial fix :star: 

The problem has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.0.1
