### ISSUE TITLE
@testing-library/user-event paste() method fails when using happy-dom, works with jsdom

### ISSUE THREAD

**Issue by sethreidnz** [capricorn86/happy-dom#1077]
**Describe the bug**

When switching to happy-dom I noticed this bug started occuring with @testing-libary. I'm not 100% certain which side the fix needs to be on but it works with jestdom. I will also raise a bug over there

```
TypeError: dt.setData is not a function
 ❯ getClipboardDataFromString node_modules/@testing-library/user-event/dist/esm/clipboard/paste.js:25:8
 ❯ Object.paste node_modules/@testing-library/user-event/dist/esm/clipboard/paste.js:16:70
 ❯ node_modules/@testing-library/user-event/dist/esm/setup/setup.js:84:35
 ❯ Object.asyncWrapper node_modules/@testing-library/react/dist/pure.js:73:28
 ❯ wrapAsync node_modules/@testing-library/user-event/dist/esm/setup/wrapAsync.js:7:24
 ❯ Object.method [as paste] node_modules/@testing-library/user-event/dist/esm/setup/setup.js:84
```

**To Reproduce**

1. Setup a new project using happy-dom and @testing-library/user-event
2. Create a test that uses the user.paste() api
3. Run tests and see error

[See reproduction repo here for full example]()

**Expected behavior**

Expect the .paste() function to work as it does in jestdom

**Device:**
 - OS: MacOS
 - Browser: Using Vitest
 - Version: 12.1.2

**Additional context**

[See reproduction repo here for full example](https://github.com/sethreidnz/testing-library-happy-dom-paste-issue)

I have also raised an issue with @testing-libary 

https://github.com/testing-library/user-event/issues/1167

**Comment by jrubins** [comment]
Ran into the same issue. Looking at the repo commits, it seems like support for this was added last week (but not yet released). See https://github.com/capricorn86/happy-dom/commit/243676f43917e6b98ee4e96a922096a18870bc4c. 🤞 this lands in a release soon!

**Comment by jrubins** [comment]
Oh, @sethreidnz , seems like this was released in https://github.com/capricorn86/happy-dom/releases/tag/v12.8.0. Updating to the latest version fixed this issue for me.

**Comment by capricorn86** [comment]
It seems like this has been fixed, so I will close the issue. Please re-open if it is not fixed.
