### ISSUE TITLE
Window does not have proper globals on Stackblitz

### ISSUE THREAD

**Issue by layershifter** [capricorn86/happy-dom#1096]
**Describe the bug**

This is a tricky issue that we have faced in https://github.com/callstack/linaria/issues/1345.

Some globals may not be defined when `Window` is used, for example `Object`. `GlobalWindow` works fine.

NOTE: locally with Node 16/18 it works properly, the problem happens only with Stackblitz.

**To Reproduce**

1. Go to https://stackblitz.com/edit/stackblitz-starters-qybbxi
2. Run `test-window.js`
3. Observe that `window.Object` is undefined

```
❯ node test-window.js
win.Object undefined undefined true
```

**Expected behavior**

`Object` should be defined:

```
win.Object [Function: Object] function true
```

**Screenshots**
N/A

**Device:**
 - OS: N/A
 - Browser: Chrome/Edge latest

**Additional context**

The sandbox has also two additional files:
- `test-global-window.js` - the same as `test-window.js`, but uses `GlobalWindow` and works properly
- `test-manual.js` - calls `vm` module manually using `happy-dom/cjs/window/VMGlobalPropertyScript.cjs`, also works fine 🤔

**Comment by capricorn86** [comment]
Starblitz outputs this warning in the console:
![Screenshot from 2023-09-25 20-30-15](https://github.com/capricorn86/happy-dom/assets/19155544/4496e20c-e43a-4c53-af0b-c8b6df06cea2)

**Comment by capricorn86** [comment]
I have created a bug in Starblitz. Hopefully they can figure out why the script isn't executed using `VM.runInContext()`.

**Comment by capricorn86** [comment]
@layershifter Stackblitz has made a fix now. The problem has been resolved :slightly_smiling_face:
