### ISSUE TITLE
scrollWidth is undefined in document.documentElement

### ISSUE THREAD

**Issue by wojtekmaj** [capricorn86/happy-dom#1109]
**Describe the bug**

`scrollWidth` is `undefined` in `document.documentElement`. Oddly enough, `scrollHeight` is set just fine.

**To Reproduce**

https://npm.runkit.com/happy-dom

```
var {Window} = require("happy-dom")

const window = new Window();
console.log('scrollWidth', window.document.documentElement.scrollWidth);
console.log('scrollHeight', window.document.documentElement.scrollHeight);
```

**Expected behavior**

`scrollWidth` to be defined and set to 0 just like `scrollHeight` is.

**Additional context**

Commit with tests failing after replacing JSDom with Happy DOM:
https://github.com/wojtekmaj/react-hooks/commit/bde9864b38bd057cdae2b203a56e941a65bae02e

**Comment by capricorn86** [comment]
Thank you for reporting @wojtekmaj! 🙂 

There is a fix in now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.7.0

**Comment by davidortner-ipex** [comment]
Thank you for creating a fix PR as well ⭐
