### ISSUE TITLE
MutationRecord should be globally available

### ISSUE THREAD

**Issue by wojtekmaj** [capricorn86/happy-dom#1112]
**Describe the bug**

MutationRecord should be globally available, as it is in the browser.

**To Reproduce**

I have a test in my test suite that checks if MutationObserver callback gets called with an array of MutationRecord. Because it's not globally available, this test code:

```js
    expect(listener).toHaveBeenCalledWith(
      [expect.any(MutationRecord)],
      expect.any(MutationObserver),
    );
```

is, in reality,

```js
    expect(listener).toHaveBeenCalledWith(
      [expect.any(undefined)],
      expect.any(MutationObserver),
    );
```

and results in an error:

```
TypeError: any() expects to be passed a constructor function. Please pass one or use anything() to match any object.
```

As a temporary workaround, I can to import it manually into my module:

```ts
import MutationRecord from 'happy-dom/lib/mutation-observer/MutationRecord.js';
```

and it works just fine.

**Expected behavior**

MutationRecord to be globally available.

**Screenshots**

Commit with tests failing after replacing JSDom with Happy DOM:
https://github.com/wojtekmaj/react-hooks/commit/8a95c2bc9c1487fecba9dd66a4e45336ec77691b

**Comment by capricorn86** [comment]
Thank you for reporting @wojtekmaj! :slightly_smiling_face: 

This has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.8.0

**Comment by wojtekmaj** [comment]
Haha seeing notifications from you always feels like Christmas, it's always good news. :D 

Have a beer on me! 🍺

**Comment by capricorn86** [comment]
Thank you @wojtekmaj! :beers:
