### ISSUE TITLE
Is it possible to load and render files?

### ISSUE THREAD

**Issue by grandemestre** [capricorn86/happy-dom#1120]
Hello, I have a question, I don't know if the resource is missing or I don't know how to use it. My goal is to scrape a dynamic page. I used jsdom but I found this project better because it appears to be compatible with fetch.

I wanted to know how to load an .html file and render it including javascripts. The equivalent of this in jsdom:

```
const { JSDOM } = require('jsdom');

let options = { runScripts: "dangerously", resources: "usable" }

JSDOM.fromFile('index.html', options).then(dom => {

  console.log(dom.serialize)

});
```

**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fetch Text Error</title>
</head>
<body>
    <div class="valor"></div>
    
</body>

<script>
let valor = document.getElementsByClassName('valor')[0];

fetch('https://api.github.com/users/xiaotian/repos').then(
  resp => resp.json() // this returns a promise
).then(repos => {
  for (const repo of repos) {

    
    valor.innerHTML += repo.name + '</br>';
    //console.log(repo.name);
  }
}).catch(ex => {
  console.error(ex);
})

</script>
</html>
```

**Comment by capricorn86** [comment]
Hi @grandemestre! :slightly_smiling_face: 

You would do something like this:
```javascript
import { Window } from 'happy-dom';

const url = 'https://github.com';
const window = new Window({ url });
const document = window.document;
const html = await window.fetch(url);
   
document.write(html);
   
// Wait for async tasks such as scripts, styles, fetches and timers to complete
await window.happyDOM.whenAsyncComplete();

// Do something with the result
const field = document.querySelector('.field');
console.log(field.textContent);
```

I can also mention that I'm working right now on improving this.

After the new update it will look something like this:
```javascript
import { Browser } from 'happy-dom';

const browser = new Browser();
const page = browser.newPage();

await page.goto('https://github.com');
await page.whenComplete();

// Do something with the result
```

**Comment by capricorn86** [comment]
With a file:
```javascript
import { Window } from 'happy-dom';
import FS from 'fs';

const url = 'https://github.com';
const window = new Window({ url });
const document = window.document;
const html = (await FS.promises.readFile('index.html')).toString();
   
document.write(html);
   
// Wait for async tasks such as scripts, styles, fetches and timers to complete
await window.happyDOM.whenAsyncComplete();

// Do something with the result
const field = document.querySelector('.field');
console.log(field.textContent);
```

**Comment by grandemestre** [comment]
I don't know why but neither of the two codes works for me. It doesn't return any errors, it just doesn't do anything

**Comment by capricorn86** [comment]
@grandemestre there was a problem in the example, but I have fixed it now. I also changed the URL to https://google.com as https://github.com is using a function that is not supported in Happy DOM yet.

Here is a working example:
https://runkit.com/capricorn86/651f36ea2eb0d90008446a82

**Comment by grandemestre** [comment]
Thanks a lot for the help. Now it worked correctly. Out of curiosity, what functionality is not yet supported?

**Comment by capricorn86** [comment]
> Thanks a lot for the help. Now it worked correctly. Out of curiosity, what functionality is not yet supported?

Sorry, I forgot to answer this and I don't remember anymore.

**Comment by capricorn86** [comment]
There is a new way now using the Happy DOM Browser API:
https://github.com/capricorn86/happy-dom/wiki/Browser

I will close this ticket now.
