### ISSUE TITLE
Support `HTMLElement#inert` property

### ISSUE THREAD

**Issue by mbehzad** [capricorn86/happy-dom#1124]
Hi, 
according to the HTML Spec (https://html.spec.whatwg.org/multipage/interaction.html#dom-inert) the HTMLElement has the `inert` property which reflects its `inert` boolean attribute and the inert state of the DOM element (https://html.spec.whatwg.org/multipage/interaction.html#inert) (no focus, click, etc).

happy-dom seems not yet to support this. e.g.

```js
import { Window } from 'happy-dom';

const window = new Window();
const document = window.document;
document.body.innerHTML = '<div class="container"></div>';
const container = document.querySelector('.container');

container.inert = true;

console.log(container.outerHTML); // will print `<div class="container"></div>` instead of `<div class="container" inert></div>`
```

cheers

**Comment by capricorn86** [comment]
Thank you for reporting @mbehzad! :slightly_smiling_face: 

Big thanks to @odanado for contributing with a fix :star: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v14.6.0
