### ISSUE TITLE
Calculate all relative attributes using the base URL

### ISSUE THREAD

**Issue by asportnoy** [capricorn86/happy-dom#1135]
**Describe the bug**
Certain URL attributes currently do not currently handle calculating the full URL from the relative URL. Links (`<a>`) handle it, but all other attributes do not.

**To Reproduce**
Demo: https://runkit.com/embed/3ysykfxe8h47
```js
const { Window } = require('happy-dom');

const { document } = new Window({
    url: 'https://example.com',
    settings: {
        disableJavaScriptFileLoading: true,
        disableCSSFileLoading: true,
    },
});

document.body.innerHTML = `
    <link rel="stylesheet" href="/test.css" />
    <img src="/test.png" alt="Test" />
    <form action="/test" />
    <a href="/test">Test</test>
    <script src="/test.js"></script>
`;

console.log(document.querySelector('link').href); // ❌ "/test.css"
console.log(document.querySelector('img').src); // ❌ "/test.png"
console.log(document.querySelector('form').action); // ❌ "/test"
console.log(document.querySelector('a').href); // ✅ "https://example.com/test"
console.log(document.querySelector('script').src); // ❌ "/test.js"
```

**Expected behavior**
All of the attributes above should return the absolute URL to the resource, like the `<a>` tag currently does. This is the behavior in a real browser, and we can also see that [JSDOM handles all these attributes](https://github.com/search?q=repo%3Ajsdom/jsdom%20parseURLToResultingURLRecord&type=code).

**Actual Behavior**
Only the `<a>` tag has the proper attribute handling.

**Device:**
 - Lib: v12.9.1
 - NodeJS: v16.20.2
 - OS: macOS Sonoma

**Comment by capricorn86** [comment]
Thank you for reporting @asportnoy! :slightly_smiling_face: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.8.4
