### ISSUE TITLE
HTMLElement.outerHTML miss style.aspectRatio

### ISSUE THREAD

**Issue by infeng** [capricorn86/happy-dom#1147]
**Describe the bug**
I set style.aspectRatio on HTMLElement, but HTMLElment.outerHTML can not contain aspectRatio

**To Reproduce**
```javascript
const { Window } = require('happy-dom');

const window = new Window({
	url: 'https://localhost:8080',
	width: 1024,
	height: 768
});

const div = window.document.createElement('div');
div.style.aspectRatio = '100/200';
div.style.width = '100%';

console.log(div.outerHTML);
```
actual output: ```<div style="width: 100%;"></div>```

**Expected behavior**
expect output: ```<div style="aspect-ratio: 100 / 200; width: 100%;"></div>```

**Device:**
 - OS: mac
 - Browser node
 - Version 16.20.1

**Additional context**

**Comment by capricorn86** [comment]
Thank you for reporting @infeng! :slightly_smiling_face: 

It seems like we are missing support for `aspectRatio` in [CSSStyleDeclaration](https://github.com/capricorn86/happy-dom/blob/v12.10.2/packages/happy-dom/src/css/declaration/CSSStyleDeclaration.ts) and `aspect-ratio` [CSSStyleDeclarationPropertyManager](https://github.com/capricorn86/happy-dom/blob/v12.10.2/packages/happy-dom/src/css/declaration/property-manager/CSSStyleDeclarationPropertyManager.ts)

**Comment by yinm** [comment]
Can I try it?
