### ISSUE TITLE
Node.insertBefore works incorrectly

### ISSUE THREAD

**Issue by CrOrc** [capricorn86/happy-dom#115]
happy-dom version 1.6.3

Node.insertBefore fails if referenceNode is null.
Following code works ok in browser and in JSDOM
```
const div1 = document.createElement("div");
const div2 = document.createElement("div");
div1.insertBefore(div2, div1.firstChild);
```

**Comment by capricorn86** [comment]
Thank you for reporting @CrOrc!

I will try to get in a fix Today :slightly_smiling_face:

**Comment by capricorn86** [comment]
@CrOrc the issue has been fixed now.

Its fixed in this release:
https://github.com/capricorn86/happy-dom/releases/tag/v1.7.0
