### ISSUE TITLE
Custom self-closing tags don't parse correctly

### ISSUE THREAD

**Issue by vSkoryk** [capricorn86/happy-dom#1152]
We experience an issue when our markup contains custom self-closing tags.
I've found an issue, that was created about 2 years ago, but I still can reproduce it  - [issue](https://github.com/capricorn86/happy-dom/issues/288)
I've recreated an example here - [code](https://stackblitz.com/edit/node-wdswqj?file=index.js)

**Comment by capricorn86** [comment]
Thank you for reporting @vSkoryk! :slightly_smiling_face: 

I have compared the results between Chrome and Happy DOM, and they are identical.

By default, elements are not self-closing when the namespace is "http://www.w3.org/1999/xhtml". As no end tag is there, all upcoming nodes will be added to the opened Element.

**Example**

Code
```javascript
var container = document.createElement('div');

container.innerHTML = `
<custom-attributes>
   <custom-accordion />
   <custom-accordion-element />
   <custom-accordion-text />
</custom-attributes>`;

console.log(container.innerHTML);
```
Outputs
```html
<custom-attributes>
   <custom-accordion>
   <custom-accordion-element>
   <custom-accordion-text>
</custom-accordion-text></custom-accordion-element></custom-accordion></custom-attributes>
```

**Comment by capricorn86** [comment]
I'm closing this as it doesn't seem to be a bug. Please re-open if I missed something.
