### ISSUE TITLE
Copy to clipboard fails

### ISSUE THREAD

**Issue by robinelvin** [capricorn86/happy-dom#1153]
**Describe the bug**

Using the `useCopyToClipboard` hook from `usehooks-ts` in a component makes it fail in testing with happy-dom with the following message:

```
Copy failed DOMException: Type text/plain does not match the blob's type
    at new ClipboardItem
```

**To Reproduce**
1. Create a React component
2. import `usehooks-ts`
3. Use the `useCopyToClipboard` hook to copy some plain text to the clipboard on a button press for example.
4. Create a test which uses `happy-dom` and click the button in the test code
5. Observe the error

**Expected behavior**
The string should be copied to the clipboard without error.

**Screenshots**

**Device:**
 - OS: macOS
 - React 18
 - Version 12.10.3

**Comment by dhruvkelawala** [comment]
Is there no fix for this yet?

**Comment by dteoh** [comment]
I'm not using any hook libs but just a regular `navigator.clipboard.writeText(contents)` where `contents` is a string value and it fails.

**Comment by andrewdodd** [comment]
I too am having this issue. I am pretty sure it is related to this work: https://github.com/capricorn86/happy-dom/pull/1116

as when I install 12.7.0 my tests pass fine, and when I install 12.8.0 they fail with this same message ("Type text/plain does not match the blob's type").

**Comment by capricorn86** [comment]
Thank you for reporting @robinelvin, @dhruvkelawala , @dteoh and @andrewdodd! :slightly_smiling_face: 

The problem should be fixed now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.8.1
