### ISSUE TITLE
`querySelectorAll` returns wrong results when `:disabled` pseudo-class used

### ISSUE THREAD

**Issue by ciepol** [capricorn86/happy-dom#1159]
**Describe the bug**
When `:disabled` pseudo-class is present in `querySelectorAll` it is ignored and result includes disabled elements.
Additionally when combined with `:not()` it is not selecting anything.
See examples below.

**To Reproduce**
Go to https://npm.runkit.com/happy-dom
and paste the code:

```js
var happyDom = require("happy-dom")

function test(selector) { 
    console.log(
        selector,
        [...document.querySelectorAll(selector)].map((node) => `${node.nodeName} ${node.className}`)
    );
}

const window = new happyDom.Window();
const document = window.document;
document.body.innerHTML = `
    <button class="enabled-button">enabled button</button>
    <button class="disabled-button" disabled="">disabled button</button>
    <input class="enabled-input-button" value="enabled input button" type="button">
    <input class="disabled-input-button" value="disabled input button" disabled="" type="button">
    <a href="https://google.com">link</a>
    <input class="checked-checkbox" name="checkbox" type="checkbox" value="checkbox" checked="">
    <input class="unchecked-checkbox" name="checkbox2" disabled="" value="checkbox2" type="checkbox">
`;

test('button, a');
test('button:disabled'); // wrong - returns all buttons
test('[type="button"]:disabled'); // wrong - returns all input buttons
test('input:disabled'); // wrong - returns all inputs
test('button:not(:disabled)'); // wrong - returns none
test('[type="button"]:not(:disabled)'); // wrong - returns none
test('button:not(.disabled-button)');
test('input:checked');
test('input[type="checkbox"]:not(:checked)');
```

**Expected behavior**
It should select disabled elements. It should select enabled elements when combined with `:not()` pseudo-class.

**Additional context**
Might be related to #990 .

**Comment by csantos1113** [comment]
FWIW: the issue is also present in `querySelector`. I created this example https://stackblitz.com/edit/stackblitz-starters-s687yz?file=package.json,jsdom.spec.tsx,happy-dom.spec.tsx where we can compare `jsdom` vs `happy-dom`

`npm run test` in the terminal:

<img width="412" alt="image" src="https://github.com/user-attachments/assets/c0e0170d-a464-4236-8b57-b89dc2f31f32">

**Comment by capricorn86** [comment]
Thank you for reporting @ciepol and @csantos1113! :slightly_smiling_face: 

This has now been fixed. The reason for why it didn't work is because the ":disabled" pseudo-class wasn't supported yet.
