### ISSUE TITLE
Missing support for Document/createElementNS

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#116]
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS

**Comment by capricorn86** [comment]
@jgonte support for Document.createElementNS() was added in the following release:
https://github.com/capricorn86/happy-dom/releases/tag/v1.3.0

Have you tested it? If you have, did you get any problems?

**Comment by capricorn86** [comment]
I will close this issue. Lets have all discussions in #117 instead.

**Comment by jgonte** [comment]
I am going to need some time to set the unit test up for that since I moved the code to a different project where I am using the browser DOM

It might take me a couple of days since I have a few things on my plate now

As soon as I test, I let you know


________________________________

**Comment by capricorn86** [comment]
I understand, sounds good :+1:
