### ISSUE TITLE
element.getBoundingClientRect().toJSON() does not exist

### ISSUE THREAD

**Issue by dragonofdeath** [capricorn86/happy-dom#1161]
**Describe the bug**
element.getBoundingClientRect().toJSON() throws as its not implemented. 

getBoundingClientRect() returns [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) which inherits its properties from [DOMRectReadOnly](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly) and it has `toJSON` method, which is listed in mdn and is supported by all browsers. In my jsdom based tests I was using `jsdom-pollyfill` to solve the usecase  and the implementaction code it is was using is something like this https://github.com/remirror/remirror/blob/main/packages/jest-remirror/src/jsdom-polyfills.ts#L90-L92 Would you mind PR adding this method?

**Comment by capricorn86** [comment]
Thank you for reporting @dragonofdeath  ! :slightly_smiling_face: 

Big thanks to @domakas for contributing with a fix :star: 

https://github.com/capricorn86/happy-dom/releases/tag/v14.8.1
