### ISSUE TITLE
Selection.anchorOffset should return 0 instead of null according to the spec

### ISSUE THREAD

**Issue by seanogdev** [capricorn86/happy-dom#1163]
**Describe the bug**
Trying to migrate to happy-dom and our test presumes that if the anchorNode is null,  then the anchorOffset is 0
**To Reproduce**

https://w3c.github.io/selection-api/#dom-selection-anchoroffset

**Expected behavior**
It matches spec

**Screenshots**

**Device:**

**Additional context**

**Comment by capricorn86** [comment]
Thank you again for your contribution @seanogdev!

Your fix has been released:
https://github.com/capricorn86/happy-dom/releases/tag/v13.1.2
