### ISSUE TITLE
Button type=submit does not set the SubmitEvent submitter to `this`

### ISSUE THREAD

**Issue by aaltepet** [capricorn86/happy-dom#1173]
**Describe the bug**
HTML form submissions that are triggered from a button click do not pass the clicked button as the event.submitter in the `SubmitEvent` event.  Forms with an `onSubmit` handler are unable to identify the element that triggered the `SubmitEvent`.  The clicked button, if it has a name, will also be submitted in the GET/POST.

One dev pattern in the remix framework is to use a `<button type="submit" name="_action" />` to signal to the POST handler which button was clicked (and branch to take action accordingly). This bug causes problems when using testing-library to write unittests for remix applications that rely on this pattern, as the _action isn't submitted with the POST.

**To Reproduce**

**Expected behavior**
See the [Mozilla Developer Network reference](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter) for the `SubmitEvent.submitter` property

Normal browser behavior for button clicks is to supply the button as the `event.submitter`.  This allows event handlers to identify the element that triggered the event `event.target`.  Additionally if the button has a name, it is included in formData.  

For dom like (in react):
```<form onSubmit={(event) => console.log(event.target)}>
<button type="submit" name="_action" value="doTheThing">Submit form</button>
</form>
```

Clicking the button should emit the button in the console.log.

Remix, a react-based web application that uses leverages browser-standard capabilities like html form submissions, uses this technique to have a single endpoint that can perform multiple tasks.  This was also a typical pattern back before single page apps took over.

I see the happy-dom HTMLFormElement code supports supply a submitter, but neither HTMLButtonElement nor HTMLInputElement(type="submit") pass `this` along to it.  I'll be submitting a PR to fix this.

**Screenshots**

A normal form submission clicked by a button sets the event.submitter to be the button:

<img width="709" alt="Screenshot 2023-12-04 at 12 41 46 PM" src="https://github.com/capricorn86/happy-dom/assets/1998375/e3b4916d-2529-4717-84ee-8c350d7a8fda">

**Device:**
n/a

**Comment by capricorn86** [comment]
Thank you again for your contribution @aaltepet!

Your fix has been released:
https://github.com/capricorn86/happy-dom/releases/tag/v13.1.4
