### ISSUE TITLE
`Object.keys(localStorage)` returns ['_store'] not the keys stored

### ISSUE THREAD

**Issue by knownasilya** [capricorn86/happy-dom#1181]
**Describe the bug**
`Object.keys(localStorage)` returns ['_store'] not the keys stored
You have to do `Object.keys(localStorage._store)` to get the keys. 
This also happens with for-in loop.

Using "happy-dom": "^12.10.3"

**To Reproduce**
1. Set values on localStorage
2. Run `Object.keys(localStorage)`
3. See incorrect result

**Expected behavior**
Object.keys(localStorage) should return keys that were set.

**Device:**
 - OS: macos m1 latest version

**Comment by knownasilya** [comment]
Workaround:

```js
for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    // access each key
}
```

**Comment by XiaoDaiGua-Ray** [comment]
I encountered the same situation as you, after emulating the storage of a value, I used `Object.keys(window.localStorage)` to get an empty array.

<img width="1376" alt="image" src="https://github.com/capricorn86/happy-dom/assets/51957438/cda1a15d-f9c7-4372-b298-4fa6e05146bb">

**Comment by capricorn86** [comment]
Than you for reporting @knownasilya! and @XiaoDaiGua-Ray! :slightly_smiling_face: 

A big thanks to @frankdiw for contributing with a fix :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v14.3.1
