### ISSUE TITLE
DOMException: The selector ":nth-of-type" is not valid.

### ISSUE THREAD

**Issue by U-Zo** [capricorn86/happy-dom#1191]
![image](https://github.com/capricorn86/happy-dom/assets/34366441/2de2ef0d-f379-4927-b404-283dd2aa3c37)

In the case of nested selectors, it is not valid.

e.g.)
```css
p:not(:nth-of-type(1))
```

**Comment by gdorsi** [comment]
Got the same issue!

I've isolated the problem to SELECTOR_REGEXP which doesn't support pseudo selectors as arguments of other pseudo-selectors: https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/query-selector/SelectorParser.ts#L22

This is a repro test:

```
it("Has support for nesting pseudo selectors inside pseudo-selectors arguments", () => {
  const div = document.createElement("div");
  const child = document.createElement("div");

  div.appendChild(child);

  expect(div.querySelector(":not(:nth-child(0))")).toBe(child);
});
```
