### ISSUE TITLE
Support fallback value of css variables

### ISSUE THREAD

**Issue by TD-LiXiang** [capricorn86/happy-dom#1192]
Our project uses [fallback value](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#custom_property_fallback_values) of css variables. For example:
```css
.my-button {
  color: var(--my-var, #FFFFFF)
}
```
But the [regular expression](https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts#L20) used by happy-dom only recognizes css variables with no fallback value. The Regular expression is:
```ts
const CSS_VARIABLE_REGEXP = /var\( *(--[^) ]+)\)/g;
```

Do we have plans to support fallback value of css variables?

**Comment by capricorn86** [comment]
Thank you for reporting @TD-LiXiang! :slightly_smiling_face: 

This has been fixed now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.0.4
