### ISSUE TITLE
[v13] Trying to set HTMLAudioElement.autoplay crashes

### ISSUE THREAD

**Issue by SimonSimCity** [capricorn86/happy-dom#1195]
**Describe the bug**

Trying to set `HTMLAudioElement.autplay` crashes

**To Reproduce**
Run this code:
```js
const audio = new HTMLAudioElement();
audio.autoplay = true;
```

**Expected behavior**
Should set the property to `true`

This happens since updating to the new major version v13.

**Comment by capricorn86** [comment]
Thank you for reporting @SimonSimCity! :slightly_smiling_face: 

`new HTMLAudioElement()` shouldn't be possible and is not something that is supported in the browser either.

The correct statement is `document.createElement('audio')` or `new Audio()`.

**Comment by capricorn86** [comment]
I will close this issue. Please re-open if the above answer didn't solve the problem for you.
