### ISSUE TITLE
[v13] Error: Cannot read properties of null (reading 'subtree')

### ISSUE THREAD

**Issue by rothsandro** [capricorn86/happy-dom#1217]
**Describe the bug**

We use React and  [DevExtreme components](https://js.devexpress.com/). After updating to happy-dom 13, some of our tests are failing with the following message:

> TypeError: Cannot read properties of null (reading 'subtree')
 ❯ Function.removeChild node_modules/happy-dom/src/nodes/node/NodeUtility.ts:127:26
 ❯ Function.removeChild node_modules/happy-dom/src/nodes/element/ElementUtility.ts:122:15
 ❯ HTMLElement.removeChild node_modules/happy-dom/src/nodes/element/Element.ts:507:25
 ❯ node_modules/devextreme-react/cjs/core/component-base.js:150:183
 ❯ Popover.ComponentBase.componentWillUnmount node_modules/devextreme-react/cjs/core/component-base.js:150:77
 ❯ Popover.Component.componentWillUnmount node_modules/devextreme-react/cjs/core/component.js:68:47
 ❯ callComponentWillUnmountWithTimer node_modules/react-dom/cjs/react-dom.development.js:22857:14
 ❯ safelyCallComponentWillUnmount node_modules/react-dom/cjs/react-dom.development.js:22873:5
 ❯ commitDeletionEffectsOnFiber node_modules/react-dom/cjs/react-dom.development.js:24129:13

The problem can be reproduced with the following simple test:

```tsx
import { Popover } from "devextreme-react/popover";
import { render, screen } from "@testing-library/react";
import { test } from "vitest";

test("popover", async () => {
  render(
    <Popover visible>
      <div>Content</div>
    </Popover>
  );

  await screen.findByText("Content");
});
```

**To Reproduce**
1. Clone the [repro](https://github.com/rothsandro/repro.happy-dom-13-subtree)
2. Install dependencies: `npm i`
3. Run the tests via `npm run test`

**Expected behavior**
The tests should run successfully.

**Device:**
 - OS: macOS
 - Browser: Brave 120

**Additional context**

This only happens with happy-dom v13 and when [Vitest globals](https://vitest.dev/config/#globals) are enabled (even if we don't rely on globals but import the functions). It works when downgrading to happy-dom v12 or when disabling Vitest globals.

**Comment by zachlankton** [comment]
Having the same problem myself, working on a fix and PR right now

**Comment by zachlankton** [comment]
I've published a temporary package for myself, you are welcome to use if you'd like, just remember this is temporary until the fix gets released.

Here's how I'm doing my package.json

```json
"devDependencies": {
    "happy-dom": "npm:zachlankton-happy-dom@13.3.2",
  },
```
