### ISSUE TITLE
Support for node/element.matches

### ISSUE THREAD

**Issue by beckerei** [capricorn86/happy-dom#123]
I wanted to try if I can speed up our test runs by replacing jsdom with happy-dom.

We use react with react with @testing-library/react which uses https://github.com/testing-library/dom-testing-library
As far as I can tell most of the matchers there make heavy use of https://developer.mozilla.org/en-US/docs/Web/API/Element/matches

Happy to contribute if you want to support it.

**Comment by capricorn86** [comment]
Nice to hear that you want to try out Happy DOM! :slightly_smiling_face: 

Yes, that is definitely something that should be supported.

Always nice with contributions! Let me know if you need any directions. I am happy to do it as well if you are busy :slightly_smiling_face:

**Comment by capricorn86** [comment]
@beckerei I have now added support for Element.matches().

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.10.0

**Comment by beckerei** [comment]
🏎️ thanks. I'll give it a try.

**Comment by beckerei** [comment]
Just to follow this up: The selector works, but I still run into a various range of errors.
E.g. 
> ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.

and increased heap size. 

But also the project has a very complex setup and runs around 3635 tests.I'll follow your project and might pick testing up again when I addressed some other performance bottlenecks. 

Still nice to see alternatives floating around 👍

**Comment by capricorn86** [comment]
@beckerei thats a lot of tests :slightly_smiling_face:

Too bad you can't use happy-dom at the moment.

I looked in to the problem you described and I think I managed to solve it. I noticed that asynchronous tasks like timeouts where not canceled properly during teardown, so I believe that at least that problem is fixed :slightly_smiling_face:

**Comment by beckerei** [comment]
> @beckerei thats a lot of tests 🙂

yes, it's a huge mono repo which is constantly growing 😁 

I'll look into it again in a couple of days. Some suites may still require jsdom, e.g. for File/Blob. But I'm still curious about the overall performance difference. The vast majority of suites are standard dom/fetch interactions.

And thanks for the effort you put into this! 🙏

**Comment by capricorn86** [comment]
@beckerei I have not added support for File, FileReader, Blob etc.

See release notes:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.0
