### ISSUE TITLE
window.location.href = 'value' returns 'about:blank' in v13.0.0

### ISSUE THREAD

**Issue by gkiely** [capricorn86/happy-dom#1230]
**Describe the bug**
In versions prior to v13, using `GlobalRegistrator.register()` and `window.location.href = 'value'` would set the href value. In v13 it always returns the value `"about:blank"`

In addition to this, clicking on links no longer updates window.location.href.

**To Reproduce**
```ts
import { GlobalRegistrator } from '@happy-dom/global-registrator';
GlobalRegistrator.register();
window.location.href = 'value';
console.log(window.location.href); // "about:blank"
```

**Expected behavior**
Prints the value that was set.

**Device:**
 - OS: macOS
 - Version: 13

**Comment by gkiely** [comment]
Example passing (v12.10.3):
https://codesandbox.io/p/devbox/eloquent-shannon-6wqgph?file=%2Findex.test.tsx

Example failing (v13.2.1):
https://codesandbox.io/p/devbox/brave-resonance-9d8f7d?file=%2Findex.test.tsx

**Comment by gkiely** [comment]
Workaround is to set:
```ts
Object.defineProperty(window.location, 'href', {
  writable: true,
});
```

**Comment by gkiely** [comment]
@capricorn86 Thank you!

**Comment by capricorn86** [comment]
No problem @gkiely! :slightly_smiling_face:
