### ISSUE TITLE
AbortSignal.throwIfAborted is not a function

### ISSUE THREAD

**Issue by allevo** [capricorn86/happy-dom#1255]
**Is your feature request related to a problem? Please describe.**
I'm developing a plain JavaScript library that heavily uses `AbortController` and `AbortSignal`. In particular, I use the `controller.signal.throwIfAborted` method, but it seems not implemented in `happy-dom`.

**Describe the solution you'd like**
I want the method to be implemented.

**Describe alternatives you've considered**
I can manage it manually with the following code
```ts
if (controller.signal.aborted) {
  throw new Error('aborted')
}
```
But it isn't enjoyable.

**Additional context**
This feature request is compliant with the standard https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/throwIfAborted
If you want, I can send a PR with the implementation.

**Comment by capricorn86** [comment]
Thank you for reporting @allevo! :slightly_smiling_face: 

Support for `throwIfAborted()` has been added now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.9.0
