### ISSUE TITLE
Error creating custom element

### ISSUE THREAD

**Issue by bavoco** [capricorn86/happy-dom#1258]
**Describe the bug**
The following code works in <=13.0.5 but fails from 13.0.6 up to 13.3.8

**To Reproduce**
```javascript
// repro.js
import { Window } from "happy-dom";

const win = new Window({});

globalThis.window = win;
globalThis.document = win.document;
globalThis.customElements = win.customElements;
globalThis.HTMLElement = win.HTMLElement;

class MyCustomElement extends HTMLElement {}
customElements.define("my-custom-element", MyCustomElement);

document.body.append(new MyCustomElement());
```
Execute `node repro.js`

Results in:
```shell
Error: Failed to construct "Node": No owner document in queue. Please use "NodeFactory" to create instances of a Node.
```

**Expected behavior**
No error

Probably related to changes in: #1207, #1208

**Comment by capricorn86** [comment]
Thank you for reporting @bavoco! :slightly_smiling_face: 

The problem should be fixed now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.7.8
