### ISSUE TITLE
`XMLSerializer` attribute serialization is vulnerable to injection due to lack of escaping

### ISSUE THREAD

**Issue by lgarron** [capricorn86/happy-dom#1265]
**Describe the bug**
`XMLSerializer` output does not escape the `href` attribute properly. It's quite possible this is a symptom of a wider issue, this is just the first I encountered.

**To Reproduce**
Run the following:

```ts
import { Window, XMLSerializer } from "happy-dom";
const document = new Window().document;

const a = document.body.appendChild(document.createElement("a"));
a.href = 'https://example.com" style="font-size: 500%;';
a.textContent = "I'm a link!"
console.log(new XMLSerializer().serializeToString(a));
```

This results in the following output:

```
<a href="https://example.com" style="font-size: 500%;">I'm a link!</a>
```

By contrast, all browsers safely apply the proper serialization:

```
<a xmlns="http://www.w3.org/1999/xhtml" href="https://example.com&quot; style=&quot;font-size: 500%;">I'm a link!</a>
```

`XMLSerializer` is a great tool for quick DOM prototyping in a web environment when you need to do some light DOM processing with an HTML file as output. Specifically, it's great because browsers invest a lot of effort into correct and secure implementations. So if the DOM operations handle untrusted data safely (i.e. avoid passing them to any [injection sinks](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API#injection_sinks)), then the output should be safe.

I was hoping to use `happy-dom` to emulate the same behaviour without firing up a full browser, but I'm sorry to say that `happy-dom`'s current behaviour is a major red flag for using it with any input that it not 100% trusted. 😬

(Also, this project doesn't seem to have a vulnerability report process. I would recommend adding one.)

**Comment by sortigoza** [comment]
The incorrect escaping also affects saving a proper HTML file.

For example, when setting `innerHTML` of an element to include a `style` attribute with a `url()` containing escaped quotes, the serialization process incorrectly converts these to double quotes, which alters the expected output.

Node version: v18.17.1
happy-dom version: v13.10.1

Here is a snippet to reproduce the issue:

```node
const { Window } = require('happy-dom');
const fs = require('fs');

const window = new Window({ url: 'https://localhost:8080' });
const document = window.document;

const domStr =
  '<a href="https://www.com/" \
style="background-image: url(&quot;https://cdn.cookie.org/image.svg&quot;);"> \
</a>';

document.body.innerHTML = domStr;

console.log(document.body.getInnerHTML());
fs.writeFileSync(`bad.html`, document.body.getInnerHTML(), 'utf8');

// Output:
// <a href="https://www.com/" style="background-image: url("https://cdn.cookie.org/image.svg");"></a>

// Expected:
// <a href="https://www.com/" style="background-image: url('https://cdn.cookie.org/image.svg');"></a>

```

**Comment by capricorn86** [comment]
Thank you for reporting @lgarron and @sortigoza! :slightly_smiling_face: 

I believe this has been fixed now in v15 of Happy DOM. Please re-open the ticket if it has not been fixed.
