### ISSUE TITLE
Error with svg in v13.4.1

### ISSUE THREAD

**Issue by ja1984** [capricorn86/happy-dom#1271]
**Describe the bug**
There seems to be an issue with finding svgs in v13.4.1 We have multiple tests that have been running just fine, but after updating to v13.4.1 for some reason one of our tests fails.

The code generated:
```
<td data-v-d8968c14="">
            <div data-v-d8968c14="" data-balloon="Active" class="tooltip-active" data-balloon-pos="up"><svg data-v-d8968c14="" class="svg-inline--fa fa-circle no-status success" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-test-id="active-collection">
                <path class="" fill="currentColor" d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"></path>
              </svg></div>
          </td>
```

Our expect
`expect(wrapper.find('svg.success').exists()).toBe(true);`

I tried with .success only and it succeeded, then tried with only svg and it failed. Downgrading back to 13.3.8 and all tests work again.

**Comment by kaderson** [comment]
hii @capricorn86  this is my code, there is a bug with this version v13.4.1, I can't get the value of svg, path when I do it:```
  const window = new Window()
  const document = window.document

  document.body.innerHTML = makerSvg
  const bodyElement = document.querySelector('body')
  const svgElement = bodyElement.querySelector('svg') // return null
  const pathElement = svgElement.querySelector('path') // return null

```
```
<body>
	<svg width="3955.829" height="880" viewBox="0 0 3955.829 880" xmlns="http://www.w3.org/2000/svg" id="id_svg_model">
		<g id="svgGroup" stroke-linecap="round" fill-rule="evenodd" font-size="9pt" 
			stroke="#000" stroke-width="0.25mm" fill="none" style="stroke:#000;stroke-width:0.25mm;fill:none"
		>
			<path d="M 0 0 L 0 880 L 1272.697 880 A 80 80 0 0 0 1350.647 817.996 L 1416.442 533.006 A 120 120 0 0 1 1533.367 440 L 1977.914 440 L 2422.462 440 A 120 120 0 0 1 2539.386 533.006 
				L 2605.182 817.996 A 80 80 0 0 0 2683.131 880 L 3955.829 880 L 3955.829 0" 
				vector-effect="non-scaling-stroke">
			</path>
		</g>
	</svg>
</body>
```

**Comment by capricorn86** [comment]
Thank you for reporting @ja1984 and @kaderson! :slightly_smiling_face: 

The problem should be fixed now:
https://github.com/capricorn86/happy-dom/releases/tag/v13.5.1

I also added a unit test for Vue here:
https://github.com/capricorn86/happy-dom/releases/tag/v13.5.2
