### ISSUE TITLE
Add support for `<!>` comment shorthand

### ISSUE THREAD

**Issue by dummdidumm** [capricorn86/happy-dom#1288]
**Is your feature request related to a problem? Please describe.**
The browser (jsdom, too) auto-repairs `<!>` tags to proper comments (e.g. `<!---->`). happy-dom does not do that and treats that character sequence as text. Frameworks like Svelte or Solid use this to their advantage to safe a bit of space when generating the template strings from which the component DOM tree is constructed.

**Describe the solution you'd like**
Add support for the shorthand, so that the following works as expected:

```js
/**
 * @vitest-environment happy-dom
 */
import { test } from "vitest";

test("can render", () => {
  const root = document.createElement("div");
  root.innerHTML = "x<!>y";
  document.body.append(root);
  console.log(document.body.innerHTML);
  // should print <div>x<!---->y</div> , currently prints <div>x<!>y</div>
});
```

**Describe alternatives you've considered**
None

**Comment by capricorn86** [comment]
Thank you for reporting @dummdidumm! :slightly_smiling_face: 

I have made a fix now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.3.6

**Comment by dummdidumm** [comment]
Thank you!
