### ISSUE TITLE
Cloning a response twice locks the ReadableStream

### ISSUE THREAD

**Issue by cprecioso** [capricorn86/happy-dom#1294]
**Describe the bug**

> A continuation of #1216 

In `Response`, when cloning a clone, none of them can then be consumed, they throw an "Invalid state: ReadableStream is locked" error.

**To Reproduce**

```ts
// test.mjs
import { Window } from "happy-dom";

const window = new Window();

const originalResponse = window.Response.json({ foo: 'bar' });

const clone1 = originalResponse.clone();
const clone2 = clone1.clone();

// Any of the following statements, in any order
// will throw an Invalid State Error
console.log(await clone1.text());
console.log(await clone2.text());
```

**Expected behavior**
Both response objects return the correct response text even if the other one has been consumed.
You can copy the code (minus the `new Window()`) to your browser console and see it working correctly.

**Device:**
node v20.11.0 on macOS Sonoma 14.3.1

**Additional context**
I'm trying to run [ky](https://github.com/sindresorhus/ky/) on happy-dom, which uses the following pattern:

```ts
// (Pseudo code)

const response = await fetch(...)
const cloneA = response.clone()

const cloneB = cloneA.clone()
if ((await cloneB.arrayBuffer().byteLength === 0) return ""

return cloneA.json()
```

https://github.com/sindresorhus/ky/blob/051d7ab4fd39743758b49012b62aaf420f7ca53d/source/core/Ky.ts#L82-L106

**Comment by capricorn86** [comment]
Thank you @cprecioso for reporting! :slightly_smiling_face: 

There is a fix in now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v13.7.6
