### ISSUE TITLE
`el.shadowRoot?.querySelector(":host")` returns null with happy-dom after 13.8.5

### ISSUE THREAD

**Issue by odanado** [capricorn86/happy-dom#1313]
**Describe the bug**
I found that when I create a custom element and run `querySelector(":host")` against `shadowRoot`, the return value is different depending on the version of `happy-dom`.

**To Reproduce**
1. git clone https://github.com/odan-sandbox/happy-dom-query-selector-with-lit-sandbox
2. run `npm i`
3. run `node src/index.js`

**Expected behavior**
Expect non-null values to be returned for both happy-dom@13.8.4 and happy-dom@13.8.5.

**Device:**
 - Node.js: v18.12.1
 - happy-dom: 13.8.4 and 13.8.5

**Comment by capricorn86** [comment]
Thank you for reporting @odanado! :slightly_smiling_face: 

I believe that the current behavior is correct, which is to always return null for the query selector ':host' as it is pseudo element selector, which is not possible to use together with `querySelector()`.

When I run the example code in Chrome, I get the same result.

**Comment by capricorn86** [comment]
I'm closing this now. Please re-open if your problem hasn't been solved based on the answer.

**Comment by odanado** [comment]
Thank you for a comment.
I also checked the behavior in Chrome.

I use [host property](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/host)  instead of `:host`.
