### ISSUE TITLE
Property localStorage is not defined in Vitest using happy-dom@14.1.1

### ISSUE THREAD

**Issue by ottomated** [capricorn86/happy-dom#1339]
**Describe the bug**
Prior to 14.1.1, global uses of `localStorage` would work as expected. They no longer do.

**To Reproduce**
See [codesandbox repro](https://codesandbox.io/p/devbox/sad-moser-y4rfmc?workspaceId=1edaa6c3-4a0c-447b-ad03-32a32cd0ca45&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu030zqt00072066lk13bpav%2522%252C%2522sizes%2522%253A%255B57.48524203%252C42.51475797%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu030zqt00022066d1loy55l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu030zqt000420667izyr9d2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu030zqt00062066mt269r0f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu030zqt00022066d1loy55l%2522%253A%257B%2522id%2522%253A%2522clu030zqt00022066d1loy55l%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu030zqt00062066mt269r0f%2522%253A%257B%2522id%2522%253A%2522clu030zqt00062066mt269r0f%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu030zqt000420667izyr9d2%2522%253A%257B%2522id%2522%253A%2522clu030zqt000420667izyr9d2%2522%252C%2522activeTabId%2522%253A%2522clu039kma01tk2066tqwrofc2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522test%2522%252C%2522id%2522%253A%2522clu039kma01tk2066tqwrofc2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
Global uses of window globals should work as expected.

**Device:**
All

**Comment by capricorn86** [comment]
Thank you for reporting @ottomated! :slightly_smiling_face: 

I'm trying to reproduce the problem, but it seems like it is working in my environment.

I can't access the codesandbox. Is it possible for you to change permission?

**Comment by capricorn86** [comment]
It seems like it is working here:
https://stackblitz.com/edit/stackblitz-starters-ghue6z?file=index.js

**Comment by ottomated** [comment]
Updated permissions

**Comment by capricorn86** [comment]
@ottomated thank you for updating permissions.

There is a fix in now that solves the problem:
https://github.com/capricorn86/happy-dom/releases/tag/v14.1.2

I described the problem and solution in the release notes:

- Fixes problem with properties defined as getters and setters not being registered globally by Vitest
   - The problem occurred as Vitest is using Object.getOwnPropertyDescriptors(window) to read which properties to register globally, but getters and setters are defined on the prototype
    - To solve the problem, `GlobalWindow` now defines the properties on the instance when it is constructed

**Comment by ottomated** [comment]
Thanks for the quick fix!
