### ISSUE TITLE
Incorrect custom element tag name in innerHTML

### ISSUE THREAD

**Issue by bavoco** [capricorn86/happy-dom#1354]
**Describe the bug**
The output of a custom element tagname in innerHTML is null.

**To Reproduce**
```js
// repro.js
import { Window } from "happy-dom";

const win = new Window();

class myCustomElement extends win.HTMLElement {}
win.customElements.define("my-custom-element", myCustomElement);

win.document.body.append(new myCustomElement());
console.log(win.document.body.innerHTML);
```

Running `node repro.js` outputs:
```
<null></null>
```

**Expected behavior**
```
<my-custom-element></my-custom-element>
```

**Version:**
 - Happy-dom: 14.3.3
 - Node: 21.5.0

**Additional context**
Interestingly `console.log(win.document.body.firstChild.tagName)` outputs `MY-CUSTOM-ELEMENT`

**Comment by capricorn86** [comment]
Thank you for reporting @bavoco! :slightly_smiling_face: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.3.5
