### ISSUE TITLE
Attempting to change configurable attribute of unconfigurable property

### ISSUE THREAD

**Issue by PabloGracia** [capricorn86/happy-dom#1362]
**Describe the bug**
I want to use RTL in bun, and according to the documentation in bun's page, it is advised to setup happy-dom for this purpose: https://bun.sh/docs/test/dom

I've followed the steps to the letter, but when running `bun test` I get the following error:

```
app/[...]/mytest.test.tsx:
35 |                             ...windowPropertyDescriptor,
36 |                             value: windowPropertyDescriptor.value.bind(global)
37 |                         });
38 |                     }
39 |                     else {
40 |                         Object.defineProperty(global, key, windowPropertyDescriptor);

TypeError: Attempting to change configurable attribute of unconfigurable property.
      at register (/[my_project_route]/node_modules/@happy-dom/global-registrator/lib/GlobalRegistrator.js:40:24)
```

**To Reproduce**
1. Go to https://bun.sh/docs/test/dom
2. Set up the project according to the happy-dom specifications.
3. Run `bun test`

**Expected behavior**
The test runs without errors. From the error this seems to be on happy-dom side rather than on bun's, so I'm opening the issue here.

**Comment by capricorn86** [comment]
Hi @PabloGracia! :slightly_smiling_face: 

I have attempted to reproduce your problem without success. I have tested to follow the Bun guide and it worked for me.

There is a new fix in now that may solve your problem:
https://github.com/capricorn86/happy-dom/releases/tag/v14.5.1

If it doesn't solve your problem, can you please provide with a reproducible example or a repository?

**Comment by fabriziomarmitt** [comment]
Hey @PabloGracia, I was having same issue, then I updated bun to version 1.1.2 and then it worked just fine.
