### ISSUE TITLE
The value of `getPropertyValue` is wrong when using style attributes and custom properties

### ISSUE THREAD

**Issue by odanado** [capricorn86/happy-dom#1364]
**Describe the bug**
The value of `getPropertyValue` is wrong when using style attributes and custom properties.

```js
import { Window } from "happy-dom";

const window = new Window({ url: "https://localhost:8080" });

const div = window.document.createElement("div");
div.setAttribute("style", "--my-color1: pink;");

const style = window.document.createElement("style");

style.textContent = `
  div {
    border-color: var(--my-color1);
  }
`;

window.document.head.appendChild(style);
window.document.body.appendChild(div);

// OK: expected: pink, actual: "" (empty string)
console.log(window.getComputedStyle(div).getPropertyValue("border-color"));

```

**To Reproduce**
1. Run `git clone https://github.com/odan-sandbox/happy-dom-getComputedStyle-with-css-variables-sandbox`
2. Run `npm ci`
3. Run `node src/repro-non-fallback.js`

**Expected behavior**
`--my-color1` is defined, so the `background-color` should be pink.

**Device:**
- Node.js: v18.12.1
- happy-dom: 14.3.6

**Comment by capricorn86** [comment]
Thank you for reporting @odanado! :slightly_smiling_face: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.3.10

**Comment by odanado** [comment]
Thank you!
