### ISSUE TITLE
querySelector pseudo class :has not working

### ISSUE THREAD

**Issue by guenichone** [capricorn86/happy-dom#1373]
**Describe the bug**
`:has` pseudo selector in query does not seem to be supported.

w3c spec: https://www.w3.org/TR/selectors-4/#has-pseudo

working sample: https://try.jsoup.org/ with query : `p:has(a[href*=jsoup])`

**To Reproduce**

Create a test with

```
const {container} = render(<html>
            <head>
                <title>Try jsoup</title>
            </head>
            <body>
            <p>This is <a href="https://jsoup.org/">jsoup</a>.</p>
            </body>
            </html>
        );

const result1 = container.querySelector('a') // this is not null
const result2 = container.querySelector('p:has(a[href*=jsoup])') // this is null where it should not
```
![image](https://github.com/capricorn86/happy-dom/assets/1672227/c14c6e15-1844-4aef-a5ad-dccd8ae69d60)

**Expected behavior**
result should give me back the <p> element in the <body>
<img width="464" alt="image" src="https://github.com/capricorn86/happy-dom/assets/1672227/36af5118-1079-4284-ad01-854ed77f664a">

**Device:**
 - OS: [iOS]
 - Browser [brave]
 - Version [[Version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (arm64)](https://brave.com/latest/)]

**Comment by timche** [comment]
Were you able to find any solution for this? Running into the same problem.

**Comment by guenichone** [comment]
> Were you able to find any solution for this? Running into the same problem.

Unfortunately not :(

**Comment by timche** [comment]
> > Were you able to find any solution for this? Running into the same problem.
> 
> 
> 
> Unfortunately not :(

Too bad it's not getting attention, because this library is great. I've switched to https://github.com/WebReflection/linkedom since then, which has support.

**Comment by capricorn86** [comment]
Thank you for reporting @guenichone and @timche! :slightly_smiling_face: 

Happy DOM now has support for the `:has` pseudo selector.
