### ISSUE TITLE
Incorrect dependency for @happy-dom/jest-environment.

### ISSUE THREAD

**Issue by CrOrc** [capricorn86/happy-dom#139]
Package: @happy-dom/jest-environment
Version: 1.10.4
Vue is in dependencies for @happy-dom/jest-environment.
It should be in devDependencies instead.
[Link to package.json](https://github.com/capricorn86/happy-dom/blob/b31879ad8084c8eddec115d8e925b165d657021a/packages/jest-environment/package.json#L48)

**Comment by capricorn86** [comment]
Thank you for reporting @CrOrc! I will fix it as soon as possible.

**Comment by capricorn86** [comment]
@CrOrc the bug has been fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.2
