### ISSUE TITLE
Unable to correctly `cloneNode` through `Node.prototype`

### ISSUE THREAD

**Issue by mcous** [capricorn86/happy-dom#1392]
**Describe the bug**

Hello again! My last experience filing a bug was so good I thought I'd do another one 😄

The upcoming Svelte v5 calls various `Node` and `Element` methods [through their prototypes](https://github.com/sveltejs/svelte/blob/6b7f1162adac0e9c86fa58a4fce4acff5843eb60/packages/svelte/src/internal/client/dom/operations.js#L53) to "avoid doing expensive prototype chain lookups."

```js
node_prototype = Node.prototype;
// ...
clone_node_method = node_prototype.cloneNode;
// ...
export function clone_node(node, deep) {
	return clone_node_method.call(node, deep);
}
```

This works fine in the browser, but in happy-dom, due to (if I'm reading the code correctly) how subclasses of `Node` override `cloneNode`, Svelte v5 fails to properly clone nodes. This is problematic, because `cloneNode` is used to initially mount components into the DOM.

Svelte calls the following methods through the prototype. From a quick scan of the code, I think `cloneNode` is the only problematic one, but I'd want to verify through tests.

- `Node.prototype.cloneNode` - Does not work
- `Node.prototype.appendChild` - Looks ok
- `Node.prototype.firstChild` - Looks ok
- `Node.prototype.nextSibling` - Looks ok
- `Element.prototype.className` - Looks ok

Related to:

- https://github.com/testing-library/svelte-testing-library/issues/319
- https://github.com/sveltejs/svelte/issues/10358

**To Reproduce**

An easy way to see how things get messed up is to check the `tagName` of a cloned node. If you use `Node.prototype.cloneNode.call`, the clone will have a `tagName` of `null`, which will break other things internally to happy-dom and downstream.

```ts
// index.js
import { Window } from "happy-dom";

const window = new Window({ url: "http://localhost:3000" });
const document = window.document;
const cloneNode = window.Node.prototype.cloneNode;

const element = document.createElement("div");
const clone = element.cloneNode();
const prototypeClone = cloneNode.call(element);

console.log("clone", clone.tagName);
console.log("prototypeClone", prototypeClone.tagName);
```

```shell
> node index.js
clone1 DIV
clone2 null
```

**Expected behavior**

I expect the various `Node.prototype` methods, such as `cloneNode`, to fully work on all node types, as they do in the browser.

**Additional context**

Tested on `happy-dom@14.7.0`

This issue has already been reported as a feature request in #1165, but I felt it was important to highlight as a bug, because it is a material difference in how happy-dom behaves vs the browser. Feel free to close out as a duplicate if you feel this is already adequately tracked!

**Comment by capricorn86** [comment]
Thank you for reporting @mcous! :slightly_smiling_face: 

The problem has been fixed now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.7.1

I'm not sure why Svelte is doing this as I can't see any performance benefits of calling `Node.prototype.cloneNode()` vs `element.cloneNode()`. The reason for why it even works in the browser is because there is no prototype chain (`HTMLElement.prototype.cloneNode` equals `Node.prototype.cloneNode`). Maybe I have missed something :shrug:
