### ISSUE TITLE
Mislabelled test in jest-environment tests

### ISSUE THREAD

**Issue by TreyVigus** [capricorn86/happy-dom#1394]
Hi! I'm a big fan of the repo and was hoping to make a small contribution! I can submit a PR for this small issue

**Describe the bug**
The `describe` block in `Angular.test.js` is named `React`

**Expected behavior**
It should be titled `Angular` instead

**Comment by capricorn86** [comment]
You are always welcome to make a contribution @TreyVigus! :slightly_smiling_face:

**Comment by TreyVigus** [comment]
Thanks @capricorn86! Looking forward to making some bigger contributions in the future!
