### ISSUE TITLE
Regression from 13.6.2 to 13.7.0: clicking a checkbox no longer fires a `change` event

### ISSUE THREAD

**Issue by cyyynthia** [capricorn86/happy-dom#1397]
**Describe the bug**
When triggering a click event on an `HTMLInputElement`, the `change` event is no longer fired in version 13.7.0 and up. Seems to affect all versions up to latest.

**To Reproduce**
1. Get an HTMLInputElement with an event listener attached to the `change` event
2. Trigger a click (using `.dispatchEvent(new MouseEvent('click'))`
3. Observe that the event listener hasn't been fired

**Expected behavior**
The `click` and `change` events should both be fired.

**Device:**
 - OS: Windows, Linux
 - Browser: Node
 - Version: 13.7.0 and up

**Comment by cyyynthia** [comment]
After a bit more testing; it seems the tooling I'm using does dispatch a `new MouseEvent('click')`, which does not extend `PointerEvent` causing the `instanceof` checks to fail. Hope this helps!

**Comment by dbritto-dev** [comment]
@capricorn86 👆🏼

**Comment by capricorn86** [comment]
Thank you for reporting @cyyynthia and @dbritto-dev! :slightly_smiling_face: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.10.2
