### ISSUE TITLE
Is history api supported

### ISSUE THREAD

**Issue by FabianSellmann** [capricorn86/happy-dom#140]
Just tried this out with our work codebase, but all the tests fail due to react-router accessing properties on`window.history`. Is this expected to be available eventually, or would users need to shim this themselfs?

**Comment by capricorn86** [comment]
Thank you for reporting @FabianSellmann!

`window.history` is not supported, but I can add support for it. I will probably add it sometime this week. I let you know when it has been added :slightly_smiling_face:

**Comment by capricorn86** [comment]
@FabianSellmann I have added support for the History API now :slightly_smiling_face:

The implementation does not do anything when modifying the History, but it should be enough to support libraries like react-router.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.13.0

**Comment by ksjogo** [comment]
Is it planned/would it be possible to also implement the history api for navigation?
We are looking to speed up our vitest runs, but a lot of them have some navigation in them.
