### ISSUE TITLE
v13.6.2->13.7.0 missing some of my events from vue app

### ISSUE THREAD

**Issue by VividLemon** [capricorn86/happy-dom#1409]
**Describe the bug**

During a change from v13 to v14, I noticed that my tests had randomly broke. I assumed it was something internally, but when regressing back my package.json, everything worked fine. I pushed each version one by one until I found it was v14 of happy dom.

**To Reproduce**

I have the two following components:

child:
```html
<script setup lang="ts">
const localValue = defineModel<string>({default: ''})
</script>

<template>
  <input
      v-model="localValue"
      id="foo"
      type="checkbox"
    />
    <label>
      <slot />
    </label>
</template>
```
parent:
```html
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <HelloWorld @update:model-value="console.log('modelvalue change', $event)" />
</template>
```
When done rawly in the browser (firefox) `document.getElementById('foo').click()` I get `modelvalue change false` This is correct.

However, when I go to my test: 

```ts
describe('HelloWorld', () => {
  it('renders properly', async () => {
    const wrapper = mount(HelloWorld, { props: { modelValue: '' } })
    await wrapper.get('input').trigger('click')
    expect(wrapper.emitted()).toHaveProperty('update:modelValue')
  })
})
```
This should not be failing.

What's perplexing is that in my example reproduction, I don't get anything in the test. All versions seem to fail... Unlike the main repository just failing between those two versions:
[vue-project.zip](https://github.com/capricorn86/happy-dom/files/14971839/vue-project.zip)

As said, in my real repository, I'm only seeing the issue when going between `13.6.2->13.7.0 ` at https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/6ea759874fd41d3da08ae3cafee052e19b3e51e1/packages/bootstrap-vue-next/src/components/BFormCheckbox/form-checkbox.spec.ts#L600

It may be more useful to pull that repository, and view the issue there. For now, I'm going to keep the happy-dom version on 13.6.2. The issue exists in v14 latest

**Expected behavior**

The emitted() return should have `update:modelValue` as a key in the object -- it should not be undefined, and the test should pass.

**Screenshots**

![image](https://github.com/capricorn86/happy-dom/assets/31498096/ef4ce833-2a82-4dd3-8203-432e684d1fb7)
v13.6.2

![image](https://github.com/capricorn86/happy-dom/assets/31498096/716cf8ce-9c18-4be2-a66f-829d17b0f127)
v13.7.0

**Device:**

**Additional context**

**Comment by dbritto-dev** [comment]
@capricorn86 I'm facing the same issues some changes added in v13.7.0 broke a bunch of my tests

**Comment by cyyynthia** [comment]
I initially reported as #1397 ; I noted that the checkbox behavior is implemented by doing an `instanceof PointerEvent` test that fails

PointerEvent should be a subclass of MouseEvent, and that check should check for instances of MouseEvent

**Comment by capricorn86** [comment]
Thank you for reporting @VividLemon, @dbritto-dev and @cyyynthia! :slightly_smiling_face: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v14.10.2
