### ISSUE TITLE
Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by brunano21** [capricorn86/happy-dom#141]
Hi,
I'm trying to load some custom elements before running Jest tests for an angular library. Some of the components of this library are using custom elements built with Stencil.js.
I'm also using jest-preset-angular into test-setup.js.

When I set `testEnvironment: '@happy-dom/jest-environment' into jest.jconfig.js and run my tests I get the following:

```
Test suite failed to run

TypeError: Cannot read property 'metadata' of undefined
at Object.<anonymous> (../../node_modules/jest-preset-angular/build/reflectMetadata.js:10:14)

```
Packages:
```
"jest": "25.2.3",
"jest-preset-angular": "8.1.2",
```

**Comment by capricorn86** [comment]
Hi @brunano21!

Thank you for reporting! :slightly_smiling_face: 

I will try to reproduce the problem and create an integration test for it. I will let you know when it has been fixed.

**Comment by brunano21** [comment]
Hey @capricorn86, do you have any update on this?

**Comment by capricorn86** [comment]
@brunano21 my plan is to fix it sometime this weekend.

**Comment by capricorn86** [comment]
@brunano21 the bug has now been fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.1
