### ISSUE TITLE
script not evaluated on add

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#142]
# Problem

```js
const window = new Window();
const document = window.document;
const script2 = window.document.createElement("script");
script2.textContent = `console.log("hiiii"); window._chris_ = 1;`;
window.document.head.appendChild(script2);
console.log(window._chris_) // undefineed
```

i then expect `window._chris_` to be defined. was that a bad assumption on my part, or is there feasibly an issue that the script is not evaluation, and not mutating the correct reference?

Thanks!

**Comment by capricorn86** [comment]
Hi @cdaringe!
Support for script evaluation has not been added yet, but I can add it :slightly_smiling_face: 

As it might be dangerous to do in some situations I will have to look into how we can enable/disable the feature. I will let you know when I have added support for it.

**Comment by capricorn86** [comment]
@cdaringe support for HTMLScriptElement has been added :slightly_smiling_face: 

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.12.0

**Comment by cdaringe** [comment]
incredible.

**Comment by cdaringe** [comment]
for other observers, the impl can be conveniently observed here https://github.com/capricorn86/happy-dom/compare/release/1.11.5...release/1.12.0
