### ISSUE TITLE
CSS selector fails querySelectorAll

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#143]
# Problem

`QuerySelector.querySelectorAll(this /* document */, ".console-output > *")`

yields

```
TypeError: Cannot read property 'startsWith' of undefined
    at new SelectorItem (node_modules/happy-dom/src/query-selector/SelectorItem.ts:27:38)
```

`getSelectorParts` inside of one of the inner loops yields: `[".console-output", ">"]` as the parts, which my gut says probably isn't correct.

**Comment by capricorn86** [comment]
Hi @cdaringe!

Thanks for reporting this bug! :slightly_smiling_face: 

The parts should probably be [".console-output", ">", "*"]. I think I know what the issue might be. I let you know when it has been fixed.

**Comment by capricorn86** [comment]
@cdaringe the bug has been fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.3

**Comment by cdaringe** [comment]
Excellent, thank you!
