### ISSUE TITLE
Fetch does not accept a request object in first parameter

### ISSUE THREAD

**Issue by jasonkuhrt** [capricorn86/happy-dom#1433]
**Describe the bug**

When trying to pass a request object to fetch the following error happens:

```
TypeError: Failed to parse URL from [object Request]
```

**To Reproduce**

```
const requestObject = new Request(input.url, {
    method: `POST`,
    body: '',
  })

  const response = await fetch(requestObject)
```

**Expected behavior**
Should accept request object in first parameter.

**Other**

It works with `jsdom`.

**Comment by kettanaito** [comment]
Some of MSW community members also encountering this: https://github.com/mswjs/msw/issues/2191.

**Comment by capricorn86** [comment]
Thank you for reporting @jasonkuhrt and @kettanaito! :slightly_smiling_face: 

This should be supported already in Happy DOM.

I have added an additional unit test to cover this now here:
https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/test/fetch/Fetch.test.ts#L270

Is it something that I'm missing? Is it possible to setup a reproducible example project somewhere?

**Comment by capricorn86** [comment]
By using the example project in https://github.com/mswjs/msw/issues/2191, I managed to find the problem.

This is a bug in Vitest, where Vitest is using the native fetch from Node.js and not the one from Happy DOM. It is using the Request and Response objects from Happy DOM. As the Request object is not recognizable by the native fetch, it will try to convert it to a string.

**Comment by capricorn86** [comment]
Bug created for Vitest:
https://github.com/vitest-dev/vitest/issues/6878

**Comment by kettanaito** [comment]
@capricorn86, outstanding work. Thank you so much!

**Comment by capricorn86** [comment]
The fix has been released now in Vitest. I'm closing this one now. Please re-open if the problem still exist.
