### ISSUE TITLE
broken querySelectorAll when the string contains new lines

### ISSUE THREAD

**Issue by masylum** [capricorn86/happy-dom#1461]
**Describe the bug**
When the selector contains new lines, `querySelectorAll` returns all sorts of things that it shouldn't.

**To Reproduce**

```
document.querySelectorAll(
  `pre, code, script, style, object, embed,
    iframe, form, input, textarea, button,
    select, option, nav`
)
```

and then compare with

```
document.querySelectorAll(
  'pre, code, script, style, object, embed, iframe, form, input, textarea, button, select, option, nav'
)
```

**Expected behavior**
it should be the same

**Comment by capricorn86** [comment]
Thank you for reporting @rothsandro! :slightly_smiling_face: 

There is a fix in now.

Big thanks to @syi0808 for providing with the fix!
