### ISSUE TITLE
inputMode attribute is set as `inputmode`

### ISSUE THREAD

**Issue by cluk3** [capricorn86/happy-dom#1487]
I'm testing wether an element has inputMode set to `none` given a specific condition. When I run `expect(input.inputMode).toBe('none');` the test fail cause inputMode is undefined but it does not fail if I write `expect(input!.inputmode).toBe('none');` (notice `inputmode` all lower case).
This doesn't happen with jsdom ( `expect(input.inputMode).toBe('none')` doesn't fail ).
Notice that also typescript is complaining when writing `inputmode` cause he is expecting the property to be called `inputMode`.

**To Reproduce**
1. set inputMode="none" to an input element
2. run `expect(input.inputMode).toBe('none');`

**Expected behavior**
The test should not fail as inputMode should be set to "none"

**Device:**
 - OS: MacOs Monterey

**Comment by capricorn86** [comment]
Thank you for reporting @cluk3! :slightly_smiling_face: 

It has been fixed now.
