### ISSUE TITLE
CORS headers not included in requests

### ISSUE THREAD

**Issue by rexxars** [capricorn86/happy-dom#1489]
**Describe the bug**
Cross-origin requests should always include the `Origin` header, and should be disallowed if the server does not respond with the `Access-Control-Allow-Origin` header matching either `*` or the origin sent. 

Currently, no `Origin` header is sent, and the preflight check also does not include the necessary `Access-Control-*` headers, although [it appears](https://github.com/capricorn86/happy-dom/blob/e6f91276d7b4549d17f5d67bd2f909723f4940b3/packages/happy-dom/src/fetch/Fetch.ts#L288-L291) that the intent _was_ to include these headers. I believe they are getting stripped away as "unsafe" because we're reusing Fetch here without any bypassing.

**To Reproduce**
1. Create and run the following script
```js
/* eslint-disable no-console */
import { createServer } from 'node:http';

import { Window } from 'happy-dom';

const happyWindow = new Window({ url: 'http://127.0.0.1:8080' });
const url = 'http://localhost:1234/';

const server = createServer((req, res) => {
  console.log('\nRequest:');
  console.log('  Method:', req.method);
  console.log('  Headers:');
  printHeaders(req.headers);

  res.writeHead(200);
  res.end();
  printCorrectness(req);
  return;
});

server.listen(1234, async () => {
  const res = await happyWindow.fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ hello: 'world' })
  });

  console.log('\nResponse:');
  console.log(`  Status: ${res.status}`);
  console.log('  Headers:');
  printHeaders(res.headers);

  const body = await res.text();
  console.log('  Body:', body);

  server.close();
});

function printHeaders(headers) {
  if (headers instanceof Headers) {
    for (const [header, value] of headers.entries()) {
      console.log(`    ${header}: ${value}`);
    }
  } else {
    for (const header in headers) {
      console.log(`    ${header}: ${headers[header]}`);
    }
  }
}

function printCorrectness(req) {
  const prefix = (msg) => `  [\x1b[31m\x1b[1mError\x1b[0m] ${msg}`;
  if (req.method === 'OPTIONS') {
    if (!('origin' in req.headers)) {
      console.error(prefix('No `origin` header on OPTIONS preflight request'));
    }

    if (!('access-control-request-method' in req.headers)) {
      console.error(
        prefix('No `access-control-request-method` header on OPTIONS preflight request')
      );
    }

    if (
      'access-control-request-headers' in req.headers &&
      req.headers['access-control-request-headers'].trim() === ''
    ) {
      console.error(prefix('`access-control-request-headers` should not be blank, if included'));
    }
  } else {
    console.error(prefix(`Non-options (${req.method}) request sent despite invalid/no preflight`));
  }
}
```
2. Observe that no `origin` header is included in either the OPTIONS or the POST request
3. Observe that no `access-control-request-method` header is included on the OPTIONS request

**Expected behavior**
- Cross-origin requests should always include the `origin` header

**Screenshots**
![image](https://github.com/user-attachments/assets/e123139b-13f6-466f-be66-bff8fb6a1384)

**Comment by elledienne** [comment]
We've been facing the same issue and can confirm the issue is that headers are being dropped here https://github.com/capricorn86/happy-dom/blob/e18524e8df9b642b6b7da069c1d76e53e9d216e4/packages/happy-dom/src/fetch/Request.ts#L88
