### ISSUE TITLE
Rename wiki page file from `Virtual-Console` to `VirtualConsole`

### ISSUE THREAD

**Issue by nobkd** [capricorn86/happy-dom#1503]
Please rename the wiki page `Virtual-Console` to `VirtualConsole`, because all the links in the wiki point to the second one.
Thanks.

**Comment by capricorn86** [comment]
Thank you for reporting @nobkd! :slightly_smiling_face: 

I have changed name of the page. I also noticed that the documentation for `VirtualConsole` should be changed to match other API documentation.
