### ISSUE TITLE
MutationObservers not able to observe() after disconnect()

### ISSUE THREAD

**Issue by dtabuenc** [capricorn86/happy-dom#1524]
**Describe the bug**

I'm not sure why but  this commit https://github.com/capricorn86/happy-dom/commit/9a64097d31c9d542bbd17c37b7e166b301554787 added a new #destroyed field in the MutationObserverClass that is set to true on disconnect and then disallows observe to be called after disconnect:

As per the specification:

The [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) method disconnect() tells the observer to stop watching for mutations.

The observer can be reused by calling its [observe()](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe) method again.

**To Reproduce**
1. Create a new MutationObserver instance
2. call  .observe() method on it with appropriate parameters
3. call .disconnect()  method on instance to stop observing
4. call.observe() again

**Expected behavior**
After disconnecting and observing again the mutation observer callback should continue to be called

**Comment by capricorn86** [comment]
Thank you for reporting @dtabuenc! :slightly_smiling_face: 

I believe that the bug has been fixed now.
