### ISSUE TITLE
Missing SECURITY.md for Reporting Process

### ISSUE THREAD

**Issue by kevin-mizu** [capricorn86/happy-dom#1542]
Hi,

I have discovered a critical vulnerability in the library, but I couldn't find a dedicated place to report the issue securely. I've already sent the full details to "david@ortner.se," but I believe it would be beneficial to have a SECURITY.md file in the repository. This would provide a clear process for reporting security issues and ensure that such information is handled appropriately in the future.

Thank you for considering this!

**Comment by kevin-mizu** [comment]
Hey @capricorn86,

This issue is quite severe, but it can be easily fixed. I would be glad to help you fix it!
You can contact me at kevin.mizu@protonmail.com if you didn't receive my emails.

Cheers,
Kévin

**Comment by capricorn86** [comment]
Thank you for reporting @kevin-mizu! :slightly_smiling_face: 

The [Github Vulnaribilty Reporter](https://github.com/capricorn86/happy-dom/security) tool has now been enabled for the repository and a `SECURITY.md` file has been created.
