### ISSUE TITLE
Performance issue with ClassMethodBinder

### ISSUE THREAD

**Issue by felixgirault** [capricorn86/happy-dom#1550]
**Describe the bug**
This is not a bug per se but more of a performance issue.
It seems that ClassMethodBinder is taking up most of the execution time when parsing HTML.

**To Reproduce**
Load an HTML document as suggested in the docs:
```js
const window = new Window();
const document = window.document;
document.body.innerHTML = '<div>Some big HTML page</div>';
```
Inspect the execution via `node --inspect`.

**Expected behavior**
The parsing should be as fast as possible.

**Screenshots**
Here is the flame chart for a call to `parse()`:
![happy-dom](https://github.com/user-attachments/assets/fc0b8524-f62b-42a0-ba5a-1a6e4711c382)

And here are the execution times of each call within `parse()`:
![happy-dom-2](https://github.com/user-attachments/assets/bb3e511c-e546-444a-9794-33d3e06e8bd0)

I haven't been able to drill down further than `bindMethods`, I don't know why the profiler stops there :thinking: 

**Device:**
 - NodeJS
 - Latest version (15.7.4)

**Additional context**
I'm not familiar enough with the code base, but it feels to me that ClassMethodBinder could be optimized for production usage.
The `forwardToPrototype` option seems to be targeted at test tools, but is still evaluated outside of them. 
Could this be a lead?

**Comment by capricorn86** [comment]
Thank you for reporting @felixgirault! :slightly_smiling_face: 

This has now been fixed. The profiling screenshots where helpful as I managed to identify the biggest culprit. I have changed the logic now to only bind methods for proxies whenever a method is used (the first time).

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v15.8.0

**Comment by felixgirault** [comment]
Great news! Thank you for your work 👍
