### ISSUE TITLE
getElementsByClassName returns wrong results when given multiple classes

### ISSUE THREAD

**Issue by hombrew** [capricorn86/happy-dom#1551]
**To Reproduce**
```javascript
import { Window } from "happy-dom";

const window = new Window();
const document = window.document;

document.body.innerHTML = `
<div class="class1 class2">
  <div class="class2">
    <span>hi</span>
  </div>
</div>`;

const arr1 = Array.from(document.getElementsByClassName("class1 class2"));
console.log(arr1.length); // output: 0 - wrong
```

**Expected behavior**
in this case getElementsByClassName should return 1 element as shown [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName)

**Device:**
 - OS: OSX Sonoma 14.6.1
 - Browser Chrome
 - Version 129.0.6668.58

**Additional context**
based on the same code, comma separated classes work as expected:

```javascript
const arr2 = Array.from(document.getElementsByClassName("class1, class2"));
console.log(arr2.length); // output: 1 - ok
```

**Comment by capricorn86** [comment]
Thank you for reporting @hombrew! :slightly_smiling_face: 

Big thanks to @kylehalleman for contributing with a fix :star: 

The fix has been released in v16.1.0.
