### ISSUE TITLE
Add an option to disable cross origin policy

### ISSUE THREAD

**Issue by OlaviSau** [capricorn86/happy-dom#1553]
**Is your feature request related to a problem? Please describe.**
We use multiple domains in our project and the API for server context assumes no CORS. Currently we are using patch-package to fix this, but I think disabling CORS would be a common use case for happy DOM.

**Describe the solution you'd like**
I want to be able to disable CORS for Fetch / SyncFetch.

**Describe alternatives you've considered**
We can either rearchitect our API, use patch-package or fork this project, none are ideal.

**Additional context**
I have a example PR.

**Comment by OlaviSau** [comment]
https://github.com/capricorn86/happy-dom/pull/1554

**Comment by capricorn86** [comment]
Thank you again @OlaviSau for your contribution! :star: 

The fix is now in.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v15.10.0
