### ISSUE TITLE
Migrating to happy-dom raises some issue

### ISSUE THREAD

**Issue by eduardhasanaj** [capricorn86/happy-dom#1558]
I am trying to use happy-dom in an existing test suite with 1000 but I get following error for some of the tests:
 1. DOMException: Failed to execute 'matches' on 'HTMLButtonElement': 'button:not' is not a valid selector.
2. TypeError: Cannot set properties of null (setting 'onclick')
3. ReferenceError: $ is not defined: the code run in browser without errors as I checked console.

I don't understand some of the issues like $ Reference Error but first issue is caused by following query selector
```
el.querySelectorAll("button:not([type]")
```

**Comment by capricorn86** [comment]
Thank you for reporting @eduardhasanaj! :slightly_smiling_face: 

I believe this has been fixed now in the latest release.
