### ISSUE TITLE
Cookie value cuts at `=` sign

### ISSUE THREAD

**Issue by rijenkii** [capricorn86/happy-dom#1570]
**Describe the bug**
Cookie values can contain `=` symbols. Browsers allow them, happy-dom only saves the part before the first `=`.

**To Reproduce**
```
rijenkii@rijenkiipc /t/hd
> npm install happy-dom

added 4 packages in 1s

1 package is looking for funding
  run `npm fund` for details
rijenkii@rijenkiipc /t/hd
> node
Welcome to Node.js v20.18.0.
Type ".help" for more information.
> const document = new (require("happy-dom")).Window().document;
undefined
> document.cookie = "hello=beautiful=world"
'hello=beautiful=world'
> document.cookie
'hello=beautiful'
```

**Expected behavior**
Expected the whole cookie to be saved.

**Additional context**
https://github.com/capricorn86/happy-dom/blob/afd256b2e4f0260adb22432c1a354f558cda6623/packages/happy-dom/src/cookie/urilities/CookieStringUtility.ts#L18

**Comment by capricorn86** [comment]
Thank you for reporting @rijenkii! :slightly_smiling_face: 

Thanks to @btea we now have a fix :star: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v15.10.7
