### ISSUE TITLE
Setting an `<input>` value to `null` is wrong

### ISSUE THREAD

**Issue by raystubbs** [capricorn86/happy-dom#1576]
**Describe the bug**
Setting `x.value = null`, where `x` is an `HTMLInputElement`, results in a `value` with the string `"null"` instead of an empty string.  All browsers I've tested (at least Chrome and Firefox) reset the `value` to an empty string when set to `null`.

**To Reproduce**
```javascript
const x = document.createElement("input");
x.value = null;
// inspect x.value in the console, its value is "null"
```

**Expected behavior**
`x.value` should have an empty string instead of `"null"`.

**Additional context**
happy-dom v15.8.0

**Comment by capricorn86** [comment]
Thank you for reporting @raystubbs! :slightly_smiling_face: 

I believe it should be fixed now.

**Comment by raystubbs** [comment]
Awesome, thanks 🙏 and thanks for the awesome work on this lib.
