### ISSUE TITLE
events on window/document/body not cleared between test runs

### ISSUE THREAD

**Issue by jesperronn** [capricorn86/happy-dom#1591]
reproduction repository: 

https://github.com/jesperronn/vitest-new-test-context/tree/v1.0.0

**Describe the bug**
I want to test some legacy (jquery) code and ensure that testing  works as expected

However, test that registers an eventListener on `body` element are not properly reset between tests.

**To Reproduce**
checkout the repository

```
git checkout git@github.com:jesperronn/vitest-new-test-context.git
git switch v1.0.0
npm install
npm test
```

The code under test will register a click event for body (remember, that's how it was done with jQuery back in the days)

```
  $('body').on("click", ".js-icon", function(e) {
      updateHiddenField($(this));
    })
```

The actual code reads a value from the clicked `.js-icon` and then adds that value to a hidden field:

```
      passw.value = (`${existingValue}${newAppendedValue}`);
```

In my test I created several tests in the same test file (some of them empty). This shows something odd. 

First test run, body.onclick event registers, I correctly click icon-A, which appends one `A` into passw field.

Next test run, body.onclick event registers, the previous click registration is still there. So I click `A`, but two `AA` is written into the field.

**Expected behavior**
Of course I expect each test to run in isolation, so that all events must be deregistered.

**Test output**
In the example project I console log the values written to `passw` field, As you can see, the later in the test runs the more AAAA and AAAABB are written:

```
npm test

stdout | src/bodylistener.test.js > bodylistener > body listener > test click iconB, iconA
### testrunIteration: 1
### before passwVal: '' ### value + new:  + B => B
B
### testrunIteration: 2
### before passwVal: 'B' ### value + new: B + A => BA
BA

stdout | src/bodylistener.test.js > bodylistener > body listener > test click iconA
### testrunIteration: 1
### before passwVal: '' ### value + new:  + A => A
A
### testrunIteration: 2
### before passwVal: 'A' ### value + new: A + A => AA
AA
### testrunIteration: 3
### before passwVal: 'AA' ### value + new: AA + A => AAA
AAA

stdout | src/bodylistener.test.js > bodylistener > body listener > test click iconA, iconB
### testrunIteration: 1
### before passwVal: '' ### value + new:  + A => A
A
### testrunIteration: 2
### before passwVal: 'A' ### value + new: A + A => AA
AA
### testrunIteration: 3
### before passwVal: 'AA' ### value + new: AA + A => AAA
AAA
### testrunIteration: 4
### before passwVal: 'AAA' ### value + new: AAA + A => AAAA
AAAA
### testrunIteration: 5
### before passwVal: 'AAAA' ### value + new: AAAA + B => AAAAB
AAAAB
### testrunIteration: 6
### before passwVal: 'AAAAB' ### value + new: AAAAB + B => AAAABB
AAAABB
### testrunIteration: 7
### before passwVal: 'AAAABB' ### value + new: AAAABB + B => AAAABBB
AAAABBB
### testrunIteration: 8
### before passwVal: 'AAAABBB' ### value + new: AAAABBB + B => AAAABBBB
AAAABBBB

```

**Device:**

```
npx vitest --version
vitest/2.1.4 darwin-arm64 node-v23.1.0
```

**Questions**
This case is probably not the standard use intended for happy-dom? I am dealing with legacy JQuery code and i NEED to write tests before I am allowed to change the code to vanilla JS. I might be missing something obvious, so please point me in directions that may be useful.

Also, feel free to play around with the example I provided https://github.com/jesperronn/vitest-new-test-context/blob/v1.0.0/

* Am I missing out a way to clear the window/document event registration?
* Can you see a workaround that makes the tests pass?
* Is it a bug in Happy-dom?
* Is there a better (i mean easier) way to write these tests? (I am not locked to happy-dom if there is an easier way)

**Comment by capricorn86** [comment]
Hi @jesperronn!

This is Vitest related.

I can see that you have set `poolOptions: { threads: 'singleThread' }` in your config.

According to the Vitest documentation, this will disable test isolation:
https://vitest.dev/config/#pooloptions-threads-singlethread
