### ISSUE TITLE
URL in style always adds quotes

### ISSUE THREAD

**Issue by iradonov** [capricorn86/happy-dom#1596]
**Describe the bug**
When the url function is called when setting some element style, the url always ends up wrapped in quotation marks, even though a url without quotes is also valid. Noticed this while migrating from JSDOM (even though the url implementation of happy-dom is based on theirs)

**To Reproduce**

```
const { Window } = require("happy-dom");

const window = new Window();
const document = window.document;
const el = document.createElement('div');
el.style = 'background-image: url(test.jpg)'
console.log(el.style.backgroundImage) // url("test.jpg")
```

See also affected unit tests.

**Expected behavior**
The url shouldn't be always wrapped in quotation marks.

**Comment by capricorn86** [comment]
Hi @iradonov @iradonov! :slightly_smiling_face: 

According to spec, quotation marks should always be added.

If you run the following code in the browser, it will behave the same:
```javascript
var el = document.createElement('div');
el.style = 'background-image: url(test.jpg)'
console.log(el.style.backgroundImage)
```

**Comment by iradonov** [comment]
Oh, it never occurred to me that JSDOM didn't comply with the spec, should've checked first. Thanks @capricorn86, will close both the issue and PR.

**Comment by capricorn86** [comment]
> Oh, it never occurred to me that JSDOM didn't comply with the spec, should've checked first. Thanks @capricorn86, will close both the issue and PR.

No problem! :slightly_smiling_face: 

It is only the URL value parser part that is based on JSDOM, the rest of the implementation is Happy DOM. This goes for more or less all logic related to CSSStyleDeclaration.
