### ISSUE TITLE
Change event fired too often on select element

### ISSUE THREAD

**Issue by fbecker-fds** [capricorn86/happy-dom#1603]
**Describe the bug**
After upgrading to v15 our tests started to fail because the change event on a select was fired way too often (twice as often in this reproducer).

**To Reproduce**
1. Go to https://stackblitz.com/edit/vitest-dev-vitest-hfkusq?file=test%2Fbasic.test.ts
2. Run `npm install && npm run test` (uses v14)
3. Tests work
4. Upgrade happy-dom to v15 in package.json
5. Run `npm install && npm run test`
6. Tests fail

**Comment by capricorn86** [comment]
Thank you for reporting @fbecker-fds! :slightly_smiling_face: 

A fix has been released.
