### ISSUE TITLE
[file] strict validation not compatible with `react-dropzone`

### ISSUE THREAD

**Issue by csantos-nydig** [capricorn86/happy-dom#1604]
I'm mostly curious why this validation exists:

https://github.com/capricorn86/happy-dom/blob/e6f91276d7b4549d17f5d67bd2f909723f4940b3/packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts#L795-L802

And if it can be removed or updated?

### Context

I'm using `react-dropzone` and they have this line https://github.com/react-dropzone/react-dropzone/blob/c36ab5bd8b8fd74e2074290d80e3ecb93d26b014/src/index.js#L807-L808
which triggers and error in `vitest` + `happy-dom`

### Plain JS example

https://codesandbox.io/p/sandbox/silly-kowalevski-qjrmt6

```
const fileInput = document.getElementById("my-file");
fileInput.value = null;
```
doesn't throw errors in any browser

_Originally posted by @csantos-nydig in https://github.com/capricorn86/happy-dom/discussions/1495_

**Comment by capricorn86** [comment]
Thank you for reporting @csantos-nydig! :slightly_smiling_face: 

I believe it should be fixed now.
