### ISSUE TITLE
DOMParser does not recognise BODY and thus creates it twice

### ISSUE THREAD

**Issue by OlaviSau** [capricorn86/happy-dom#1615]
**Describe the bug**
DOMParser is not compliant with the browser implementation. This breaks frameworks like Angular from setting the innerHTML as an attribute, breaking most renders using Angular.
This occurs because BODY is not recognised and this causes body to be created as an extra element in HappyDOM.

**To Reproduce**
`(new window.DOMParser()).parseFromString("<body><x></x>Example Text", "text/html").body.innerHTML`
HappyDOM: `<body><x></x>Example Text</body>`
**Expected behavior**
Chrome: `<x></x>Example Text`

**Additional context**
tagName BODY should not be created as a standard node.
https://github.com/capricorn86/happy-dom/blob/afd256b2e4f0260adb22432c1a354f558cda6623/packages/happy-dom/src/dom-parser/DOMParser.ts#L79
https://github.com/capricorn86/happy-dom/blob/afd256b2e4f0260adb22432c1a354f558cda6623/packages/happy-dom/src/dom-parser/DOMParser.ts#L87

@capricorn86

**Comment by OlaviSau** [comment]
@capricorn86 I have created a naive fix for this, please take a look and make improvements.
https://github.com/capricorn86/happy-dom/pull/1616

**Comment by aralroca** [comment]
Now I receive this error:

```js

21 |     document.body.innerHTML = '';
                  ^
TypeError: null is not an object (evaluating 'document.body.innerHTML = ""')
```

Is that normal? `document.body.innerHTML = ""` is allowed in browsers

**Comment by capricorn86** [comment]
> Now I receive this error:
> 
> ```js
> 21 |     document.body.innerHTML = '';
>                   ^
> TypeError: null is not an object (evaluating 'document.body.innerHTML = ""')
> ```
> 
> Is that normal? `document.body.innerHTML = ""` is allowed in browsers

"body" should only become null if you have removed the body element. When using `document.write()` or `DOMParser` it should always be populated with an `HTMLBodyElement`.

How did you end up with "body" becoming null?

**Comment by aralroca** [comment]
@capricorn86 I'm using in this case on `afterEach`:

https://github.com/brisa-build/brisa/blob/66249054e2223b7965c16126ec517ce71d6ea3b8/packages/brisa/src/utils/rpc/resolve-rpc/index.test.ts#L21

But if I comment this line, I got similar error on other lines like this one:

https://github.com/brisa-build/brisa/blob/66249054e2223b7965c16126ec517ce71d6ea3b8/packages/brisa/src/utils/rpc/resolve-rpc/index.test.ts#L197

```sh
197 |         expect(document.body.innerHTML).toBe('<div class="foo">404</div>');
                              ^
TypeError: null is not an object (evaluating 'document.body.innerHTML')
```

To reproduce it, `bun i` and `bun test packages/brisa/src/utils/rpc/resolve-rpc/index.test.ts`. With version 5.11.7 the tests pass correctly, with version 16.3 this error occurs.
