### ISSUE TITLE
different form element onSubmit and forms.namedItem()

### ISSUE THREAD

**Issue by confix** [capricorn86/happy-dom#1628]
**Describe the bug**

We are trying to run react component tests using `vitest` and testing a component that uses the [conform](github.com/edmundhung/conform) library. 

After checking in with the author of the library, we assume `happy-dom` passes a different instance of the form element into the `onSubmit` handler compared to the one resolved via the `forms.namedElement()` API.

Please find the author's comment here: https://github.com/edmundhung/conform/issues/820#issuecomment-2499142078

**To Reproduce**

1. I've created a quick repro over here: https://stackblitz.com/edit/vitejs-vite-tg4emg
2. `npm run test`
3. See the console log `match false` above the test output

**Expected behavior**
The reference of the form element passed to `onSubmit` should resolve to the same instance as when using `forms.namedElement()`.

**Screenshots**

**Device:**
 - Version 15.11.6

**Additional context**

**Comment by capricorn86** [comment]
Thank you for reporting @confix! :slightly_smiling_face: 

The issue should be fixed now in v16.2.8
