### ISSUE TITLE
SVGSVGElement is missing method node.getAttribute

### ISSUE THREAD

**Issue by Atyn** [capricorn86/happy-dom#176]
Running the following code with LitElement
```
html`<svg viewport="0 0 1 1"></svg>`
```
 Results in the following error:
```
 TypeError: Cannot read property 'split' of null

      40 |                         var attributeValue = node.getAttribute(attributeLookupName);
      41 |                         node.removeAttribute(attributeLookupName);
    > 42 |                         var statics = attributeValue.split(exports.markerRegex);
         |                                                      ^
      43 |                         this.parts.push({ type: 'attribute', index: index, name: name_1, strings: statics });
      44 |                         partIndex += statics.length - 1;
```

SVGElement should extend Element but extends HTMLElement. Is that why?

Link to inheritence chain for SVGSVGElement: https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement

**Comment by capricorn86** [comment]
Thank you for reporting @Atyn!

I will look into it as soon as possible :slightly_smiling_face:

**Comment by capricorn86** [comment]
@Atyn SVGSVGElement.getAttribute() most certainly exists. It seems like the code is trying to get an attribute that has not been set on the element, which makes getAttribute() return null. Can you try to set a breakpoint and see what attribute it tries to get?

Regarding the inheritance chain. I am well aware of it and it has been fixed in the branch I am currently working on :slightly_smiling_face:

**Comment by Atyn** [comment]
That is great to hear! Lets wait for your fix to arrive then 🙂

**Comment by capricorn86** [comment]
@Atyn I have tested to use "<svg viewport="0 0 1 1"></svg>" with lit-html and lit-element and it works fine for me.

What versions of the libraries are you using? Are you using the latest version of Happy DOM? :slightly_smiling_face:

**Comment by Atyn** [comment]
I am using "@happy-dom/jest-environment": "^1.18.2", so that may be explain it. I will upgrade and this will hopefully fix itself. Thanks for your help 🙂👍

**Comment by capricorn86** [comment]
@Atyn I will close this as there hasn't been any activity on it for a long time. Please re-open if this still is a problem :slightly_smiling_face:

**Comment by Atyn** [comment]
@capricorn86 That sounds good! It was fixed when upgrading so it is no longer a problem 👍. Thanks! 🙂
