### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#189]
# problem

i installed happy-dom, my app, and at import of happy-dom:

```
Error: Cannot find module 'whatwg-encoding'
Require stack:
- /Users/cdaringe/src/factorio-ts/packages/json-schema-producer/node_modules/happy-dom/lib/file/FileReader.js
- /Users/cdaringe/src/factorio-ts/packages/json-schema-producer/node_modules/happy-dom/lib/window/Window.js
- /Users/cdaringe/src/factorio-ts/packages/json-schema-producer/node_modules/happy-dom/lib/index.js
```

indeed, `whatwg-encoding` is not listed as a dep of happy-dom directly

**Comment by capricorn86** [comment]
Thanks for reporting @cdaringe! :slightly_smiling_face: 

It has been fixed now. I am still not sure why the test didn't fail, but I will look into that in another task.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.1.4

**Comment by cdaringe** [comment]
amazing, thanks!
