### ISSUE TITLE
document.querySelector misbehaving on attr filter

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#191]
# Problem

- capture https://lua-api.factorio.com/latest/ as a html string
- load it into happy-dom
- compare `document.querySelector('[id=Classes]')` vs `document.getElementById('Classes')`

In the above, querySelector returns the root document node (incorrect), while getElementById returns the id=Classes element (correct)

**Comment by capricorn86** [comment]
Thanks for reporting @cdaringe! :slightly_smiling_face: 

It seems like query selectors for attribute values without using quotes did not work (e.g. [id="Classes"] worked). I have fixed it and added a unit test for it now.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.1.5

**Comment by cdaringe** [comment]
Thanks @capricorn86! Even with the small little issues (expected during the infancy of a lib), i've really been enjoying happy-dom! Great work

**Comment by capricorn86** [comment]
Thank you @cdaringe! Really nice to hear :slightly_smiling_face:
