### ISSUE TITLE
textContent handles whitespace differently than browser implementations

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#195]
# Problem

`el.textContent` appears to use HTML driven whitespace, vs node-wise space.

Consider the following:

```html
<li>
  <span class="param-name">type</span> ::
  <span class="param-type"
    ><a href="defines.html#defines.controllers"
      >defines.controllers</a
    ></span
  >: Which controller to use
</li>
```

In happy-dom:

```js
el.textContent
"
              type ::
              defines.controllers: Which controller to use
            "
el.innerHTML
"
              <span class="param-name">type</span> ::
              <span class="param-type"><a href="defines.html#defines.controllers">defines.controllers</a></span>: Which controller to use
            "
```

Grabbing that same element from the original webpage:

```js
el.textContent
"type :: defines.controllers:  Which controller to use"
```

I _believe_ that textContent should be agnostic to the formatting of the input HTML, thus I believe the happy-dom impl to _likely?_ not be considering textContent whitespace appropriately

**Comment by capricorn86** [comment]
Thanks for reporting @cdaringe! :slightly_smiling_face: 

I can unfortunately not reproduce the problem. I have tested in Chrome and Firefox and they seem to behave the same way as Happy DOM.

It would be convenient if it would be agnostic to the formatting of the HTML. I sometimes have to strip white-space using a Regexp in unit tests when I compare because of this behavior.

Do you have some more information on the root cause of the issue? :slightly_smiling_face: 

**In Chrome**

Code
```javascript
var div = document.createElement('div');

div.innerHTML = `<li>
       <span class="param-name">type</span> ::
       <span class="param-type"
       ><a href="defines.html#defines.controllers"
           >defines      controllers</a
       ></span
       >: Which controller to use
</li>`;

console.log(div.children[0].textContent);
console.log(div.children[0].innerHTML);
```

Console outputs
```javascript
"
       type ::
       defines      controllers: Which controller to use
"
```
```javascript
"
       <span class="param-name">type</span> ::
       <span class="param-type"><a href="defines.html#defines.controllers">defines      controllers</a></span>: Which controller to use
"
```

**Comment by cdaringe** [comment]
Hmmm. Shucks--I missed this. Thanks for putting some effort in, and apologies that my repro was insufficient. I will re-open this I observe it again in the wild. Thx again

**Comment by capricorn86** [comment]
No problem, happy to help! :slightly_smiling_face:
