### ISSUE TITLE
Missing Node.parentElement

### ISSUE THREAD

**Issue by Atyn** [capricorn86/happy-dom#196]
I guess we could add a alias to **parentNode** using a getter?

Interface for Node
https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/nodes/node/Node.ts

Documentation at MDN
https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement

**Comment by capricorn86** [comment]
Thanks for reporting @Atyn! :slightly_smiling_face: 

Support for Node.parentElement has now been added.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.3.0

**Comment by Atyn** [comment]
What a quick fix and fast response! Thank you! 🙂🙏
