### ISSUE TITLE
Missing API - document.documentElement.style.getPropertyValue

### ISSUE THREAD

**Issue by jrparish** [capricorn86/happy-dom#197]
This is a very intriguing project! I stumbled across it while looking into some solutions for testing web components. 

One of the main failures we see when turning on happy-dom across the board is related to a missing/incomplete `document.documentElement.style.getPropertyValue` function. 

We're invoking by proxy of utilizing Chakra-UI - https://github.com/chakra-ui/chakra-ui/blob/main/packages/color-mode/src/color-mode.utils.ts#L77

![image](https://user-images.githubusercontent.com/5173987/106489023-ede59a80-6479-11eb-9c87-91efcf81c9d6.png)

**Comment by capricorn86** [comment]
Thanks for reporting @jrparish! :slightly_smiling_face: 

I have now added support for CSSStyleDeclaration.getPropertyValue().

Nice to hear that you want to migrate over to Happy DOM. Let me know if you encounter any more problems while migrating. I will do my best to resolve them as fast as I can.

Read more about the release here:
[https://github.com/capricorn86/happy-dom/releases/tag/v2.2.0](https://github.com/capricorn86/happy-dom/releases/tag/v2.2.0)
