### ISSUE TITLE
Missing Node.textContent

### ISSUE THREAD

**Issue by Atyn** [capricorn86/happy-dom#200]
Why do you want to use Node.textContent?
shadowRoot does not have **.innerText** property textContent. textContent can be helpful to use when unit testing

Documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by capricorn86** [comment]
Thanks for reporting @Atyn! :slightly_smiling_face: 

I have now added support for DocumentFragment.textContent. This will also add support for ShadowRoot.textContent as ShadowRoot extends from DocumentFragment.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.5.0
