### ISSUE TITLE
No way to get src property of an img element via document.querySelector

### ISSUE THREAD

**Issue by JulianLang** [capricorn86/happy-dom#201]
Hi, maybe I am mistaken, but I did not find a way to retrieve the `src` property of an `img`. I don't think there is even an interface in happy-dom for `img` elements?

I tried to get my img src via:

```
document.querySelector('img').src
```

Do I miss something?

**Comment by capricorn86** [comment]
Thanks for reporting @JulianLang! :slightly_smiling_face: 

You are right. Happy DOM did not have support for HTMLImageElement, so it did not have support for this property. I have now added support for it.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.4.0

**Comment by JulianLang** [comment]
@capricorn86 Oh great! Will try it soon, thanks! :)

**Comment by JulianLang** [comment]
Hi, I just installed happy-dom@2.6.0 and vscode auto-imported the HTMLImageElement like this: `import HTMLImageElement from 'happy-dom/lib/nodes/html-image-element/HTMLImageElement';` - is this correct? Importing it using simply `... from 'happy-dom'`seems not to work. Just wanted to check, if I am doing everything right

**Comment by capricorn86** [comment]
It seems like I forgot to export HTMLImageElement and IHTMLImageElement to the main script (index.ts). I have fixed it now :slightly_smiling_face: 

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.6.1
