### ISSUE TITLE
Queryselector in Lit example breaks when changing span to h1

### ISSUE THREAD

**Issue by herrKlein** [capricorn86/happy-dom#202]
Seems queryselector on h1/h2 etc.. elements breaks.
Found out when using happy-dom as a jsdom replacement in jest test.

https://raw.githubusercontent.com/capricorn86/happy-dom/master/packages/jest-environment/test/lit-element/LitElement.test.ts

Change this line in the LitElement.test.ts to query the h1 element
```
expect(shadowRoot.querySelector('h1').innerText).toBe(PROP1);
```

make the span an h1 element
```diff
public render(): TemplateResult {
		return html`
-			Some text <span>${this.prop1}</span>!
+			Some text <h1>${this.prop1}</h1>!
		`;
	}
```

this error occurs:
```
LitElementComponent › Tests integration.

    TypeError: Cannot read property 'innerText' of null
```

**Comment by capricorn86** [comment]
Thanks @herrKlein for reporting! :slightly_smiling_face: 

Turns out there was an error in the RegExp for query selectors. I have now released a fix for it.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.4.1
