### ISSUE TITLE
TypeError: Cannot set property 'cssText' of null

### ISSUE THREAD

**Issue by steel** [capricorn86/happy-dom#207]
Importing jQuery in my jest tests fails with this error.

```
at HTMLElement.cloneNode (node_modules/happy-dom/lib/nodes/html-element/HTMLElement.js:287:34)
      at node_modules/jquery/dist/jquery.js:5633:9
      at node_modules/jquery/dist/jquery.js:5680:5
      at node_modules/jquery/dist/jquery.js:27:40
      at Object.<anonymous> (node_modules/jquery/dist/jquery.js:38:3)
      at Object.<anonymous> (lib/globals/libs.js:6:34)
```

**Comment by capricorn86** [comment]
Thanks for reporting @steel! :slightly_smiling_face: 

I believe that I have found the problems and resolved them. Can you please test with the latest release?

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.5.1

**Comment by capricorn86** [comment]
I will close the issue for now. Please re-open if you still find problems using jQuery in Happy DOM.
