### ISSUE TITLE
.item() on Nodelist does not exists

### ISSUE THREAD

**Issue by herrKlein** [capricorn86/happy-dom#208]
When using queryselectorAll on the shadowroot of an element I got this error:

```
Error: shadowRoot.querySelectorAll(...).item is not a function
```

Reproduce by replacing this line in `LitElement.test.ts
``` diff
- expect(shadowRoot.querySelector('span').innerText).toBe(PROP1);
+ expect(shadowRoot.querySelectorAll('span').item(0).innerText).toBe(PROP1); 
```

**Comment by herrKlein** [comment]
When using queryselectorAll on the shadowroot of an element I got this error:

```
Error: shadowRoot.querySelectorAll(...).item is not a function
```

Reproduce by replacing this line in `LitElement.test.ts
``` diff
- expect(shadowRoot.querySelector('span').innerText).toBe(PROP1);
+ expect(shadowRoot.querySelectorAll('span').item(0).innerText).toBe(PROP1); 
```

**Comment by capricorn86** [comment]
Thanks for reporting @herrKlein! :slightly_smiling_face: 

I have now added support for HTMLCollection and NodeList.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.6.0
