### ISSUE TITLE
Goto url and wait until page fully rendered

### ISSUE THREAD

**Issue by JulianLang** [capricorn86/happy-dom#212]
Hi, me again :)

I'm currently trying to visit a webpage and wait for the page being rendered (including javascripts run) to find a specific image. I've seen this example in the docs (https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom), so I tried to go a similar way:

```ts
function visitUrl(url: string): Promise<AsyncWindow> {
  // ...
  const window = new AsyncWindow();
  window.location.href = url;
  window.happyDOM.whenAsyncComplete().then(() => {
    console.log('innerHTML', window.document.body.innerHTML);
    resolve(window);
  });
}

// resolves directly with empty innerHTML:
const window = await visitUrl('https://page-to-visit.com');
const img = window.document.querySelector('img');
```

The console log only shows `innerHTML `, so I assume there's either something wrong with my code, or there might be a bug with happy-dom. Do you know what's the issue here? Is there maybe any "load"-event I can listen to?

- Maybe it could also be useful to have this use case in the docs :)

Thanks in advance, keep up the great work!

**Comment by capricorn86** [comment]
Hi @JulianLang! :slightly_smiling_face: 

Happy DOM does not load a page when changing location.href. This is intentional as it could potentially be a security risk and many of the consumers does not have this use case.

If you want to parse a page, you will have to fetch it before and put the HTML into Happy DOM.

Please note that there is a security risk executing unknown scripts on the server as the scripts may be able to access the server even though the scripts are executed scoped within a VM context in the example.

```javascript
import { fetch } from 'node-fetch';
import { AsyncWindow } from 'happy-dom';
import VM from 'vm';

function async visitUrl(url: string): Promise<AsyncWindow> {
    const response = await fetch({ url });
    const html = await response.text();
    const window = VM.createContext(new AsyncWindow(), {
           codeGeneration: {
                // Set to false to disable script execution
                strings: true,
                // Set to false to disable WebAssemply compilation
                wasm: true
           }
    });
    const document = window.document;
    
    document.write(html);
    
    await window.happyDOM.whenAsyncComplete();
    
    return window;
}

const window = await visitUrl('https://page-to-visit.com');
const img = window.document.querySelector('img');

console.log(img.src);
```

**Comment by JulianLang** [comment]
Ah I see. Thank you so much for helping, will close this issue then. Keep up the great work! :)

**Comment by capricorn86** [comment]
Thank you @JulianLang! :slightly_smiling_face:

**Comment by capricorn86** [comment]
Hi again @JulianLang! :slightly_smiling_face: 

I read a bit more about VM context, and according to Node, code executed within a context does not have access to the local scope, and therefore it should be quite safe to run scripts within the context.

Link to Node VM context:
https://nodejs.org/api/vm.html#vm_vm_runincontext_code_contextifiedobject_options

If you want to execute scripts, this example is probably better:

```javascript
import { fetch } from 'node-fetch';
import { AsyncWindow } from 'happy-dom';
import VM from 'vm';

function async visitUrl(url: string): Promise<AsyncWindow> {
    const response = await fetch({ url });
    const html = await response.text();
    const window = VM.createContext(new AsyncWindow());
    
    window.location.href = url;
    
    VM.runInContext('document.write(`' + html + '`);', context);
    
    await window.happyDOM.whenAsyncComplete();
    
    return window;
}

const window = await visitUrl('https://page-to-visit.com');
const img = window.document.querySelector('img');

console.log(img.src);
```

**Comment by capricorn86** [comment]
@JulianLang please ignore my last example and use my first example. The problem with loading scripts in the correct context has been fixed in #211 :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.6.2

**Comment by capricorn86** [comment]
Support for loading scripts using "src" will be added in #217.

**Comment by JulianLang** [comment]
Thanks a lot for helping, will try it the next days :)
