### ISSUE TITLE
Node.isConnected connects children before calling connectedCallback

### ISSUE THREAD

**Issue by seanstrom** [capricorn86/happy-dom#230]
## Question about behavior
I'm noticing that custom element `childNodes` are **connected** before their parent node, or a custom element is not connected until its children are connected. Is this intentional?

**Connected** meaning the `connectedCallback` has been called.

### Where does this happen?
When a `Node` is set to `node.isConnected = true` it connects the child nodes before calling `connectedCallback` for itself. This creates a behavior where the children elements have their `connectedCallback` called always before their parent.

### Why is this an issue?
It seems that some web browsers behave differently, at least tested on Chrome, where the execution order is **parent then child**. It may be important that lifecycle callbacks are consistent.

Is there a spec that requires a certain behavior?

### Here's what I've found so far
I've debugged a little and arrived to this piece of code here:
https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/nodes/node/Node.ts#L62

Can we move the for-loop below the `node.connectedCallback` call?

## How to reproduce

Here are two examples of both **happydom** and a **browser**. Each of the examples log to console when each `connectedCallback` is called for a custom element.
I added constructor logs for more context.

### Browser
Here's a **browser** demo that shows `connectedCallback` calls:
https://codesandbox.io/s/custom-elements-connect-order-eew3r

The log outputs for the browser are:
```
created Counter
connected Counter
created Button
connected Button
```

### HappyDom
Here's a **node** demo that shows how **happydom** calls `connectedCallback`:
https://replit.com/@seanstrom/happydom-connected-callbacks-order

and the outputs for **happydom** are:
```
created Counter
created Button
connected Button
connected Counter
```

**Comment by capricorn86** [comment]
Thank you for reporting @seanstrom! :slightly_smiling_face: 

Very well written description of the issue :+1: 

I have changed when connectedCallback() and disconnectedCallback() are called to be the same order as in Chrome. I have also added a test for it.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.11.1
