### ISSUE TITLE
Calling HTMLInputElement.form causing infinite loop

### ISSUE THREAD

**Issue by dkocsis-emarsys** [capricorn86/happy-dom#231]
Hi!

This sample code causing an infinite loop:

```javascript
const input = document.createElement('input');
document.body.appendChild(input);
input.form; //this
```

https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts#L726
I think this line should be `parent = <IHTMLElement>parent.parentNode`.

Have a nice day,
David

**Comment by capricorn86** [comment]
@dkocsis-emarsys that is a pretty serious bug! Good that you found it :sweat_smile: 

I have fixed the bug now. It seems like there was no test for it, so I have added that as well.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.10.1
