### ISSUE TITLE
Element.setAttributeNodeNS() is missing

### ISSUE THREAD

**Issue by dkocsis-emarsys** [capricorn86/happy-dom#232]
Hi again!

I've also find a missing implementation of Element.setAttributeNodeNS, but I think it's currently just an alias for Element.setAttributeNode.

**Comment by capricorn86** [comment]
Thank you for reporting! :slightly_smiling_face: 

I have added support for Element.setAttributeNodeNS(), Element.removeAttributeNodeNS() and Element.getAttributeNodeNS() now.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.11.0
