### ISSUE TITLE
Add support for Local and Session Storage

### ISSUE THREAD

**Issue by Aerophite** [capricorn86/happy-dom#239]
#### Versions (at time of request)
- @happy-dom/jest-environment: 2.11.2
- happy-dom: 2.11.2

#### Feature request

I'd like to be able to use local and session storage like you can when using jsdom (or at least when using jest's jsdom environment) without me having to create my own mock of it.

**Comment by capricorn86** [comment]
Thanks for reporting @Aerophite! :slightly_smiling_face: 

I have now added support for window.localStorage and window.sessionStorage.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.12.0
