### ISSUE TITLE
document.styleSheets is undefined

### ISSUE THREAD

**Issue by Leprosy** [capricorn86/happy-dom#242]
Is there a way to compute the `document.styleSheets` attribute once the `window` element is created and some HTML is added to it?

**Comment by capricorn86** [comment]
Thanks for reporting @Leprosy! :slightly_smiling_face: 

I will look into this as soon as possible.

**Comment by Leprosy** [comment]
Cool! Beside this, this looks like a really great package!

**Comment by capricorn86** [comment]
@Leprosy we now have support for HTMLLinkElement, HTMLStyleElement and Document.styleSheets :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.14.0

**Comment by Leprosy** [comment]
Awesome....this seems to be working ok for styles defined in the <style> element but for some reason I can't fetch the ones defined as <link>  elements...should I enable something extra in order to fetch the external content?

**Comment by capricorn86** [comment]
@Leprosy they should be fetched, but they are fetched asynchronously according to the spec. Javascript files are fetched synchronously by default, so they work a bit different.

Normally in a browser you would probably use something like the "load" event to detect when all resources in the body has been loaded, but Happy DOM does not have support for it yet.

I have created a task for it: https://github.com/capricorn86/happy-dom/issues/261

Until then you can wait for all asynchronous task to complete by using `await happyDOM.whenAsyncComplete()`.

Another alternative is to listen to the "load" event on all "link" elements by doing a querySelectorAll('link'). If the link element already has a "sheet" the loading is completed.

Also note that "href" has to be specified and "rel" has to be set to "stylesheet" in order for the CSS file to be fetched.

**Comment by Leprosy** [comment]
The thing is that I'm fetching the HTML from an URL, then I'm parsing it using happy-dom, no browser involved in the process.

**Comment by capricorn86** [comment]
@Leprosy the code examples I sent is for server side. However, I am working on adding support for the "load" and "readystatechange" event that you will be able to use instead.

**Comment by Leprosy** [comment]
Hi...if I follow you correctly, then this should be enough?

```
import { Window } from 'happy-dom';
const window = new Window();
const document = window.document;
document.body.innerHTML = "some HTML content here"
await globalAny.window.happyDOM.whenAsyncComplete();
console.log(document.styleSheets)
```

**Comment by capricorn86** [comment]
@Leprosy yes that should be enough.

I am not sure about `globalAny.` though. `window.happyDOM.whenAsyncComplete()` should be enough.

**Comment by Leprosy** [comment]
Oh...I used globalAny because on react-native we don't have a global context. But means the same.

I've used this piece of code, but still, I only got the stylesheets defined as a <style> tag, not the <link> ones...perhaps I'm missing something here?

**Comment by capricorn86** [comment]
Do you have some HTML example? Does the link elements have `href` and `rel` set as attributes correctly?

**Comment by capricorn86** [comment]
I have created several tests for it, but it is possible that I have missed something 😅

**Comment by capricorn86** [comment]
You will also have to set the current URL. Otherwise the requests might fail.

`window.location.href = 'http://localhost:8080'`

I should perhaps output errors for failing requests to the console. I will create an Issue for it.

**Comment by Leprosy** [comment]
I'm clipping this site: https://l3pro.netlify.app/

And yes, I'm setting the location.href too, I forgot to put that in the code above

**Comment by capricorn86** [comment]
I will test with the source code from that site later this evening 👍

**Comment by Leprosy** [comment]
Thanks!

**Comment by capricorn86** [comment]
@Leprosy I managed to find what caused the problem now and I have fixed it in the latest release.

I recommend using a VM context to set Happy DOM as global if you will run scripts. You can also use `@happy-dom/global-registrator` in test environments. I do not recommend using `@happy-dom/global-registrator` in environments where you do not have control over the page HTML. If you plan to execute unknown code I recommend to use a VM context and disable script evaluation in the VM as it is always a risk that the script manages to jump out from the VM somehow.

I have also added support for the window "load" event and the document "readystatechange" event, but as your code seems to execute scripts I recommend using `happyDOM.whenAsyncComplete()` as it will also wait for the script to finish executing (timeouts, fetches etc.).

You can read more about the latest releases here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.17.1

**I used this script for testing:**
```javascript
const { Window } = require('./packages/happy-dom');
const VM = require('vm');

async function getStyles() {
    const window = VM.createContext(new Window());
    const document = window.document;
    
    window.location.href = 'https://l3pro.netlify.app';
    
    document.write(`<!DOCTYPE html>
    <html>
      <head>
        <style>
          h1 { text-decoration: underline; }
        </style>
        <link rel="stylesheet" href="style.css">
      </head>
      <body>
        <h1> This is test </h1>
        <h2></h2>
    
        <p>This has some dynamic generated content</p>
        <p>This should be enought to test</p>
        <img src="celes.jpeg" width="50" height="100" />
        <img src="img/guitar.jpeg" width="50" height="100" />
    
        <script>
          const getQuote = async () => {
            let text = "";
            try {
              const res = await fetch("https://l3pro.netlify.app/.netlify/functions/test");
              text = await res.text();
            } catch(e) {
              text = \`Error fetching: \${e}\`;
            } finally {
              document.getElementsByTagName("h2")[0].innerHTML = text
            }
          }
    
          setTimeout(getQuote, 2000);
        </script>
      </body>
    </html>
    `);

    await window.happyDOM.whenAsyncComplete();

    return document.styleSheets;
}

getStyles().then(styleSheets => {
    let index = 0;
    debugger;
    for(const styleSheet of styleSheets) {
        console.log('Stylesheet #' + index + ':');
        for(const cssRule of styleSheet.cssRules) {
            console.log(cssRule.cssText);
        }
        index++;
    }
}).catch(error => {
    console.error(error);
    process.exit(1);
});
```
