### ISSUE TITLE
`removeChild` method should return removed node

### ISSUE THREAD

**Issue by YevhenKap** [capricorn86/happy-dom#243]
According to [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) `removeChild` method [should not return `void`.](https://github.com/capricorn86/happy-dom/blob/7cfdfa08fd738ac367946bcc37a80e5b1a8c0184/packages/happy-dom/src/nodes/node/INode.ts#L23)

**Comment by capricorn86** [comment]
Thank you for your contribution @YevhenKap! slightly_smiling_face

I have merged the PR now, so I will close this issue.
