### ISSUE TITLE
Add support for `Document.adoptNode` method.

### ISSUE THREAD

**Issue by YevhenKap** [capricorn86/happy-dom#244]

**Comment by capricorn86** [comment]
Thank you for your contribution @YevhenKap! :slightly_smiling_face: 

I have merged the PR now, so I will close this issue.

**Comment by capricorn86** [comment]
@YevhenKap I found the Typescript errors. They have been fixed now.

The reason for the errors was because Document, Element, Template and DocumentFragment did not return the removed Node, but the interface stated that they should.

**Comment by YevhenKap** [comment]
@capricorn86 I got it. Sorry, my mistake :(
