### ISSUE TITLE
unmountComponentAtNode warns about another copy of React

### ISSUE THREAD

**Issue by zanona** [capricorn86/happy-dom#248]
Hello, I am just giving happy-dom a try as it's indeed much faster than jsdom for testing.
One thing I am noticing though, is that whenever trying to unmount a React component through `react-dom`, I get the warning below, whether jsdom doesn't show anything in particular? Any ideas why that is?

Thanks in advance

```jsx
// with hapy-dom
import React from "react";
import { render, unmountComponentAtNode } from "react-dom";
import { Window } from "happy-dom";

const { window, document } = new Window();
global.window = window;
global.document = document;

const Foo = () => <h1>Hello World</h1>;
document.body.innerHTML = "<div></div>";

render(<Foo />, document.body.firstChild);
unmountComponentAtNode(document.body.firstChild);

// emits
// Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.
```

```jsx
// with-jsdom
import React from "react";
import { render, unmountComponentAtNode } from "react-dom";
import "global-jsdom/register"; // on a side note, `happy-dom/register` would be awesome :)

const Foo = () => <h1>Hello World</h1>;
document.body.innerHTML = "<div></div>";

render(<Foo />, document.body.firstChild);
unmountComponentAtNode(document.body.firstChild);

// emits: No Warnings
```

**Comment by capricorn86** [comment]
Thanks for reporting @zanona! :slightly_smiling_face: 

I was not able to reproduce the problem in my Jest test environment. I believe the problem for you was that it is not enough to only register window and document globally. There are a lot more properties that React is depended on.

I have added a new package called [@happy-dom/global-registrator](https://www.npmjs.com/package/@happy-dom/global-registrator) which does the same this as "global-jsdom/register". It should solve the problem for you.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.16.0

**Comment by zanona** [comment]
That's great! Thank you very much for the global-registrator package. It makes the setup process much easier.

**Comment by lianghx-319** [comment]
I got the same warns. Maybe I can create a reproduce repo for this issue.

**Comment by azat-io** [comment]
@capricorn86 I have the same error with [Vitest](https://vitest.dev/). Here is a part of my `vite.config.ts`:

```ts
    test: {
      environment: 'happy-dom',
      global: true,
    },
```

**Comment by capricorn86** [comment]
Hi @zanona! :slightly_smiling_face: 

It seems like I misinterpreted the original issue. I missed the comment about the warning.

The issue should now be fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.25.2
