### ISSUE TITLE
add `element.getRootNode` implementation

### ISSUE THREAD

**Issue by zanona** [capricorn86/happy-dom#249]
Hello,
I believe that `element.getRootNode` _([jsdom version](https://github.com/jsdom/jsdom/blob/5279cfda5fe4d52f04b2eb6a801c98d81f9b55da/lib/jsdom/living/nodes/Node-impl.js#L152-L154))_ might not yet be implemented.
The current use case is with some matchers from `@testing-library/jest-dom` (_i.e: [`.toBeInTheDocument`](https://github.com/testing-library/jest-dom/blob/21ad89bc707b6e41af887d1bd103dd6dbc665dee/src/to-be-in-the-document.js#L8-L11)_), to fail as it relies on this  specific method.

**Comment by capricorn86** [comment]
Thanks for reporting @zanona! :slightly_smiling_face: 

I will add support for it as soon as possible.

**Comment by capricorn86** [comment]
@zanona I have now added support for getRootNode(). Sorry for it to take so long :sweat_smile: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.19.0

**Comment by zanona** [comment]
Thanks so much for taking the time to implement it. I will change my tests to make use of it right away.
