### ISSUE TITLE
querySelectorAll fails when using underscores in the selector

### ISSUE THREAD

**Issue by Leprosy** [capricorn86/happy-dom#250]
Hi, I'm getting this when using the querySelector methods:

```
window.document.querySelectorAll("div[_attribute]")
SelectorItem.js:198 Uncaught Error: The selector "div[_attribute]" is not valid.
```

Perhaps there is something on the regexp used there?

**Comment by capricorn86** [comment]
Thanks for reporting @Leprosy! :slightly_smiling_face: 

The bug was Regexp related as you suspected. I have fixed it now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.16.3
