### ISSUE TITLE
Add Support for Declarative Shadow DOM

### ISSUE THREAD

**Issue by EisenbergEffect** [capricorn86/happy-dom#251]
I noticed that the current server render tests render the shadow dom into the light dom. With the new declarative shadow DOM feature, it would be great if the shadow dom contents were rendered into a template tag with the `shadowroot="open"` attribute.

Would you be interested in taking a community contribution to make this change? My team can dedicate some time to working with you on the implementation.

**Comment by capricorn86** [comment]
@EisenbergEffect I am not sure what rendering to a template tag means in this case. Do you have some reference documentation? :slightly_smiling_face: 

All kinds of contributions are very welcome. I am happy to collaborate on this :slightly_smiling_face:

**Comment by capricorn86** [comment]
Hi @EisenbergEffect! :slightly_smiling_face: 

I have now finally added support for Declarative Shadow DOM.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.47.0
