### ISSUE TITLE
Error caused by Element having observedAttributes getter

### ISSUE THREAD

**Issue by bigfish** [capricorn86/happy-dom#271]
Hi, I found that when attempting to use happy-dom with Stencil generated React components, it complained about not being able to set the observedAttributes property.

```
(node:10615) UnhandledPromiseRejectionWarning: TypeError: Cannot set property observedAttributes of function Element() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _thi...<omitted>... } which has only a getter
```

AFAIK the observedAttributes static getter should be defined by custom elements, so should not already be defined by Element. Stencil is setting the property in its bootstrap script and causes this error. I presume since this works in a browser, it should also work in emulated DOM env. 

Anyways I tried removing the observedAttributes property getter from Element class, and the error went away. Perhaps it is not necessary (since undefined property is just going to return undefined anyways, which is what the default implementation is doing?)

**Comment by capricorn86** [comment]
Thanks for reporting @bigfish! :slightly_smiling_face: 

I have created a fix now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.19.1
