### ISSUE TITLE
Happy-dom are not allowing NPM to flatten dependencies (taking 248 MB disk space)

### ISSUE THREAD

**Issue by Atyn** [capricorn86/happy-dom#276]
npm-shrinkwrap.json are published with all packages of happy-dom. This is has the following effects:
- Preventing NPM from reuse dependencies and causing @happy-dom/jest-environment to require 248 MB disk space.
- Includes all devDependencies (angular, react, vue etc)

Latest version of Lerna is not interpreting .npmignore correctly:
https://github.com/capricorn86/happy-dom/blob/master/packages/jest-environment/.npmignore

Refered issue:
https://github.com/npm/npm-packlist/issues/51

Solutions:
- Lock to an older version of npm-packlist 
- Use "hoist"
- Use package-lock with NPM 7

**Comment by capricorn86** [comment]
Thanks for reporting @Atyn! :slightly_smiling_face: 

The problem should be fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.19.3
