### ISSUE TITLE
TypeError: Cannot read property 'jest-symbol-do-not-touch' of null (Jest 27)

### ISSUE THREAD

**Issue by vsmahesh** [capricorn86/happy-dom#281]
```
TypeError: Cannot read property 'jest-symbol-do-not-touch' of null

      at Object.<anonymous> (node_modules/expect/build/index.js:3:20)
```

I am getting the above error when adding `"testEnvironment": "@happy-dom/jest-environment"` under the jest configuration in package.json

Here are the relevant snippet from package.json
```
"devDependencies": {
    "@happy-dom/jest-environment": "^2.20.1",
    "@types/jest": "^26.0.23",
    "jest": "^27.0.1",
    "jest-esm-transformer": "^1.0.0"
  },
  "jest": {
    "verbose": false,
    "transform": {
      "\\.m?jsx?$": "jest-esm-transformer"
    },
    "testEnvironment": "@happy-dom/jest-environment"
  }
```
I think it is happening only on the latest `jest` version (27).

**Comment by capricorn86** [comment]
Thank you for reporting @vsmahesh! :slightly_smiling_face: 

I have added support for Jest v27.0.0 now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.21.0
