### ISSUE TITLE
 The DOMParser in Happy DOM only supports the mime type "text/html"

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#284]
If possible, I would like it to support 'application/xml'

**Comment by capricorn86** [comment]
Hi @jgonte!
This is the same request as in #282 :slightly_smiling_face: 

I will add it as soon as possible.

**Comment by jgonte** [comment]
Just to let you know I am really impressed with happy-dom

Thanks
Jorge

________________________________

**Comment by jonblatho** [comment]
`image/svg+xml` MIME type support would also be fantastic.

**Comment by capricorn86** [comment]
@jgonte Happy DOM finally has support for parsing XML :slightly_smiling_face: 

@jonblatho `image/svg+xml` should also work

**Comment by onx2** [comment]
Is there a working example of this? I'm not able to get it working in my environment. I'm using `v17.4.4`.


```ts
import { DOMParser } from "happy-dom";

// This code throws and error
const parser = new DOMParser();
const svgDoc = parser.parseFromString(
  '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="red" /></svg>',
  "image/svg+xml"
);
console.log({ svgDoc });
``` 


```bash
TypeError: Cannot read properties of undefined (reading 'DOMException')
    at DOMParser.parseFromString (file:///.../node_modules/happy-dom/lib/dom-parser/DOMParser.js:20:51)
```
