### ISSUE TITLE
Happy DOM jest environment does not support fetch

### ISSUE THREAD

**Issue by randak** [capricorn86/happy-dom#286]
I believe that HappyDOM's removal of fetch is inappropriate for a Jest environment configuration. We use Mock Service Worker (https://mswjs.io/) rather than mocking fetch, and HappyDOM is incompatible with our tests because they use the real `fetch` with a fake API implementation. 

I would propose that these lines should be removed and left to individual users to configure for themselves if this behavior is desired: 
https://github.com/capricorn86/happy-dom/blob/bf804ad8f37dd3581cf0b31595b7085a8ef5f341/packages/jest-environment/src/index.ts#L44-L46

The current setup is also inconsistent with how JSDOM is configured, so it is likely not what users would expect.

**Comment by capricorn86** [comment]
Thanks for reporting @randak! :slightly_smiling_face: 

I have now removed the two suggested lines and `jest-environment `should now support fetch().

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.22.0
