### ISSUE TITLE
Add support for URLSearchParams

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#289]
# problem

When using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) in jest-environment, the following Error is emitted:

```
    ReferenceError: URLSearchParams is not defined
```

Bummer! Looks like this can probably be slapped on directly from the `url` module?

**Comment by capricorn86** [comment]
Thanks for reporting @cdaringe! :slightly_smiling_face: 

Support for URLSearchParams has been added.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.24.0
