### ISSUE TITLE
Chrome returns undefined when called customElements.get(name) on an undefined element

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#290]
Just to bring you attention that customElements.get(name) return undefined in Chrome while it returns null with HappyDom.

**Comment by capricorn86** [comment]
Thanks for reporting @jgonte! :slightly_smiling_face: 

This has been fixed now in the latest release:
https://github.com/capricorn86/happy-dom/releases/tag/v2.22.1
