### ISSUE TITLE
insertBefore should not allow to insert before a child that is not a child of the parent node

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#294]
My code is different but it should be something like it (I am trying to simplify :-)

const node = new DocumentFragment();

const element1 = document.createElement('span');

const element2 = document.createElement('span');

 node.insertBefore(element1 , element2 );

It lets me insert the elements

Instead it shoud throw the following error:

DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by capricorn86** [comment]
Thanks for reporting @jgonte! :slightly_smiling_face: 

This has been fixed now in the latest release.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.24.1
