### ISSUE TITLE
document.createNodeIterator is not a function

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#297]
It seems that the node iterator APIs are not supported by Happy-Dom

**Comment by capricorn86** [comment]
Hi @jgonte! :slightly_smiling_face: 

I will look into adding support for this as soon as possible.

**Comment by jgonte** [comment]
Actually, if you could prioritize
Exception has occurred: TypeError: slot.assignedElements is not a function
IMHO that would be better

Thank you so much
Jorge
________________________________

**Comment by capricorn86** [comment]
We finally have support for the NodeIterator API.

Big thanks to @danielrentz for your contribution! 🌟 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.3.0
