### ISSUE TITLE
Add support for node.normalize()

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#300]
https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize

**Comment by capricorn86** [comment]
Hi @jgonte! :slightly_smiling_face: 

Sorry for taking so long answering. I will look into adding support for Node.normalize() as soon as possible.

**Comment by capricorn86** [comment]
Thanks to @danielrentz we finally have support for `Node.normlize()` :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.6.0
