### ISSUE TITLE
CSSStyleSheet insertRule should return the index of the newly inserted rule

### ISSUE THREAD

**Issue by derekdon** [capricorn86/happy-dom#303]
https://github.com/capricorn86/happy-dom/blob/8e2723cb0a996e0e7f3dbe40e7c1d7d4d74b2fa1/packages/happy-dom/src/css/CSSStyleSheet.ts#L55

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule#return_value

**Comment by capricorn86** [comment]
Thanks for reporting @derekdon! :slightly_smiling_face: 

I have made a fix for it.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.24.4

**Comment by derekdon** [comment]
Wow @capricorn86 quick turnaround! Thank you... happy-dom looks cool, but I had to move to JSDOM in the short term as I hit a number of other issues too...

For your ref:

```
// mocked
window.document['createRange'] = () => ({
    setStart: () => {},
    setEnd: () => {},
    commonAncestorContainer: {
      nodeName: 'BODY',
      ownerDocument: window.document,
    },
  });

// mocked
  window['matchMedia'] = () => ({
    matches: false,
    addListener: () => {},
    removeListener: () => {},
  });

// missing
window.HTMLSlotElement.assignedElements / assignedNodes
```

There might be more... but that's when I stopped I'm afraid.

In JSDOM I had to do the following to get a working dom for my use case, Web Components, MS Fast.

```
  globalThis.window = window;
  globalThis.customElements = window.customElements;
  globalThis.document = window.document;
  globalThis.CSSStyleSheet = window.CSSStyleSheet;
  globalThis.CustomEvent = window.CustomEvent;
  globalThis.Document = window.Document;
  globalThis.HTMLDialogElement = window.HTMLDialogElement;
  globalThis.HTMLElement = window.HTMLElement;
  globalThis.HTMLInputElement = window.HTMLInputElement;
  globalThis.HTMLOptionElement = window.HTMLOptionElement;
  globalThis.HTMLSelectElement = window.HTMLSelectElement;
  globalThis.HTMLStyleElement = window.HTMLStyleElement;
  globalThis.MutationObserver = window.MutationObserver;
  globalThis.Node = window.Node;
  globalThis.Option = window.Option;
  globalThis.ShadowRoot = window.ShadowRoot;
```

**Comment by capricorn86** [comment]
I understand. I will fix what you found as soon as I get some time over :slightly_smiling_face: 

I have created these Issues for your findings:
 - #305: Missing support for Document.createRanger()
 - #306: Missing support for Window.matchMedia
 - #307: https://github.com/capricorn86/happy-dom/issues/307
