### ISSUE TITLE
Missing support for Window.matchMedia

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#306]

**Comment by Ayc0** [comment]
I implemented this in the past: see https://github.com/Ayc0/mock-match-media/

You could so something similar:
- use a custom mock that would use a global setter if someone wants to emulate a change in the media
- expose the setter with `window.happyDOM.setMedia`

**Comment by capricorn86** [comment]
Thanks for reporting @Ayc0! :slightly_smiling_face: 

I have added support for window.matchMedia() and MediaQueryList. However, I have not added support for setting media and matching towards the current resolution and pixel ratio. The released version makes it easier to mock and will resolve errors when running code. Do you want to add a separate task for looking into adding more advanced support?

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.32.0
