### ISSUE TITLE
Missing support for HTMLSlotElement.assignedElements

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#307]

**Comment by jgonte** [comment]
Exception has occurred: TypeError: slot.assignedElements is not a function

**Comment by capricorn86** [comment]
@jgonte sorry that you had to wait for the fix such a long time.

It should be fixed now :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.31.0
