### ISSUE TITLE
Elment.attributes does not implement the NamedNodeMap interface

### ISSUE THREAD

**Issue by sondr** [capricorn86/happy-dom#308]
I was trying to replace JSDOM with Happy DOM and the app was failing to run something akin to:
```
const element = document.createElement('div');
const someAttribute = document.createAttribute('someattribute');
element.attributes.setNamedItem(someAttribute);
```

I see the current implementation is:
```
readonly attributes: { [k: string]: Attr | number };
```

Is there any chance there will be a switch to [NamedNodeMap ](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap)in the future?

**Comment by capricorn86** [comment]
Hi @sondr! :slightly_smiling_face: 

Yes I will add support for this as soon as possible. This will probably come in pretty soon as it is fairly easy to implement support for.

**Comment by urkle** [comment]
This is needed to support vue-test-utils (1.x) as it uses `attributes.length` and `attributes.item(#)`

**Comment by brattonross** [comment]
I ran into an issue related to this when running tests with [axe-core](https://github.com/dequelabs/axe-core). It looks like in their code there are a couple of if statements that do a check along the lines of:

```js
if (attributes instanceof window.NamedNodeMap) {
 // ...
}
```

This results in the error `Right-hand side of 'instanceof' is not an object` being thrown, and the tests failing.

I think this is a little different to the original issue since this is concerning `window` and not an element.

**Comment by Archon-** [comment]
Code such as this in Jest tests:
```
expect(wrapper.find('.button').attributes().disabled).toEqual('disabled')
```
Throw an error: `TypeError: attributes.item is not a function`. Seems like it's the same issue. Is this in active development? Is there anything I could help with?

**Comment by matt-smarsh** [comment]
This issue seems to be the last one preventing a drop-in replacement from `jsdom`. I'm using `vitest` & `@vue/test-utils@1` and I can't switch because of the error `TypeError: attributes.item is not a function` which is thrown from within `@vue/test-utils` and is unavoidable.

**Comment by flip111** [comment]
I switched from jsdom to happy-dom for performance and jsdom [lack of ESM](https://github.com/jsdom/jsdom/issues/2475). I can't get my nodejs program to run cross-platform without this feature.

**Comment by jledentu** [comment]
@capricorn86 Don't know if you've worked on this, otherwise I can help to write a PR.

**Comment by capricorn86** [comment]
Thank you contributing @jledentu! :slightly_smiling_face: 

There is a fix in now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.6.0
