### ISSUE TITLE
Add support for Beacon

### ISSUE THREAD

**Issue by cdaringe** [capricorn86/happy-dom#309]
# Problem

`navigator.sendBeacon()` is a useful API, but is missing

https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API

**Comment by capricorn86** [comment]
Hi @cdaringe! :slightly_smiling_face: 

I will look into adding it.

Are you using fetch() or other resource loading functionality from Happy DOM?

**Comment by cdaringe** [comment]
Hey @capricorn86 , yes, definitely!

I use happy dom in 1.5 projects. The first project is quite simple, and happy dom just worked right off the bat. Every month or two, I try and replug it in to my second project, and see what I get snagged up on. There’s generally one or two little things, and I file tickets with you accordingly :-) my 2nd project evolves regularly, so I put down my happy-dom experiment when I hit snags. That’s why my tickets have been a bit sporadic over the few months—repeat evaluations!

**Comment by capricorn86** [comment]
@cdaringe this has finally been fixed now :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.10.0
