### ISSUE TITLE
Test hangs indefinitely

### ISSUE THREAD

**Issue by wtchnm** [capricorn86/happy-dom#310]
Hey, thanks for doing this! I was able to run some simple tests and the speed was impressive, but unfortunately some complex tests hangs indefinitely.

To reproduce:

1. `npx degit wtchnm/Vitamin#feat/happy-dom happy-dom-test`
2. `cd happy-dom-test`
3. `pnpm i`
4. `pnpm test:ci`

I have no idea what the problem is, but I'll keep looking. Thanks.

**Comment by capricorn86** [comment]
Thank you for reporting @wtchnm! :slightly_smiling_face: 

I have debugged what happened in your code and I found a bug in Happy DOM that was triggered by the test framework you are using. I have now released a fix for the problem.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.24.5
