### ISSUE TITLE
onChange event doesn't seem to work properly

### ISSUE THREAD

**Issue by Marcisbee** [capricorn86/happy-dom#313]
Hey. First of all, great package!
My tests are running TWICE as fast, so great thanks for that 🥳 

I noticed some weird issues when using `@testing-library/user-event` for react.

Here's stackblitz reproduction of the issue: https://stackblitz.com/edit/node-qh31el?file=index.js

This test fails with `happy-dom`
```js
test('changes input value correctly', () => {
  const { container } = render(createElement(TestComponent));

  const input = container.querySelector('input');

  userEvent.type(input, 'Hello world');

  assert.equal(onChange.callCount, 11);
  assert.equal(onChange.calls[10][0].target.value, 'Hello world');
});
```

`onChange.callCount` is `0` instead of `11`. Since user-events library types each character in separate event. But in `happy-dom` there are no events called.

In that stackblitz reproduction I also included what happens when using `jsdom`, the test passes.

**Comment by capricorn86** [comment]
Thanks for reporting @Marcisbee!

I have managed to fix all issues now with why "testing-library" didn't work when using userEvent.type().

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.25.0
