### ISSUE TITLE
expose fetch APIs constructors

### ISSUE THREAD

**Issue by Kikobeats** [capricorn86/happy-dom#317]
Hello, this project is super great, thanks for it!

I can see you are using `node-fetch` to expose `fetch` primitive
https://github.com/capricorn86/happy-dom/blob/15964665b5c11442ba7d8843164c28c713d39590/packages/happy-dom/src/window/Window.ts#L430

There are some global APIs that are missing right now and you can expose them from `node-fetch`:

```js
global.Headers = require('node-fetch').Headers
global.Request = require('node-fetch').Request
global.Response = require('node-fetch').Response
```

I wanted to make a PR but not sure what should be the right place at code to expose them.

Also, related to network APIs, could be nice to add `AbortController` and `AbortSignal`. These APIs are the preferred way to abort requests on the browser.

```js
const controller = new AbortController();
const response = fetch('https://example.com', {
  signal: controller.signal
});

// about the request after 3s timeout
setTimeout(controller.abort, 3000);

await response
```

This is a spec-compliant and tiny polyfill to consider to add (~200 bytes)
https://github.com/mysticatea/abort-controller

**Comment by capricorn86** [comment]
Hi @Kikobeats! :slightly_smiling_face: 

I will look into adding support for this as soon as possible.

**Comment by capricorn86** [comment]
Hi @Kikobeats! :slightly_smiling_face: 

I have now finally added support for Window.Request, Window.Response and Window.Headers.

It was a bit more complex than just exposing the classes from "node-fetch" as they contain asynchronous logic that has to work with the async task manager (window.happyDOM.whenAsyncComplete()).

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.51.0

**Comment by msawatzky75** [comment]
Was this going to include the `AbortController` too? or should that be a separate issue?
