### ISSUE TITLE
createElementNS does not set style for svg?

### ISSUE THREAD

**Issue by mpope9** [capricorn86/happy-dom#319]
Background: I'm trying to use happy-dom with Deno and Apache Echarts for server side rendering. I am hitting an error, and I think it traces back to `createElementNS` not setting the style. I'm not 100% sure though.

Repro:
```javascript
// happy_renderer.js

import * as echarts from "https://esm.sh/echarts@5.2.2";
import Canvas from "https://esm.sh/canvas";
import { Window } from "https://esm.sh/happy-dom";

echarts.setCanvasCreator(() => {
    return new Canvas(100, 100);
});

const window = new Window();
const document = window.document;
document.body.innerHTML = '<div id="graph"></div>';

globalThis.document = document;

const root = document.getElementById("graph");
root.style.cssText = 'width: 500px; height: 500px;';

const chart = echarts.init(root, null, {
    renderer: 'svg'
});
```

Run with:
```bash
deno run -A --unstable happy_renderer.js
```

Error:
```bash
error: Uncaught TypeError: Cannot set properties of undefined (setting 'cssText')
    at new e (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/svg/Painter.js:3:64805)
    at new r (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/zrender.js:2:74605)
    at co (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/zrender.js:2:77790)
    at new t (https://cdn.esm.sh/v58/echarts@5.2.2/deno/echarts.js:11:2339)
    at Module.use (https://cdn.esm.sh/v58/echarts@5.2.2/deno/echarts.js:11:21575)
    at file:///Users/pope/Projects/stats_5thq/priv/ssr/happy_renderer.js:19:23
```

I've traced this to the function `e` above:
`e (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/svg/Painter.js:3:64805)`

Calling a function  `k`:
```javascript
k(e){return document.createElementNS("http://www.w3.org/2000/svg",e)}

e(...){
  ...
  var a=k("svg"); 
  ...
  a.style.cssText="user-select:none;position:absolute;left:0;top:0;"
};
```

Does this make sense as an issue?

**Comment by mpope9** [comment]
I've written this Jest test to repro the issue:

```javascript
	describe('createElementNS()', () => {
		it('Creates a custom element with namespece set to SVG and can set the style.', () => {
			const svg = document.createElementNS(NamespaceURI.svg, 'svg');
			svg.style.cssText = 'user-select:none;';
			expect(svg.style.cssText).toBe('user-select:none;');
		});
	});
```

The error returned is:
```
 FAIL  test/nodes/document/Document.test.ts
  ● Test suite failed to run

    test/nodes/document/Document.test.ts:677:8 - error TS2339: Property 'style' does not exist on type 'IElement'.

    677    svg.style.cssText = 'user-select:none;';
               ~~~~~
    test/nodes/document/Document.test.ts:678:15 - error TS2339: Property 'style' does not exist on type 'IElement'.

    678    expect(svg.style.cssText).toBe('user-select:none;');
                      ~~~~~
```

I'm not sure where this style should come from, but I could give this an attempt with a pointer.

**Comment by mpope9** [comment]
So I've tried to add a `style` variable of type `CSSStyleDeclaration` to the `SVGElement.ts`. However `createElementNS` returns a `IElement` so it still throws a undefined property error. The spec doesn't define that `IElement` has `style`, so I'm not super sure how to proceed on this.

Should the `Element.ts` have a getter/setter for `style`, and if if is `null`, then throw the undefined error?

I'm still new to JS so I'm not sure the best way to proceed.

**Comment by capricorn86** [comment]
Hi @mpope9! :slightly_smiling_face: 

This sounds like like a bug. I will look into it as soon as possible.

**Comment by mpope9** [comment]
@capricorn86 thank you much. I'm looking at how this is implemented in `HTMLElement.ts`, I will make a PR if I can make sense of this.

**Comment by capricorn86** [comment]
Contributions are always very welcomed! :slightly_smiling_face: 

Let me know if you have any questions.

**Comment by capricorn86** [comment]
Thank you for your contribution @mpope9! :slightly_smiling_face:
