### ISSUE TITLE
Missing ParentNode APIs?

### ISSUE THREAD

**Issue by jonnyarnold** [capricorn86/happy-dom#32]
I can't find a mention of `firstElementChild` in this repository, which is defined in the [ParentNode interface](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/firstElementChild). Is this supported by happy-dom?

**Comment by capricorn86** [comment]
Thank you for reporting this @jonnyarnold!

I just made a fix for it and it is available in v0.11.0 of happy-dom and v0.0.39 of jest-environment-happy-dom.
