### ISSUE TITLE
`tagName` can be null

### ISSUE THREAD

**Issue by userquin** [capricorn86/happy-dom#321]
`tagName` can be `null`, we need to modify the logic on `Element.ts` since it is causing problems to test web components using `lit` on `vitest` repo

**Comment by capricorn86** [comment]
Hi @userquin! :slightly_smiling_face: 

I am not sure that your fix was released as there was a unit test failing after the merge. However, the unit test is fixed and your fix should not be part of the latest version of Happy DOM.

**Comment by userquin** [comment]
@capricorn86 no problem, just ping me when released to update Happy DOM and remove the workaround on vitest repo on lit example.

**Comment by capricorn86** [comment]
@userquin great! Just to clarify, the fix is released :slightly_smiling_face:

**Comment by userquin** [comment]
@capricorn86 it seems to be included on `2.25.2`

![imagen](https://user-images.githubusercontent.com/6311119/149243429-727bf900-304f-451e-b193-f40f7731b868.png)

**Comment by userquin** [comment]
> @userquin great! Just to clarify, the fix is released 🙂

sorry man, I read `not`  instead `now` in your comment, thx again.

**Comment by capricorn86** [comment]
No problem! Thats because I wrote "not" by mistake, but I corrected it :sweat_smile:
