### ISSUE TITLE
unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React

### ISSUE THREAD

**Issue by azat-io** [capricorn86/happy-dom#325]
I am trying to run a simple test with [Vitest](https://vitejs.dev/) but I get the following warning: `Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React`

Here is a part of my `vite.config.ts`:

```ts
    test: {
      environment: 'happy-dom',
      global: true,
    },
```

How can I fix it?

Looks like it is the same problem: https://github.com/capricorn86/happy-dom/issues/248

**Comment by capricorn86** [comment]
Thanks for reporting @azat-io! :slightly_smiling_face: 

It seems like a misinterpreted the issue in #248.

The issue should now be fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.25.2
