### ISSUE TITLE
ReferenceError: HTMLCollection is not defined

### ISSUE THREAD

**Issue by tamascsaba** [capricorn86/happy-dom#327]
Global HTMLCollection not exploded.
You can easily reproduce the issue:

```
import { Window } from 'happy-dom';

const window = new Window();
console.log(window.HTMLElement) // HTMLElement
console.log(window.HTMLCollection) // undefined
```

My original error came from flatpickr.
```
    ReferenceError: HTMLCollection is not defined

      18 |
    > 19 | import flatpickr from 'flatpickr';
         | ^

      at ../../node_modules/flatpickr/dist/flatpickr.js:2058:5
      at ../../node_modules/flatpickr/dist/flatpickr.js:3:65 
```

**Comment by tamascsaba** [comment]
It is the same with `NodeList`

**Comment by tamascsaba** [comment]
I use in happy-dom in jest test environment with the following config: `testEnvironment: '@happy-dom/jest-environment',`

**Comment by capricorn86** [comment]
Thank you for reporting @tamascsaba! :slightly_smiling_face: 

I have added support for Window.HTMLCollection and Window.NodeList now.

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.29.0
