### ISSUE TITLE
ClassList doesn't include `toggle`

### ISSUE THREAD

**Issue by Ayc0** [capricorn86/happy-dom#328]
When using `happy-dom` with `classlist-polyfill`, I have this error:

```
TypeError: testElement.classList.toggle is not a function
```

When looking at https://github.com/capricorn86/happy-dom/blob/ab971406111805e8d940419acc6500c601eb0aa2/packages/happy-dom/src/nodes/element/ClassList.ts, it doesn't seem to have `toggle` defined in it

**Comment by capricorn86** [comment]
Thank you for your contribution @Ayc0! slightly_smiling_face

It has been merged and released now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.27.0
