### ISSUE TITLE
[bug] HTMLUnknownElement is missing

### ISSUE THREAD

**Issue by TechQuery** [capricorn86/happy-dom#33]
`HTMLUnknownElement` is uncommonly used, but it's important sometimes, such as
https://github.com/EasyWebApp/WebCell/blob/c3adfc711bbb472c4194609536b212a52d7c02a3/source/utility.ts#L73

happy-dom 0.11.0+ lost it...

**Comment by capricorn86** [comment]
Hi @TechQuery!

Thank you for reporting the bug. I am not sure that we have ever supported it, but I will fix it as soon as possible.

It might come as part of the v1.0.0 release that I am working on, as it could be a bit bigger change to add support for it.

**Comment by TechQuery** [comment]
Great! (I'm sure, because my tests crashed after upgrading)

**Comment by capricorn86** [comment]
Hi @TechQuery!

Sorry that it has taken such a long time before I could release v1.0.0.

Happy DOM now has support for HTMLUnkownElement, together with a lot of other features.

I will now close this issue now.
