### ISSUE TITLE
`document.location` is undefined

### ISSUE THREAD

**Issue by Ayc0** [capricorn86/happy-dom#330]
According to the spec https://developer.mozilla.org/en-US/docs/Web/API/Location, `location` is supposed to be set to both `document` and `window`.

But in `happy-dom`, it's only set in `window`

**Comment by Xa3lis** [comment]
I've the same problem

**Comment by capricorn86** [comment]
Thank you for your contribution @Ayc0! :slightly_smiling_face: 

It has been merged and released now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.26.0
