### ISSUE TITLE
Serializer escapes attributes too much

### ISSUE THREAD

**Issue by Demivan** [capricorn86/happy-dom#335]
I tried using happy-dom with Vitest and when switching from jsdom I got a failing test:

![image](https://user-images.githubusercontent.com/2339406/150375626-9222cbc2-cfe2-47d1-b9b4-b0c976630346.png)
  
![image](https://user-images.githubusercontent.com/2339406/150375278-4d61320c-caf7-4464-96af-771a173cc134.png)
 
happy-dom is escaping characters in html attributes that are allowed. These is not need to use `encode` from `he`, `escape` is enough.

**Comment by capricorn86** [comment]
Thanks for contributing @Demivan! :slightly_smiling_face: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.27.3
