### ISSUE TITLE
Svelte components fail because of missing initCustomEvent()

### ISSUE THREAD

**Issue by angryziber** [capricorn86/happy-dom#338]
Compiled Svelte components use this code to build custom events:
```
function custom_event(type, detail, bubbles = false) {
    const e = document.createEvent('CustomEvent');
    e.initCustomEvent(type, bubbles, false, detail);
    return e;
}
```

When running under happy-dom, it says that `initCustomEvent` is not defined

**Comment by capricorn86** [comment]
Thank you for reporting @angryziber! :slightly_smiling_face: 

I have implemented support for CustomEvent.initCustomEvent() now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.30.0

**Comment by capricorn86** [comment]
@enyo good suggestion! :slightly_smiling_face: 

We should add an integration test for Svelte as well to verify that it keeps working if things changes.

I have added #491 for creating the integration test and add Svelte to the docs.

**Comment by angryziber** [comment]
Unfortunately it didn't still work when I last checked... Need to investigate a bit more
