### ISSUE TITLE
Classes should implement "Native" types

### ISSUE THREAD

**Issue by Atyn** [capricorn86/happy-dom#34]
The class "HTMLElement" should implement the official Typescript "HTMLElement" e.g. because of two reasons:

1. They can be used were native types are used (e.g. declared arguments)
2. We ensure that they implement the same propeties/methods

**Comment by capricorn86** [comment]
@Atyn it is not possible to import Native types without doing globally as a lib. Because of this, it is unfortunately not possible to achieve this.

**Read more about it here:**
https://stackoverflow.com/questions/59061266/can-i-import-dom-types-explicitly

**Comment by capricorn86** [comment]
I will close this issue.
