### ISSUE TITLE
Handling of Event.currentTarget breaks testing-library user events

### ISSUE THREAD

**Issue by atk** [capricorn86/happy-dom#343]
Event.currentTarget is supposed to be read only, so attempting to overwrite it will throw an error.

Instead, one is supposed to use Object.defineProperty to set the current target.

**Comment by benbender** [comment]
May be related: https://github.com/capricorn86/happy-dom/issues/544

**Comment by capricorn86** [comment]
Thanks for reporting @atk ! :slightly_smiling_face: 

I have created a fix that will not set Event.target and Event.currentTarget directly. However, you will probably run into more problems if you let Vitest transpile external libraries. You need to change the transform config to only transform your app source code to avoid this problem.

```javascript
    transformMode: {
      web: [/src\/\.[tj]sx?$/]
    }
```

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.6

**Comment by atk** [comment]
Thanks for you answer. I'll update my articles on testing solid accordingly, once I get to it.
