### ISSUE TITLE
.innerText doesn't add \n newlines like browser does

### ISSUE THREAD

**Issue by devinellis** [capricorn86/happy-dom#344]
_First, let me say thanks for your work on HappyDOM, I'm really happy with the performance. I'm using it to feed Mozilla's Readability library to extract articles from HTML documents._

### Steps to Reproduce
```
document.body.innerHTML = '<div>The <strong>quick</strong> brown fox</div><div>Jumped over the lazy dog</div>'
document.body.innerText
```

**Returns**
```The quick brown foxJumped over the lazy dog```

**Expected (Firefox and Chrome)**
```The quick brown fox\nJumped over the lazy dog```

I verified this behavior in Chrome and Firefox. As far as I can tell, they do it for block level elements.

This is causing things like `<li>` lists to get merged together. My temporary fix is to append a whitespace to every text, but this still creates runon sentences with no break.

Another inconsistency is how newlines within the HTML are handled:
```
document.body.innerHTML = '<span>The quick brown fox</span>\n<span>Jumped over the lazy dog</span>'
document.body.innerText
```

**Returns**
```The quick brown fox\nJumped over the lazy dog```

**Expected**
```The quick brown fox Jumped over the lazy dog```

Logically, the `\n` is treated as whitespace and not specifically a newline (i.e. word-wrapped code doesn't mean it should be rendered with the same breaks)

**Comment by devinellis** [comment]
Checking in on this. I just confirmed this is still happening on v3.1.1. It turns out that my workaround is causing some unintended behavior. Maybe my use-case is not very common so no one else has noticed this issue.

**Comment by devinellis** [comment]
Feel free to close. I have switched to using linkedom for my use-case.

**Comment by capricorn86** [comment]
Too bad to hear that Happy DOM couldn't help you with your case.
 
 I believe I understand the problem now. I assumed that innerText for `<body>` behaves the same as innerText as other elements, but it seems like they behave differently. I tested with a `<div>` element.
 
```javascript
 var div = document.createElement('div');
 div.innerHTML = '<div>The <strong>quick</strong> brown fox</div><div>Jumped over the lazy dog</div>';
 
 document.body.innerHTML =  '<div>The <strong>quick</strong> brown fox</div><div>Jumped over the lazy dog</div>';
 
 // Outputs: "The quick brown fox\nJumped over the lazy dog"
 console.log( document.body.innerText);
 
 // Outputs: "The quick brown foxJumped over the lazy dog"
 console.log( div.innerText);
```

**Comment by capricorn86** [comment]
Actually, it is not the <body> element that behaves different. It should just render it differently if it is connected to the document or not.
