### ISSUE TITLE
`document.scrollingElement` is `undefined`

### ISSUE THREAD

**Issue by Shinigami92** [capricorn86/happy-dom#350]
- https://caniuse.com/document-scrollingelement
- https://github.com/quasarframework/quasar/pull/12314/files#diff-dbabc490b58d99bc7a91dec1c6f0d13ee2f67ded096284632c2bb97ba1a8c540R65
- https://discord.com/channels/415874313728688138/806172040804827188/938759874119098398
![image](https://user-images.githubusercontent.com/7195563/152336127-1b7f0535-682c-4dce-9f30-27d35a877a06.png)

/cc @IlCallo

**Comment by IlCallo** [comment]
Seems like we end up [fixing it with a fallback](https://github.com/quasarframework/quasar/issues/12318) anyway, still interested into knowing if this is a Quasar problem or a JSDom/HappyDOM one

**Comment by capricorn86** [comment]
Thanks for reporting @Shinigami92 and @IlCallo! :slightly_smiling_face: 

I have added support for Document.scrollingElement.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.35.0
