### ISSUE TITLE
Missing window.performance

### ISSUE THREAD

**Issue by paparent** [capricorn86/happy-dom#351]
I'm experimenting with vitest and happy-dom since it's suggested here: https://vuejs.org/guide/scaling-up/testing.html#recipes

When I integrate [vue-i18n-next](https://github.com/intlify/vue-i18n-next), I have an error because it needs `window.performance.now()`.

**Comment by capricorn86** [comment]
Thanks for reporting @paparent! :slightly_smiling_face: 

I have added support for Window.performance.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.37.0
