### ISSUE TITLE
Add support for CSS.supports()

### ISSUE THREAD

**Issue by Schloemicher** [capricorn86/happy-dom#352]
[MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports)

I would like to add this static function so it at least exists.

Personally i am fine with returning always true or false.

**Comment by capricorn86** [comment]
Thanks for reporting @Schloemicher! :slightly_smiling_face: 

I have added support for the CSS interface now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.38.0
