### ISSUE TITLE
TypeError: Image is not a constructor

### ISSUE THREAD

**Issue by msawatzky75** [capricorn86/happy-dom#353]
Running tests with vitest, Vuetify and `@testing-library/vue` gives an error in the `VImg` component saying Image is not a constructor.

The image spec is referenced here: [https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image).

i'm currently working around this by using jsdom instead.

**Comment by linkurzweg** [comment]
Same problem here, I'm also using `@testing-library/vue` but NaiveUI instead of Vuetify.

**Comment by capricorn86** [comment]
Hi @msawatzky75 and @linkurzweg! :slightly_smiling_face: 

I have added support for Image as a constructor.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.34.0

**Comment by linkurzweg** [comment]
@capricorn86 Thank you! Now a lot of my tests pass, still got some that work with jsdom but don't work with happy-dom though. I'll create issues for the errors I'm getting :)
