### ISSUE TITLE
TypeError: input.stepUp /  input.stepDown  is not a function

### ISSUE THREAD

**Issue by linkurzweg** [capricorn86/happy-dom#366]
When I try to test a Vue 3 component in vitest with an input of type number I get an error when trying to use stepUp/stepDown on the input element.

`TypeError: input.value?.stepDown is not a function`

It looks like those methods aren't implemented yet?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp

**Comment by capricorn86** [comment]
Thanks for reporting @linkurzweg! :slightly_smiling_face: 

I have added support for stepDown() and stepUp() now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.39.0

**Comment by linkurzweg** [comment]
@capricorn86 Wow, you're fast! Thanks :D
