### ISSUE TITLE
Using sizzle for querySelectors?

### ISSUE THREAD

**Issue by mat3e** [capricorn86/happy-dom#37]
[Sizzle](https://github.com/jquery/sizzle) is a selector engine used by jQuery. It was there before `querySelectorAll` and similar methods. Now, it uses `querySelectorAll` if available.

I've seen there are changes in happy-dom selectors on `v1.0.0` branch, but maybe it's still valuable to use Sizzle? I gave it a quick try with happy-dom, but unfortunately, Sizzle expects `window` object to be available. We could experiment with it further (I think even contributing in Sizzle isn't a problem), but the question is - is this worth it? What do you think?

**Comment by capricorn86** [comment]
I will look into using Sizzle :+1: 

I have done a lot of fixes in the v1.0.0 branch and the issues you are experiencing might already been solved.

**Comment by allain** [comment]
I second this as I just got bitten by a querySelector bug. Specifically *.querySelector('[attribName]') was returning null when it shouldn't.

Delegating to another project that does all the weird edge cases of querySelector is probably the most bang for you buck.

**Comment by capricorn86** [comment]
The query selector "[attribName]" has been fixed in the v1.0.0 and is covered by a unit test, but there could be other query selectors that are not covered.

I will look into Sizzle and see how we can make sure that all types of selectors are covered.

**Comment by capricorn86** [comment]
Hi @mat3e and @allain!

Sorry that it has taken such a long time before I could release v1.0.0 and fix the issues related to query selectors.

Happy DOM now has support for all the query selectors that Sizzle has. It also has unit tests for covering it.

I will now close this issue now.
