### ISSUE TITLE
TypeError: element.ownerDocument.getSelection is not a function

### ISSUE THREAD

**Issue by linkurzweg** [capricorn86/happy-dom#370]
When I test a component with vitest and @testing-library/user-event and try to get an element with `getByLabelText`, I get the following error:
`TypeError: element.ownerDocument.getSelection is not a function`

Would be great to have this fixed as well :)

**Comment by capricorn86** [comment]
Thanks for reporting @linkurzweg! :slightly_smiling_face: 

I have added basic support for Document.getSelection(). Hopefully it will solve the problem for you.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.41.0
