### ISSUE TITLE
slot element is null when querying it with '>'

### ISSUE THREAD

**Issue by ahmadigbaryia** [capricorn86/happy-dom#38]
when trying to get the slot element I receive null!

```js
//<div class="card-footer"><slot name="footer"></slot></div>
console.info(`${this.shadowRoot.querySelector(".card-footer")}`);// => the div element
console.info(`${this.shadowRoot.querySelector(".card-footer > slot")}`);// => null
console.info(`${this.shadowRoot.querySelector(".card-footer slot")}`);// => the slot element
```

**Comment by capricorn86** [comment]
Hi @ahmadigbaryia!

Thank you for reporting! I will look into it as soon as I can.

**Comment by capricorn86** [comment]
Hi @ahmadigbaryia!

Sorry that it has taken such a long time before I could release a fix for this issue.

I have worked on v1.0.0, which is now released. It has support for all native query selector features.

**Comment by capricorn86** [comment]
Hi @ahmadigbaryia!

Sorry that it has taken such a long time before I could release a fix for this issue.

I have worked on v1.0.0, which is now released. It has support for all native query selector features.

I will close this issue now.
