### ISSUE TITLE
QuerySelector class in happy-dom/jest-environment does not work (Breaking change or bug)

### ISSUE THREAD

**Issue by daBack** [capricorn86/happy-dom#395]
**Issue:**
When querySelecting a web component with a class (like 'webcomponent-123.aClassName') The returned element will skip the class selection and only search for the `webcomponent-123`.

This means that if there are several components of the same web component (might be for every element, not only custom elements), It will always return the first component matched.

In our case, we render 3 custom web components like this.
Dom:
```
<webcomponent class="aClassName1"></webcomponent>
<webcomponent class="aClassName2"></webcomponent>
<webcomponent class="aClassName3"></webcomponent>

```
We try to querySelect the second component like this 
`const test = querySelector('webcomponent.aClassName2')`

Expected: test.className = aClassName2
Result: test.className = aClassName1

This happend somewhere between version 2.42.0 and 2.43.1. The issue seems to be in the happy-dom and not happy-dom/jest-environment, since even thought we cap the jest-environment to 2.42.0, it has a dependency to happy-dom with a ^, making it increase to a version not working.

Solution in Happy dom: Not sure what is causing it. An idea is the addition or fix of `:not` and rewriting the "matchClass" method.
Somewhere it does not take the class name into account when query selecting.

Our solution:
What we did in our project, was to cap the version of both jest-environment and its dependency to 2.42.0.

**Comment by capricorn86** [comment]
Thank you for reporting @daBack! :slightly_smiling_face: 

I have created a fix for the bug now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.46.1
