### ISSUE TITLE
eval should be returning the result

### ISSUE THREAD

**Issue by dylang** [capricorn86/happy-dom#396]
https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/window/Window.ts#L328-L330

Example:

```
const x = eval('() => 5');
x();
\\ => 5
```

This is causing packages that depend on https://github.com/dougwilson/nodejs-depd to fail because it returns a new function generated using `eval`.

Possible fix:

```ts
		if (global && vm && vm.isContext(this)) {
			return vm.runInContext(code, this);
		} else if (global && global.eval) {
			return global.eval(code);
		}
```

Typing for `eval` will need to be updated as well.

**Comment by capricorn86** [comment]
Thanks for reporting @dylang! :slightly_smiling_face: 

I have made a fix for it now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.46.3

**Comment by KlausEverWalkingDev** [comment]
Hello @capricorn86, I apologize in advance for taking advantage of the interation in this issue. @dylang, could you please give a look on https://github.com/dylang/npm-check/pull/397? Someboby made a nice PR with some lovely additions and updates on npm-check package, a project that I greatly recommend. Have a nice day, folks :)
