### ISSUE TITLE
[BUG] ShadowRootRenderer - Removes unassigned text nodes

### ISSUE THREAD

**Issue by itutto** [capricorn86/happy-dom#400]
### Hey there,

I've noticed that the server-renderer removes the perfectly valid simple `textNode` type children of a custom element. 
https://github.com/capricorn86/happy-dom/blob/7f03049c01f6c50b8cead43706c32496675120b3/packages/server-rendering/src/renderer/shadow-root/ShadowRootRenderer.ts#L77

### Example:
```js
class SimpleStyler extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({mode: 'open'}).innerHTML = '<style>color: "red";</style>';
  }
}

customElements.define('simple-styler', SimpleStyler);
```
```html
<simple-styler>Text node should not be removed</simple-styler>
```
The above example fails to render correctly by `HappyDOMServerRenderer` even if the web component has a default `slot` as the textNode is not listed by `element.children` https://github.com/capricorn86/happy-dom/blob/7f03049c01f6c50b8cead43706c32496675120b3/packages/server-rendering/src/renderer/shadow-root/ShadowRootRenderer.ts#L56

#### Output will be:
```html
<simple-styler><style>color: "red";</style></simple-styler>
```

#### Expected output:
```html
<simple-styler><style>color: "red";</style>Text node should not be removed</simple-styler>
```

Let me know if you'd prefer me to create a PR.
Thanks

**Comment by capricorn86** [comment]
Hi @itutto! :slightly_smiling_face: 

The server-rendering package has many limitations and I have now chosen to deprecate it in favor of [Declarative Shadow DOM](https://chromestatus.com/feature/5191745052606464).

I have now added support for [Declarative Shadow DOM](https://chromestatus.com/feature/5191745052606464)  and there is a [guide here](https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom#server-side-rendering-of-web-components) that explains how use it in Happy DOM.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.47.0

**Comment by itutto** [comment]
Thanks! :)
I've tested the [example code](https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom#server-side-rendering-of-web-components) and I didn't get the ShadowDom rendered, only the light dom:
```
                <my-custom-element>
                    <span>Slotted content</span>
                </my-custom-element>
```

**Comment by capricorn86** [comment]
@itutto you are right. It seems like there is a bug where custom elements aren't loaded when defined. They have to be defined before the HTML is rendered.

I have created a new bug for it:
https://github.com/capricorn86/happy-dom/issues/404

**Comment by capricorn86** [comment]
@itutto the problem should now be fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.47.1

**Comment by itutto** [comment]
@capricorn86 Thanks so much for the quick fix!
