### ISSUE TITLE
document.charset not impl

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#402]
```javascript

document.write(`<!doctype html>
<meta charset="windows-1252">
<a href="?sm&ouml;rg&aring;sbord">Test</a>`)

console.log(document.charset);
console.log(document.characterSet);

```

```javascript
undefined
undefined
```

**Comment by capricorn86** [comment]
Hi @Mas0nShi! :slightly_smiling_face: 

I have added support for Document.characterSet and Document.charset.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.48.0
