### ISSUE TITLE
incorrect insertBefore work

### ISSUE THREAD

**Issue by seliverstov-logema** [capricorn86/happy-dom#421]
Hey! 

There is a incorrect work of insertBefore

```
const d = document.createElement('div');
d.innerHTML = '<span id="a"></span><span id="b"></span><span id="c"></span><span id="d"></span>';

const a = d.querySelector('#a');
const b = d.querySelector('#b');

d.insertBefore(a, b);

console.log(d.innerHTML)
```

in it has to show not changed order of elements

but it shows `<span id="b"></span><span id="a"></span><span id="c"></span><span id="d"></span>`

**Comment by capricorn86** [comment]
Thanks for reporting @seliverstov-logema and @EstDavid! :slightly_smiling_face: 

The issue has been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.7.1
