### ISSUE TITLE
Cannot add function to Array prototype

### ISSUE THREAD

**Issue by provegard** [capricorn86/happy-dom#430]
Hi!

I decided to try happy-dom instead of jsdom for my Jest tests due to the advertised speedup. My code adds a function to `Array.prototype`:

    Array.prototype.groupBy = () => ...

With jsdom, this works. With happy-dom, it doesn't. If I put a breakpoint right after the function has been added, I can see that the function is present (`[].groupBy` is a function) with jsdom but is undefined with happy-dom.

Do I have to configure happy-dom to allow adding to the prototype of native objects?

**Comment by capricorn86** [comment]
Thank you for reporting @provegard! :slightly_smiling_face: 

There seem to be a general problem when using a virtual machine that we also had with Object and Function. I have applied the same fix for Array now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.51.0

**Comment by provegard** [comment]
Hi! I tested 2.51.0 but I'm seeing the same problem.

**Comment by capricorn86** [comment]
@provegard I have done multiple tests where I run `Array.prototype.groupBy = () => {}` both in a VM and without. For me it works and arrays get the `[].groupBy()` function.

How do you run the code? Is it through Jest, in a VM or some other way? :slightly_smiling_face:

**Comment by provegard** [comment]
It's through Jest. I'll try again!

**Comment by capricorn86** [comment]
I will test in Jest as well and see if I can reproduce it :sweat_smile:

**Comment by capricorn86** [comment]
@provegard it works for me in Jest. I have you tested it again?

**Comment by capricorn86** [comment]
This problem should now finally be fixed :slightly_smiling_face: 

It was not easy to fix as it required major changes.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v3.0.0
