### ISSUE TITLE
ELEMENT_NODE is missing from the node instance

### ISSUE THREAD

**Issue by silvenon** [capricorn86/happy-dom#433]
Hi! I noticed that instances of `Node`, or at least `HTMLElement`, don't have the `ELEMENT_NODE` property.

```js
const { Window } = require('happy-dom')

const window = new Window();
const document = window.document;

document.body.innerHTML = '<div class="container"></div>';

console.log(document.querySelector('.container').ELEMENT_NODE) // undefined
```

I discovered this while migrating from Jest to Vitest, and at the same time moving from `jsdom` to `happy-dom`. I noticed that computing the accessible name of elements started coming up empty in Testing Library, which uses [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) for that functionality, which relies on `ELEMENT_NODE`. (It was quite a debugging trip! 😄)

I see `ELEMENT_NODE` in your codebase, though 🤔 so hopefully you'll be able to shed some light on this, thanks! 🤞

**Comment by capricorn86** [comment]
Thank you for reporting @silvenon! :slightly_smiling_face: 

I have fixed the issue now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.52.0
