### ISSUE TITLE
Class 'Headers' incorrectly implements interface 'IHeaders'.

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#439]
when i pull the latest main branch, i can't run `tsc` compile.
```
 error TS2420: Class 'Headers' incorrectly implements interface 'IHeaders'.
  Type 'Headers' is missing the following properties from type 'IHeaders': forEach, append, delete, get, and 7 more.

7 export default class Headers extends NodeFetch.Headers implements IHeaders {}
                       ~~~~~~~
```

**Comment by capricorn86** [comment]
Hi @Mas0nShi! :slightly_smiling_face: 

I am not able to reproduce the error. Maybe we sit on a different environment.

Which Node version do you use? I use Node v16.14.2.

**Comment by Mas0nShi** [comment]
> 

I use v17.7.1 and v12.18.3, i will try new folder to pull the latest branch and compile again.

**Comment by Mas0nShi** [comment]
okay, it's my problem.
