### ISSUE TITLE
setCustomValidity is not a Function

### ISSUE THREAD

**Issue by msawatzky75** [capricorn86/happy-dom#442]
`HTMLInputElement.prototype.setCustomValidity` is not a function.

right now, i am able to get around the issue by mocking it: 
```
import { vi } from "vitest";
window.HTMLInputElement.prototype.setCustomValidity = vi.fn();
```

**Comment by capricorn86** [comment]
Thanks for reporting @msawatzky75! :slightly_smiling_face: 

I have added support for HTMLInputElement.setCustomValidity(), HTMLInputElement.reportValidity() and HTMLInputElement.validationMessage now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.54.0
