### ISSUE TITLE
Move from ES5 to ES6

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#448]
Still use CommonJS for imports as ES6 imports (ESM) may cause problems for some.

**Comment by hornta** [comment]
Hi, I don't know if this PR was triggered by my issue but do you think this change solves my problem?
https://github.com/capricorn86/happy-dom/issues/447

I'll be able to test this out later today.

**Comment by capricorn86** [comment]
Hi @hornta! 🙂 
Yes I hope it will fix it, but the publish build failed and I did not have time to fix it.

I will let you know when it succeeds and you can test.

**Comment by capricorn86** [comment]
This problem has finally been fixed @hornta! :slightly_smiling_face: 

It was not easy to fix and required some major changes.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v3.0.0
