### ISSUE TITLE
window.getSelection is not a function

### ISSUE THREAD

**Issue by cll123456** [capricorn86/happy-dom#457]
I use vitest to test my component， but my component use `window.getSelection()` api, i get errors as follows:

![image](https://user-images.githubusercontent.com/41314419/164406910-d0d6be28-0419-4591-8cc6-0e63fffc7046.png)

**Comment by Mas0nShi** [comment]
I will submit PR for this issue.

> You can call `Document.getSelection()`, which works identically to `Window.getSelection()`

Refer: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection
https://w3c.github.io/selection-api/#dom-window-getselection

**Comment by capricorn86** [comment]
Thank you for helping out @Mas0nShi! :slightly_smiling_face:
