### ISSUE TITLE
<select /> throws error if value is empty

### ISSUE THREAD

**Issue by catc** [capricorn86/happy-dom#461]
If select value is an empty string (ie: user hasn't selected an option yet), happy dom (via jest env) + rtl throws an error:
```tsx
import { render } from '@testing-library/react';

function Foo() {
  const value = '';
  return (
    <div>
      <select name="" id="" value={value}>
        <option value="foo" />
      </select>
    </div>
  );
}

describe('<Foo />', () => {
  it('renders', () => {
    render(<Foo />);
  });
});
```

Error:
<img width="760" alt="Screen Shot 2022-04-29 at 2 18 01 PM" src="https://user-images.githubusercontent.com/5651132/166000889-cec07cf8-7e36-4412-92d3-5e9e147bfbe6.png">

**Comment by capricorn86** [comment]
Thanks to @fatihcure-jf we now have support for HTMLOptGroupElement, HTMLOptGroupElement and HTMLSelectElement.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v5.1.0
