### ISSUE TITLE
ci stuck

### ISSUE THREAD

**Issue by woldtwerk** [capricorn86/happy-dom#462]
I updated from ^2.55.0 to latest and this causes my github pipeline to get stuck after the tests are done. Oddly enough it works on windows. only linux and macos get stuck.

Am I overseeing something in the upgrade notes which can cause this?

I'm using vitest for testing.

link to repo:
https://github.com/ueberbit/lib

![image](https://user-images.githubusercontent.com/32794633/166200496-9acd402e-992d-4d8d-9e29-a7acad7e1b21.png)

**Comment by tapioko** [comment]
I probably have the same issue, although I use Windows 10 (21H2). Works fine with version 2.55.0, gets randomly stuck with 3.0.0. I also use vitest (0.10.2) for testing.

To reproduce, create **at least three** test files like this:

```
import { describe, expect, it } from 'vitest';

describe('suite name', () => {
    it('foo', () => {
        expect(1 + 1).toEqual(2);
    });
});
```
Then run tests with "npx vitest". Press enter many times until it gets stuck. The more test cases or tests files there are, the sooner it will get stuck (probably takes less than 10 retries).

My minimal vite.config.ts:
```
import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        environment: 'happy-dom',
    },
});

```

**Comment by dennismphil** [comment]
I have this same issue as well with \`3.1.0\`. When I downgrade to `2.55.0` it works.  

The command that is getting stuck on local. I am using c8 for coverage reporting  
 

```typescript

// package.json

 "scripts": {
  ..
  ..
  "coverage": "c8 --check-coverage --lines 80 --functions 100 pnpm test",
  "test": "vitest run",
  ..
  ..
```

**Comment by capricorn86** [comment]
Thank you for reporting @woldtwerk, @tapioko and @dennismphil! :slightly_smiling_face: 

I believe that I have localized the problem. It is a bit problematic to fix as "Window" now is running as a as a [VM context](https://nodejs.org/api/vm.html#what-does-it-mean-to-contextify-an-object) and Vitest is importing it and sets its keys in the global context.

There is a new class called GlobalWindow, which is meant to be executed in the global context.

It was not expected that Vitest imported Happy DOM this way and I wish I knew this before the major release was made. The change was done to solve multiple bugs/problems when running things with Happy DOM in a VM.

To solve this either Vitest needs to import GlobalWindow and use it instead, or Happy DOM needs to change Window to be the global window and make a new class called VMWindow (or similar).

**Comment by capricorn86** [comment]
It seems like Vitest will fix it on their side :slightly_smiling_face:

**Comment by capricorn86** [comment]
@woldtwerk, @tapioko and @dennismphil apparently the problem was not what I thought, even though it might cause other problems.

After some more debugging I found the problem. It was caused by the import of "sync-request". I have now made a fix.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v3.1.1

**Comment by woldtwerk** [comment]
Thx for the quick fix. Works like a charm again:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/32794633/167010594-b9b4f796-b6f8-49bc-9170-49cbdf0fac5b.png">

**Comment by capricorn86** [comment]
Great to hear @woldtwerk! :slightly_smiling_face:
