### ISSUE TITLE
Cannot read property '_listeners' of undefined

### ISSUE THREAD

**Issue by iamzapata** [capricorn86/happy-dom#464]
Hi, first of all, thank you so much for this library!

I have this method on a a class that is a wrapper on a DOM element. When I call the method in my tests, I can an `Cannot read property '_listeners' of undefined` error.

code:
```javascript
  destroy(): void {
    removeEventListener('click', this.handleCloseDialog)
    this.element.remove()
    this.onCloseDialog()
  }
```

error:
```bash
TypeError: Cannot read property '_listeners' of undefined
 ❯ removeEventListener node_modules/happy-dom/lib/event/EventTarget.js:27:18
 ❯ ReleaseDialog.destroy src/components/ReleaseDialog/ReleaseDialog.component.ts:89:4
     87| 
     88|   destroy(): void {
     89|     removeEventListener('click', this.handleCloseDialog)
       |    ^
     90|     this.element.remove()
     91|     this.onCloseDialog()
```

If I change my code to: 

```diff
  destroy(): void {
-  removeEventListener('click', this.handleCloseDialog)
+  window.removeEventListener('click', this.handleCloseDialog)
    this.element.remove()
    this.onCloseDialog()
  }
```

The error disappears.  Is it possible to not require the `window` prefix, or maybe also allow `globalThis` instead of `window` ?

**Comment by capricorn86** [comment]
Thanks for reporting @iamzapata! :slightly_smiling_face: 

I have fixed the problem.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v3.2.2

**Comment by iamzapata** [comment]
@capricorn86 thank you!
