### ISSUE TITLE
window.open is not a function

### ISSUE THREAD

**Issue by smarlhens** [capricorn86/happy-dom#466]
Hi there 👋🏻 ,

I hope it is the right place to ask, and I apologize if not. But I'm currently trying to test that `window.open` is correctly called by my code using `vitest` & `vue` and I'm facing the following error:

happy-dom version: **2.51.0** (I'm not using greater version because it is breaking my code, and I haven't took the time to investigate).

![image](https://user-images.githubusercontent.com/11817371/166458278-153e55b4-37a2-4583-857b-6b313fc7985d.png)

I'm not sure if it come from happy-dom, but as seen in https://github.com/capricorn86/happy-dom/issues/457 I may have thought it is the same case.

Thanks in advance, wish you a nice day ☀️ 

PS: I apologize if the subject already has an open issue and I did not see it.

**Comment by Mas0nShi** [comment]
well, it has not been implemented too. 🧐
