### ISSUE TITLE
"is" defined by createElemtent(NS) options is not being serialized.

### ISSUE THREAD

**Issue by Lusito** [capricorn86/happy-dom#478]
First of all, thanks for the project!
I couldn't find any existing issue, but searching for "is" is a bit of a lost cause :confused:  

happy-dom:
```ts
const x = document.createElement("img", { is: "lazy-img" })
x.outerHTML // `<img/>`
```

Real browser (chrome and firefox tested):
```ts
const x = document.createElement("img", { is: "lazy-img" })
x.outerHTML // `<img is="lazy-img">`

// Interestingly though:
x.getAttribute("is") // null
x.getAttributeNames() // []
```

From the above, it seems that `is` doesn't count as attribute when specified via options, but it does get serialized as attribute.

I'd say `XMLSerializer._getAttributes` needs to be adjusted, but `options.is` is not stored on the element.
Looking at the code in `createElementNS`, this may only be wanted if the custom-element has not been defined in the registry.

Does this sound reasonable to you?
- Extend the Element class with an optional `is` attribute
- Set that `is` attribute within `createElementNS` if the registry did not contain said element.
- Check for that attribute in `XMLSerializer._getAttributes` and add it to the result

If so, I can create a PR.

**Update:** SVG Elements seem to work differently:

Real browser:
```ts
const x = document.createElement("svg", { is: "lazy-img" })
x.outerHTML // firefox and chrome: `<svg is="lazy-img"></svg>`

const y = document.createElementNS("http://www.w3.org/2000/svg", "svg", { is: "lazy-img" })
y.outerHTML // chrome: `<svg is="lazy-img"></svg>`, firefox: `<svg></svg>`

const z = document.createElementNS("http://www.w3.org/1999/xhtml", "svg", { is: "lazy-svg"});
z.outerHTML // chrome and firefox: `<svg is="lazy-img"></svg>`
```

Yay for cross-browser consistency :angry:  
So it seems, that firefox makes a difference depending on the namespace.

Anyway. It looks like the xmlns is also not serialized (not in a real browser either). I guess I'll just setAttribute on both of these for now in addition, to make sure they get rendered correctly.

**Comment by capricorn86** [comment]
Hi @Lusito! :slightly_smiling_face: 

It would be great with a contribution.

I have been trying to find out how the [is attribute/value](https://html.spec.whatwg.org/multipage/custom-elements.html#attr-is) is stored within an element instance. It does not seem to be stored as an attribute. Therefore I think we should store it as a property with "_" as prefix for now. As it is referred to as "is value" everywhere, I think it makes sense to call the property "_isValue".

`XMLSerializer._getAttributes()` can then add the "_isValue" as an attribute when it renders the element. It should not add it if there is already an attribute with the name "is" as the browser seem to ignore the "is value" in this scenario.

I think we should go with how Chrome has done it as that is the most popular browser and its behavior seem more consistent.

**Comment by Lusito** [comment]
Hi @capricorn86,

Sorry for the delay. I've been out sick.

Looking at how the void elements created a new major version of happy-dom due to it serializing differently, will this not also create a new major version, since it will also serialize differently?

About the attribute: My preferred solution would be to use a Symbol instead. That way it's less likely to be used by anyone outside, as it won't show via for..in loop, Object.keys or Object.getOwnPropertyNames. If you disagree, I can use the name "_isValue" instead.

**Comment by Lusito** [comment]
Nevermind, you already have some _ prefixed variables, so it would be more consistent to use that.

**Comment by capricorn86** [comment]
Thank you for your contribution @Lusito! :slightly_smiling_face: 

I will close this issue now.
