### ISSUE TITLE
Add Happy DOM to Navigator.userAgent

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#482]
Make it possible to detect that Happy DOM is part of the user agent by adding it as a string.

Example:
```
if(navigation.userAgent.includes('Happy DOM')) {
    // Do something
}
```

**Comment by Mas0nShi** [comment]
what's mean...🤔️

in fact, we can self-rewrite userAgent, because `readonly`in typescript seems like warn not forced...
(maybe i am wrong?)

```javascript
const window = new happy.Window()

console.log(window.navigator.userAgent);
window.navigator.userAgent = "Happy DOM";
console.log(window.navigator.userAgent);
// Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
// Happy DOM

```

**Comment by capricorn86** [comment]
@Mas0nShi, yes it it possible to override the user agent, but it might be good to add a string to the user agent that indicates that it is the Happy DOM browser/environment. JSDOM has done it, so it might be expected.

**Comment by Mas0nShi** [comment]
Well, I get it. Thank for your patient answer.😀

**Comment by capricorn86** [comment]
Related to #1067

**Comment by capricorn86** [comment]
@Mas0nShi and @anthonyblond, this has now been fixed in the latest release of Happy DOM:
https://github.com/capricorn86/happy-dom/releases/tag/v12.0.0

**Comment by RobinTail** [comment]
The issue persists in `happy-dom` v14.12 and MUI grid 5.17

```
MUI: useResizeContainer - The parent DOM element of the data grid has an empty width.
Please make sure that this element has an intrinsic width.
The grid displays with a width of 0px.

More details: https://mui.com/r/x-data-grid-no-dimensions.
```
