### ISSUE TITLE
ReferenceError: Audio is not defined

### ISSUE THREAD

**Issue by Archon-** [capricorn86/happy-dom#484]
Looks like support for audio was never implemented. Reporting issue for it and I'll try to add implementation if there's nothing yet.
```
ReferenceError: Audio is not defined
```

**Comment by Mas0nShi** [comment]
Hello, as you say, Audio is not implemented.

**Comment by rudywaltz** [comment]
Hi @Archon- , did you mean audio HTML element? That is using HTMLMediaElement api like video. I start working on the implementation but be honest, I have very limited time, I can share some draft PR, the API is huge and some of need to implement for the first round. Also have some tricky behaviour at least for me. Related issue here https://github.com/capricorn86/happy-dom/issues/475

**Comment by Archon-** [comment]
Hello @rudywaltz 👋 I'm pretty sure it's about [HTMLAudioElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio). Not sure if that is part of HTMLMediaElement. If you could share your branch maybe I could continue work.

**Comment by rudywaltz** [comment]
> The HTMLMediaElement interface adds to [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) the properties and methods needed to support basic media-related capabilities that are common to audio and video.

> The [HTMLVideoElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) and [HTMLAudioElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement) elements both inherit this interface.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

**Comment by jsolly** [comment]
The lack of support for Audio was why I needed to use jsdom.
