### ISSUE TITLE
Element `dataset` not set properly when using `innerHTML`

### ISSUE THREAD

**Issue by mikestopcontinues** [capricorn86/happy-dom#493]
Hi! In the following code, `button.dataset` is an empty object. It should be `{itemId: '123'}`.

```ts
const itemId = '123';

const main = document.createElement('main');
main.innerHTML = `<button data-item-id="${itemId}"></button>`;
document.appendChild(main);

const button = main.querySelector<HTMLButtonElement>('button');

expect(button?.dataset.itemId).toBe(itemId); // FAILS
```

I'm using `happy-dom@5.0.0` for testing with `vitest@0.13.1` and `@testing-library/dom@8.13.0`.

**Comment by mikestopcontinues** [comment]
Here's a different case where the data attribute goes missing:

```ts
const itemId = '123';

const listing = document.createElement('div');
listing.id = 'listing';
listing.dataset.itemId = itemId;
listing.innerHTML = `
  <h4>Name</h4>
  <h5>$100.00</h5>
  <button>Add To Cart</button>
`;
document.appendChild(listing);

const button = main.querySelector<HTMLButtonElement>('button');

expect(button.closest('[data-item-id]')).toBeDefined(); // FAILS
```

**Comment by danielrentz** [comment]
Hi @mikestopcontinues 

Your test cases try to append elements to the `document` itself. Spec says "If you try to append an element to an existing HTML document, it might throw a HierarchyRequestError given a `<html>` element already exists." [1]

I think the test cases intend to insert the test element into the body, so I would suggest to change the test cases to do

```js
document.body.append(main);
```

However, your first test case works either way with "happy-dom".

Your second test case misses creation of the `main` element (it appends `listing` to `document`, later asks `main` for `button`). Rewriting the test to have the hierarchy `body>main>listing>button` works as expected.

I will create a PR with unit tests covering your test cases.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Document/append#appending_a_root_element_to_a_document

**Comment by mikestopcontinues** [comment]
Thanks!
