### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object (FileList)

### ISSUE THREAD

**Issue by Newbie012** [capricorn86/happy-dom#494]
I'm getting the following error:

```
TypeError: Right-hand side of 'instanceof' is not an object
 ❯ cloneObject file:/home/.../node_modules/.pnpm/react-hook-form@7.31.3_react@18.1.0/node_modules/react-hook-form/dist/index.esm.mjs:574:55
 ❯ createFormControl file:/home/.../node_modules/.pnpm/react-hook-form@7.31.3_react@18.1.0/node_modules/react-hook-form/dist/index.esm.mjs:1347:26
 ❯ Module.useForm file:/home/.../node_modules/.pnpm/react-hook-form@7.31.3_react@18.1.0/node_modules/react-hook-form/dist/index.esm.mjs:2203:16
```

which points to the [following line](https://github.com/react-hook-form/react-hook-form/blob/d8c77856c30f6ad6da8fbf753a5210ad0e1881c7/src/utils/cloneObject.ts#L14) in [react-hook-form](https://github.com/react-hook-form/react-hook-form):

```ts
!(isWeb && (data instanceof Blob || data instanceof FileList)) &&
```

It looks like [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) is being evaluated as `undefined`.

**Comment by josteph** [comment]
Got an error while using in React environment, it's pointing to this line: https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/client/ReactInputSelection.js#L62
