### ISSUE TITLE
DOMTokenList toString method returns object string.

### ISSUE THREAD

**Issue by fatihcure-jf** [capricorn86/happy-dom#496]
Hey. Currently DOMTokenList toString method returns string list `[object Object]` but the expected output ig. should be the value. An example. 
![Screen Shot 2022-06-08 at 14 21 08](https://user-images.githubusercontent.com/92732143/172604473-43b763b3-c328-4d22-9527-db0248b91fc9.png)

**Comment by capricorn86** [comment]
Thank you for your contribution! It has been merged now :slightly_smiling_face:
