### ISSUE TITLE
Get on a proxy key that is a Symbol causing an error

### ISSUE THREAD

**Issue by kalvenschraut** [capricorn86/happy-dom#501]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30308012/172898825-d5e161cf-0485-4dbc-9ffa-20e6ed87103f.png)

From looking at the that stack trace, I look at HTMLElement.js and key is a Symbol in this case so can't call .replace on it. Maybe need to check if key is not a string and key toString on it? Not to sure on the spec if it is expected for a proxy get to be triggered off a symbol access,

**Comment by capricorn86** [comment]
Thank you for your contribution @kalvenschraut! :slightly_smiling_face:
