### ISSUE TITLE
XMLParser fails for script tag with JS-Code that looks like a start tag

### ISSUE THREAD

**Issue by baranor** [capricorn86/happy-dom#504]
I ran into a problem where adding the following HTML code (simplified):
```html
<html>
<head>
    <title>Title</title>
</head>
<body>
  <script type="text/javascript">
    var vars = []
    for (var i=0;i<vars.length;i++) {}
  </script>
</body>
</html>
```
via `document.write(...)` (with script execution) or `document.documentElement.outerHTML = ...` (without script execution).

After some debugging I found the XMLParser is at fault here, as it tries to parse the `<vars` condition in the for-loop as a new tag.

The problem did have a different impact depending on the actual HTML structure:
- in the original code, it somehow caught itself, but the `textContent` of the script tag was most of the HTML document after that point
- in the above example, it allocated memory until nodejs killed it

If I understand the current parser implementation correctly, there is already handling for the similar case of actual tags within the `script`-tag, but it doesn't catch this one.

I originally stumbled upon this in `happy-dom@4.1.0`, but it still happens in `happy-dom@5.2.0`.

**Comment by Mas0nShi** [comment]
Hi, @baranor 😀, HTML parsers(XML parser) have been buggy for a long time... 
e.g. #376
I will try to fix it in my free time. thank you for your feedback.

**Comment by Mas0nShi** [comment]
Hi, @baranor 😀, HTML parsers(XML parser) have been buggy for a long time... 
e.g. #376
I will try to fix it in my free time. thank you for your feedback.

**Comment by Mas0nShi** [comment]
the reason of this bug:

only one `script` tag is matched.
the regex can't correct match `</script>`

```javascript
html
head
title
title
head
body
script
vars.length
body
html
```

https://github.com/capricorn86/happy-dom/blob/8ece2905eea8e5780e66508230689f0043c1b0e8/packages/happy-dom/src/xml-parser/XMLParser.ts#L85-L93

**Comment by capricorn86** [comment]
Thanks to @Mas0nShi we now have a fix in place 🙂 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v5.3.1
