### ISSUE TITLE
have more samples about whenAsyncComplete?

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#507]
i try to solve #420 use `window.fetch`.
it's async, i add fetch load resource after `parse`:

https://github.com/capricorn86/happy-dom/blob/f9d55eb1f31ee6538935d27c5173be5db11516f8/packages/happy-dom/src/location/URL.ts#L44-L46

then, I test it.

```javascript

window.location.href = "https://www.google.com";

window.happyDOM.whenAsyncComplete().then(() => {
	let body = window.document.getElementsByTagName('html')[0].innerHTML;
	console.log(body);
});
```

print:

```
<head></head><body></body>
refresh success
```

we did `console.log(body)` before refreshed..
maybe it's my wrong use, so anybody know why?

**Comment by Mas0nShi** [comment]
and i want to load resources at first, then print the `body`...

**Comment by capricorn86** [comment]
@Mas0nShi Happy DOM does not load anything when you set `window.location.href` at the moment.

To achieve what you are after you probably need to do something like this:

```javascript
const NodeFetch = require('node-fetch2');
const { Window } = require('happy-dom');

async function getPageHTML(url) {
    const response = await NodeFetch(url);
    const html = await response.text();
    return html;
}

async function getRenderedPageHTML(url, html) {
    const window = new Window();
    const document = window.document;
    
    // Sets URL
    window.location.href = url;
    
    // Writes page HTML
    document.write(html);
    
    // Waits for scripts to be completed
    await window.happyDOM.whenAsyncComplete();
    
    return document.documentElement.outerHTML;
}

async function main() {
     const url = 'https://www.google.com';
     const html = await getPageHTML(url);
     const renderedHTML = await getRenderedPageHTML(url, html);
     
     console.log(renderedHTML);
}

main();
```

**Comment by capricorn86** [comment]
I am not sure we should change the behavior for `location.href` at the moment as it could be a security risk that scripts can load other pages and I am not sure what should happen. We need to create a new Window instance, but the consumer will not have access to it. Maybe we can look at it in the future :sweat_smile:
