### ISSUE TITLE
GlobalRegistrator has a bad conditional for `unregister`

### ISSUE THREAD

**Issue by pearofducks** [capricorn86/happy-dom#509]
https://github.com/capricorn86/happy-dom/blob/master/packages/global-registrator/src/GlobalRegistrator.ts#L29=

This incorrectly checks if the array is populated and throws, when it should be checking the negation.

**Comment by capricorn86** [comment]
Thank you @pearofducks for fixing this! :slightly_smiling_face:  I will close this issue now.
