### ISSUE TITLE
Selector with dot fails

### ISSUE THREAD

**Issue by vrslev** [capricorn86/happy-dom#512]
Selector by attribute (`[foo="bar.baz"]`) works in browser or using JSDom, but fails with happy-dom.

JSDom outputs `HTMLDivElement {}`:

```js
const { JSDOM } = require("jsdom");

const {
  window: { document },
} = new JSDOM();

document.body.innerHTML = `
    <div name="foo.bar"></div>
`;

const result = document.querySelector('[name="foo.bar"]');
console.log(result);
```

happy-dom returns `null`, when `HTMLElement` is expected:

```js
const { Window } = require("happy-dom");

const { document } = new Window();

document.body.innerHTML = `
    <div name="foo.bar"></div>
`;

const result = document.querySelector('[name="foo.bar"]');
console.log(result);
```

**Comment by capricorn86** [comment]
Relates to #715

**Comment by capricorn86** [comment]
Thanks for reporting @vrslev! :slightly_smiling_face: 

This has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.6
