### ISSUE TITLE
XMLParser Error

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#519]
e.g. 
```javascript
const { Window } = require("../packages/happy-dom");

const window = new Window(), document = window.document;

document.write(`<html>
<!--[if lt IE 9]>
    <script>window.location = 'browser.htm';</script>
<![endif]-->
</html>`);

console.log(window.location);

```
this will result in incorrect loading scripts `window.location = 'browser.htm';`

**Comment by capricorn86** [comment]
Thanks for the contribution @Mas0nShi! :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.7.5
