### ISSUE TITLE
n.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by smarlhens** [capricorn86/happy-dom#524]
Hi there 👋🏻 ,

I hope it is the right place to ask, and I apologize if not. I'm currently using `happy-dom` with `vitest` but I'm facing the following error:

![image](https://user-images.githubusercontent.com/11817371/176379353-d55400e2-ca84-4189-82a4-6bc6831b8627.png)

```text
Binaries:
    Node: 16.15.1 - /usr/bin/node
    npm: 8.11.0 - /usr/bin/npm
  npmPackages:
    happy-dom: 5.3.4 => 5.3.4 
    vite: 2.9.13 => 2.9.13 
    vitest: 0.16.0 => 0.16.0
```

Reproduction repo: [smarlhens/vite-vitest-happy-dom-compare-document-position-is-not-a-function](https://github.com/smarlhens/vite-vitest-happy-dom-compare-document-position-is-not-a-function)

You can check using `jsdom` with `vitest` by switching `test.environment: 'jsdom'` in `vite.config.ts`.

Thanks in advance for your help, wish you a nice day sunny

**Comment by capricorn86** [comment]
Thanks for reporting! 🙂  

It seems like we are missing support for `Node.compareDocumentPosition()`.

I will look into adding it as soon as possible. You are also very welcome to make a contribution if you want.

**Comment by castanonrodrigo** [comment]
Hi guys!
Is there any update on this?

**Comment by smarlhens** [comment]
Hi @castanonrodrigo, I have no news about the review so I published a new version on a private repository with my modifications not to be blocked and I override the package as follows `"happy-dom": "npm:@<prefix>/happy-dom@6.1.0",` with custom npm registry as default.

But I guess @capricorn86 is working on #344 so maybe after he will take a look 🙏🏻
