### ISSUE TITLE
No submit event triggered for button type=submit

### ISSUE THREAD

**Issue by Doeke** [capricorn86/happy-dom#527]
This works in browsers and in JSDom, but in Happy-dom it fails:

```javascript
import { Window, Event } from 'happy-dom'

const window = new Window()
const document = window.document

document.write(`
    <html>
        <body>
            <form>
                <button type="submit">Submit</button>
            </form>
        </body>
    </html>
`)

const button = document.querySelector('button')
const form = document.querySelector('form')

form.addEventListener('submit', e => {
    console.log('on submit')
})

button.dispatchEvent(new Event('submit', { bubbles: true })) // Works
button.dispatchEvent(new Event('click', { bubbles: true })) // Doesn't work
```

Same result if I use `<input type="submit">` instead of button.

Because of this my tests fail with happy-dom but not with jsdom.

What would be a possible workaround for this?

**Comment by capricorn86** [comment]
We are missing support for HTMLButtonElement.

I will look into adding it as soon as possible.

**Comment by capricorn86** [comment]
@Doeke a possible workaround is to override the dispatchEvent() method. It can be done globally for all your tests during setup.

```javascript
const originalDispatchEvent = EventTarget.prototype.dispatchEvent;
EventTarget.prototype.dispatchEvent = function(event) {
     const result = originalDispatchEvent.call(this, event);
     if(event.type === 'click' && this.tagName === 'BUTTON') {
           this.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
     }
     return result;
};
```

**Comment by Doeke** [comment]
Thank you for the quick response!

Btw, I believe `<input type="submit">` should work the same way and also trigger a submit event when clicked

**Comment by hornta** [comment]
I created a reproducible example for easier testing in here: https://stackblitz.com/edit/vitest-dev-vitest-ktnq7h

**Comment by AndreasNasman** [comment]
Blocking issue for migrating from Jest/jsdom to Vitest/happy-dom. We have some form elements with uncontrolled inputs that rely on the submit event being fired.

**Comment by thequailman** [comment]
> @Doeke a possible workaround is to override the dispatchEvent() method. It can be done globally for all your tests during setup.
> 
> ```js
> const originalDispatchEvent = HTMLElement.prototype.dispatchEvent;
> HTMLElement.prototype.dispatchEvent = function(event) {
>      const result = originalDispatchEvent.call(this, event);
>      if(event.type === 'click' && this.tagName === 'BUTTON') {
>            this.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
>      }
>      return result;
> };
> ```

I had to tweak this example otherwise it fired with every button click:

```
const originalDispatchEvent = HTMLElement.prototype.dispatchEvent;
HTMLElement.prototype.dispatchEvent = function (event): boolean {
	const result = originalDispatchEvent.call(this, event);

	if(event.type === "click" && this.tagName === "BUTTON" && this.getAttribute("type") === "submit") {
		this.dispatchEvent(new Event("submit", { bubbles: true,
			cancelable: true }));
	}
	return result;
};
```

Works well with vitest!

**Comment by capricorn86** [comment]
This has finally been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.0.0

**Comment by capricorn86** [comment]
This has finally been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.0.1

**Comment by denniseffing** [comment]
@capricorn86 I think this issue still exists _if_ the submit button is not inside of the actual `<form></form>` tag using HTML5.

Check out the following reproducible sample: https://stackblitz.com/edit/vitejs-vite-zhgfzj?file=src%2FApp.jsx

Could you maybe take a look at this? ❤️

**Comment by mendrik** [comment]
it also doesn't work when the submit button has a onclick event attached.

**Comment by gustaff-weldon** [comment]
@capricorn86 I do not think this is fixed, we have tests for React where we have a Formik form and clicking on submit button with the below logic, works fine in jsdom, but does not in happy-dom, sadly: 
```
import userEvent from '@testing-library/user-event';

export const submitForm = async (container: HTMLElement, options?: { testId?: string }): Promise<void> => {
  const form = container.querySelector('form') || container.querySelector('[role="form"]');

  const selector = options && options.testId ? `[data-testid="${options.testId}"]` : '[type=submit]';
  const submitInput = form?.querySelector(selector);

  if (submitInput) {
    await userEvent.click(submitInput);
  }
};
```

**Comment by Justas-Lapiene** [comment]
Yall sure this is fixed? I'm still having issues.
