### ISSUE TITLE
TypeError: window.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by quantuminformation** [capricorn86/happy-dom#553]
I wonder if this might be missing too:
TypeError: window.XMLHttpRequest is not a constructor

**Comment by Mas0nShi** [comment]
Duplicate of #463 

Hi @quantuminformation, 
I'm working on this feature,  See: #520
Of course, welcome PR if you can help us to implement it.

**Comment by capricorn86** [comment]
Thanks for reporting @quantuminformation! 🙂 

We have now added support for XMLHttpRequest.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0
