### ISSUE TITLE
RequestAnimationFrame is called with fixed instead of current timestamp

### ISSUE THREAD

**Issue by c-wygoda** [capricorn86/happy-dom#554]
As stated in https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames:

> To run the animation frame callbacks for a [target object](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#concept-animationframeprovider-target-object) target with a timestamp now: [...]
> [Invoke](https://webidl.spec.whatwg.org/#invoke-a-callback-function) callback, passing now as the only argument, [...]

I understand that `now` is the current timestamp at time of execution of the callback and confirmed this in Chrome and Firefox.

**Comment by capricorn86** [comment]
Thanks for contributing @c-wygoda! 🙂 

There is a fix available in v7.0.2:
https://github.com/capricorn86/happy-dom/releases/tag/v7.0.2
