### ISSUE TITLE
Implement a node localName property

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#565]
I think that node.localName is equivalent node.tagName?.toLowerCase() but I might be wrong

**Comment by capricorn86** [comment]
Thanks for reporting @jgonte!

I believe that `Element.localName` is already supported or am I missing something? :sweat_smile:

**Comment by capricorn86** [comment]
I will close this as I can't reproduce. Please re-open if I missed something.

**Comment by jgonte** [comment]
Maybe I need to update the library

Thank you and glad to hear from you, I thought the project was dead
________________________________
