### ISSUE TITLE
URL constructor is missing 'base' option

### ISSUE THREAD

**Issue by silverwind** [capricorn86/happy-dom#569]
The URL constructor at https://github.com/capricorn86/happy-dom/blob/57a8d33d4b1ba3bdd4df0f7f8bc02e0d06bd8e9e/packages/happy-dom/src/location/URL.ts#L23 does not support the second form of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) constructor which takes a `base` url:

```
new URL(url)
new URL(url, base)
```

Quick test:

```js
# expected
> new URL('', 'https://example.com').pathname
'/'
# actual
> new URL('', 'https://example.com').pathname
''
```

**Comment by silverwind** [comment]
BTW I think the `URL` implementation could be sourced from https://github.com/jsdom/whatwg-url, which is pretty much the reference implementation.

**Comment by Mas0nShi** [comment]
Thank you for your feedback. `jsdom/whatwg-url`so slow because it follows the standard exactly. I think we can test with native module `node:url`. yes, I trying do it. 

#521 
https://github.com/capricorn86/happy-dom/pull/520#issuecomment-1172156327

**Comment by silverwind** [comment]
`node:url` is to my knowledge also a complete copy of `jsdom/whatwg-url`. If you want to marry happy-dom to node, it might be feasible to use that instead, but it's going to be equally "slow" :)

**Comment by Mas0nShi** [comment]
No, I disapprove you.
you can test the performance of both. 

my test unit.
```javascript 
const wg = require("whatwg-url");

console.time("whatwg-url");
for (let i = 0; i < 1000000; i++) {
	new wg.URL('', 'https://example.com');
}
console.timeEnd("whatwg-url");

console.time("node:url");
for (let i = 0; i < 1000000; i++) {
	new URL('', 'https://example.com');
}
console.timeEnd("node:url");
```

test parse 1 million times, `whatwg-url` needs about 11s but `node:url` only about 1s.

**Comment by silverwind** [comment]
Interesting, they must've done some additional optimizations not present in `jsdom/whatwg-url`.

**Comment by Mas0nShi** [comment]
Maybe. I don't  look closely, you can see the implementation of `node:url` at https://github.com/nodejs/node/blob/v18.7.0/lib/url.js

**Comment by silverwind** [comment]
It's in https://github.com/nodejs/node/blob/v18.7.0/lib/internal/url.js. Definitely contains various low-level optimizations. Maybe as a solution, you could check if running on node, use `node:url` there, otherwise fall back to `jsdom/whatwg-url`. That would make it compatibly with other JS runtimes as well, like Deno.

**Comment by hugo-dlb** [comment]
After a lot of debugging, I stumbled upon the same issue. In my case I was trying to replace jsdom by happydom for our tests but this is not possible because of this issue. MSW is relying on this constructor (and I'm sure many other librairies do): https://github.com/mswjs/interceptors/blob/main/src/utils/getUrlByRequestOptions.ts#L91

It would be awesome if happy-dom could add this. :)

**Comment by shayneo** [comment]
Found my way here via the vitest `0.25.1` issues. Any new thoughts on supporting the `new URL(url, base)` constructor? Would a PR be welcome?

**Comment by capricorn86** [comment]
Hi @shayneo! :slightly_smiling_face: 

Great that you want to contribute. However, I believe that me and @Mas0nShi are already working on a PR related to this, which should solve it.

We will remove the custom URL implementation and replace it with Nodes.

You can see the change here:
https://github.com/capricorn86/happy-dom/pull/520/files#diff-962b53d12390f23f537f3d9b4d96d382fc950b0d4e7464cfefcbf3450a72f0c5R43

**Comment by shayneo** [comment]
> Hi @shayneo! 🙂
> 
> Great that you want to contribute. However, I believe that me and @Mas0nShi are already working on a PR related to this, which should solve it.
> 
> We will remove the custom URL implementation and replace it with Nodes.
> 
> You can see the change here: https://github.com/capricorn86/happy-dom/pull/520/files#diff-962b53d12390f23f537f3d9b4d96d382fc950b0d4e7464cfefcbf3450a72f0c5R43

Thanks for the quick reply @capricorn86! Looks like this is well underway.

**Comment by capricorn86** [comment]
We have now fixed this by using the native `url` module 🙂 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0
