### ISSUE TITLE
Question: Register web components from third-party library in Window (VMContext)

### ISSUE THREAD

**Issue by joschne** [capricorn86/happy-dom#573]
Hi!

I'm considering happy-dom for server-side rendering of web components.

The [server-sider rendering example of the readme](https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom#server-side-rendering-of-web-components) defines a customElement (web component) directly in the script that is then parsed and evaluated by happy dom.

This is a good starting point but not really feasible when working with an existing web component library like [`@ionic/core`](https://www.npmjs.com/package/@ionic/core).

Is there a way to pass in the necessary third party code to VMContext of the happy-dom Window?

I imagine something like this:

```typescript
import { Window } from 'happy-dom';
import { defineCustomElement } from "@ionic/core/components/ion-badge.js";
import { initialize } from "@ionic/core/components";

const context = {
    initialize,
    defineCustomElement
}
const window = new Window(context); // <- add to VMContext

window.location.href = 'http://localhost:8080';

document.write(`
    <html>
        <head>
             <title>Test page</title>
        </head>
        <body>
            <div>
                <ion-badge color="secondary">Hello World</ion-badge>
            </div>
        </body>
        <script>

            // Initializes the Ionic config and mode behavior
            initialize();
            
            //  Defines the ion-badge web component
            defineCustomElement();
        
        </script>
    </html>
`);
```

**Comment by capricorn86** [comment]
I am hoping to soon have support for ES6 modules, which would make this a lot easier (#600 and #320).

Right now you will probably have to bundle the code before using it inside Happy DOM.

I see two alternatives:
1. If you have a server up and running for the website you can use Happy DOM as a proxy in front of it. The server should then deliver any Javascript code needed bundled. Then Happy DOM can load necessary resources from the server if you add script tags (e.g. `<script src="ionic_code.js"/>`)
2. You bundle all your code with Webpack (or similar) one time before the server rendering logic starts and add the code to a VM.Script. Then you can just add the VM.script to Happy DOM as it is a VM context.

Guide for compiling Webpack to memory:
https://errorsandanswers.com/compiling-webpack-in-memory-but-resolving-to-node_modules-on-disk/

Examples for VM.Script:
```javascript
import VM from 'node:vm';
import { Window } from 'happy-dom';

async function render(html: string, script: VM.Script): Promise<string> {
      const window = new Window(context);
      const document = window.document;
      
      // Runs the third party scripts in the Happy DOM virtual machine context
      script.runInContext(window);
      
      document.write(html);
      
      // Wait for any timeouts, fetch or other async tasks
      await window.happyDOM.whenAsyncComplete();
      
      // We need to add the <html> tag as only server side rendering with web components currently only support inner HTML
      return `<html>${document.documentElement.getInnerHTML({ includeShadowRoots: true })}</html>`;
}

// We only want to create the script once as we can re-use it between all renders
const script = new VM.Script(myThirdPartyCode);

const result = await render(`
    <html>
        <head>
             <title>Test page</title>
        </head>
        <body>
            <div>
                <ion-badge color="secondary">Hello World</ion-badge>
            </div>
        </body>
        <script>

            // Initializes the Ionic config and mode behavior
            initialize();
            
            //  Defines the ion-badge web component
            defineCustomElement();
        
        </script>
    </html>
`, script);

// Outputs the result
console.log(result);
```

**Comment by capricorn86** [comment]
I will close this now. Please re-open if you have further questions.

**Comment by joschne** [comment]
Thank you @capricorn86 for the detailed answer!
