### ISSUE TITLE
fetch with `Request` instance cause `TypeError: url.startsWith is not a function`

### ISSUE THREAD

**Issue by KoichiKiyokawa** [capricorn86/happy-dom#582]
cf) https://developer.mozilla.org/en-US/docs/Web/API/Request

```js
await fetch(new Request('https://jsonplaceholder.typicode.com/users')).then((r) => r.json())
```
This code causes an error of `TypeError: url.startsWith is not a function`.
The followings are error details.
```
 ❯ RelativeURL.getAbsoluteURL node_modules/happy-dom/lib/location/RelativeURL.js:14:17
 ❯ eval node_modules/happy-dom/lib/fetch/FetchHandler.js:26:61
 ❯ FetchHandler.fetch node_modules/happy-dom/lib/fetch/FetchHandler.js:24:16
 ❯ GlobalWindow.fetch node_modules/happy-dom/lib/window/Window.js:473:45
```

Thanks.

## Reproduction
https://stackblitz.com/edit/vitest-dev-vitest-vhbz3s?file=test%2Findex.test.ts&initialPath=__vitest__

**Comment by stefanhoelzl** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `happy-dom@7.5.10` for the project I'm working on.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/happy-dom/lib/window/Window.js b/node_modules/happy-dom/lib/window/Window.js
index 6b14a75..08f4034 100644
--- a/node_modules/happy-dom/lib/window/Window.js
+++ b/node_modules/happy-dom/lib/window/Window.js
@@ -513,6 +513,14 @@ class Window extends EventTarget_1.default {
      * @returns Promise.
      */
     async fetch(url, init) {
+        if (url.method !== undefined) {
+            init = {
+                method: url.method,
+                headers: Object.fromEntries(url.headers.entries()),
+                body: await url.arrayBuffer(),
+            };
+            url = url.url;
+        }
         return await FetchHandler_1.default.fetch(this.document, url, init);
     }
     /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

This is not a general solution but might be a starting point for a workaround until this issue is fixed!

**Comment by capricorn86** [comment]
Thanks for reporting @KoichiKiyokawa! 🙂 

Thanks a lot for contributing @stefanhoelzl! ⭐ 

@stefanhoelzl fix was added as part of this release:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0

**Comment by alkrauss48** [comment]
I received this error after upgrading to v15 (which as of this comment has been out less than 24 hours). Downgrading to v14 fixed it.

**Comment by PineappleAttack** [comment]
Same for me.

**Comment by rjfranco** [comment]
This issue seems to be present still in v15.11
