### ISSUE TITLE
support FormData 

### ISSUE THREAD

**Issue by wxhccc** [capricorn86/happy-dom#585]
would you want to add support for FormData?

**Comment by capricorn86** [comment]
Thanks for reporting @wxhccc! :slightly_smiling_face: 

I will look into adding support for FormData as soon as possible. There is some partial support for it already.

**Comment by ryanflorence** [comment]
We're running into trouble testing [Remix](https://remix.run) apps with happy-dom. Remix apps rely on it heavily, making it infeasible to recommend happy-dom for unit testing for our users, though we like it very much! Would love to see this get implemented :)

**Comment by MattBevis** [comment]
@capricorn86 any ideas on when this could be making its way into your beautiful repo?

**Comment by innocenzi** [comment]
I've stumbled upon this when using Vitest along with Happy DOM as well. How could one be of some help?

**Comment by capricorn86** [comment]
@innocenzi it is being implemented in #677, which should soon be done 🙂

**Comment by innocenzi** [comment]
Awesome! ❤️

**Comment by MattBevis** [comment]
@capricorn86 thank you so much! #Excited

**Comment by capricorn86** [comment]
Happy DOM now finally supports FormData.

Sorry that it took such a long time. Implementing the full API of FormData also meant that I had to implement fetch() into Happy DOM.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.0.0
