### ISSUE TITLE
Various <select>/<option> issues

### ISSUE THREAD

**Issue by IGx89** [capricorn86/happy-dom#618]
Discovered a number of issues with the behavior of select's and option's:

1. Setting HTMLSelectElement.value doesn't ever work (never updates selected index). This breaks v-model updates in Vue.
2. Setting HTMLSelectElement.selectedIndex to -1 doesn't unselect any/all options
3. Setting HTMLSelectElement.selectedIndex doesn't update `selected` attributes on option nodes
4. Getting HTMLSelectElement.selectedIndex initially is always -1, even if there's an `<option selected>` present in the initial HTML
5. HTMLSelectElement.options doesn't reflect DOM updates when option nodes are added/removed (such as when a `v-for` on an `<option>` in Vue re-runs)

I will be submitting a PR shortly to resolve these issues.

**Comment by capricorn86** [comment]
Thanks again for your contribution @IGx89! :slightly_smiling_face: 

You can read more about the releases here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.12
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.11

**Comment by IGx89** [comment]
Thanks for your help with the PR and reviewing and merging it so quickly! Brings the number of failing tests on one of my projects from ~400 down to ~100 when using happy-dom -- getting a lot closer :)
