### ISSUE TITLE
TypeError in window constructor

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#627]
**Describe the bug**

```javascript
const { Window } = require('happy-dom');

const window = new Window({
    innerWidth: 1024,
    innerHeight: 768,
    url: 'http://localhost:8080',
});

console.log(window);
/*
            this.location.href = options.url;
                               ^

TypeError: Cannot set properties of undefined (setting 'href')
*/
```

**Comment by Mas0nShi** [comment]
I don't know why we didn't test this in `Window.test.ts` ?

**Comment by jledentu** [comment]
Weird. TypeScript generates the `Window` constructor like this:

```ts
constructor(options) {
        super();
        this.innerWidth = options?.innerWidth ? options.innerWidth : 0;
        this.innerHeight = options?.innerHeight ? options.innerHeight : 0;
        if (options?.url) {
            this.location.href = options.url;
        }

        // ...

        this.location = new Location_1.default();
}
```

So `this.location` is not yet initialized when calling `this.location.href = options.url;`. I don't know why TypeScript handles the class field initializers like that, but I'd suggest to move the initialization of `location` in the `constructor`.

**Comment by Mas0nShi** [comment]
Yes, I think so. submit a PR if you're ready.

**Comment by capricorn86** [comment]
Thanks for reporting @Mas0nShi! :slightly_smiling_face: 

I guess I missed adding a unit test for it. Weird behavior by Typescript, it is not really expected.

Big thanks to @jledentu for you contribution! :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.6.1
