### ISSUE TITLE
getElementByTagName doesn't support wildcard searches

### ISSUE THREAD

**Issue by IGx89** [capricorn86/happy-dom#633]
getElementByTagName can be passed a special string `"*"` representing all elements ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName#parameters)), causing it to return all elements. That currently doesn't work.

jQuery relies on that functionality for non-trivial selector searches, so without this functionality jQuery support is partially broken. For example, `$('[attr]')` doesn't work.

**Comment by capricorn86** [comment]
Thanks for your contribution @IGx89! :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.6.2
