### ISSUE TITLE
Replace sync-request with sync-fetch

### ISSUE THREAD

**Issue by ypconstante** [capricorn86/happy-dom#650]
**Is your feature request related to a problem? Please describe.**
Today happy-dom uses sync-request to handle situations were a synchronous request is necessary, but this library isn't maintained anymore (last release was 4 years ago), and requires a lot of packages not used by happy-dom or it's dependencies.

**Describe the solution you'd like**
Migrate to [sync-fetch](https://www.npmjs.com/package/sync-fetch), which is an actively maintained library that uses node-fetch, like happy-dom, which should help reduce happy-dom install size by 3Mb

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by capricorn86** [comment]
Thank you for reporting @ypconstante! :slightly_smiling_face: 

Me and @Mas0nShi are working on a fix for this in a related PR:
https://github.com/capricorn86/happy-dom/pull/520/files#diff-532eacee8d4b349453e921fd5fdbd2d2f191868e1242b03a27f9f6365be7fe1fL36

We will replace sync-request with a very minimal custom solution.

**Comment by capricorn86** [comment]
Related to #463

**Comment by capricorn86** [comment]
We have now fixed this by replacing "sync-request" with a custom solution.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0

**Comment by capricorn86** [comment]
Re-opening as I just noticed that the dependency in package.json is still there.
