### ISSUE TITLE
`document.referrer` should be a string

### ISSUE THREAD

**Issue by cloud-walker** [capricorn86/happy-dom#653]
**Describe the bug**
[document.referrer](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer), should be a present by specification (an empty string by default I guess)

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-xbr6ap?file=test/happydom.test.ts

**Expected behavior**
https://stackblitz.com/edit/vitest-dev-vitest-xbr6ap?file=test/jsdom.test.ts

**Comment by capricorn86** [comment]
Thank you for reporting @cloud-walker! :slightly_smiling_face: 

Sorry for taking such a long time before answering this.

There is a fix for it now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.1.2
