### ISSUE TITLE
Node.isEqualNode()

### ISSUE THREAD

**Issue by jujurocket** [capricorn86/happy-dom#656]
**Is your feature request related to a problem? Please describe.**
I wanted to compare two happy-dom nodes in my tests, however the library does not implement the standard
[Node.isEqualNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode) browser method.

Instead I noticed there is a static function (`nodeEquals`) that implements this functionality in `NodeUtility`.

The issue is I did not realise this functionality was available  in the library until I dug through the source 
code, and I had to do this import in order to use it:
```js
import NodeUtility from "happy-dom/lib/nodes/node/NodeUtility"
```

**Describe the solution you'd like**
I was wondering if there was some design choice behind this that I haven't considered, or whether it
would be possible to add the method to the `INode` type, the same way it works in browsers?

**Additional context**
I am actually using happy-dom to test a web framework I am developing, and it involves comparing
generated HTML trees, hence the above.

The official implementation makes this tricky sometimes because of [whitespace between nodes](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace). I have
actually implemented a wrapper function around `nodeEquals` which first strips the two node trees of
any text nodes only containing whitespace. This makes comparison between two node trees more
meaningful in a test environment for generated HTML.

I'm not sure if the above function would have any use in `NodeUtilities` as well?

---

Happy to put in a pull request if any of the above seems desirable.

**Comment by gangsthub** [comment]
The method in the Node interface according to spec is `isEqualNode`:

- https://dom.spec.whatwg.org/#ref-for-dom-node-isequalnode

There's also `isSameNode`. `nodeEquals` does not exist in the spec, at least at the moment. 🤔

**Comment by capricorn86** [comment]
Thanks for your contribution @gangsthub! :slightly_smiling_face: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.0
