### ISSUE TITLE
Node.normalize() not implemented

### ISSUE THREAD

**Issue by WebMechanic** [capricorn86/happy-dom#658]
The Node interface should have a `normalize()` method.  
_"In a normalized sub-tree, no text nodes in the sub-tree are empty and there are no adjacent text nodes."_ (MDN)

In essence, a mess like
```html
<p>Foo 
    </p>
<p>
  Bar</p>
```
becomes
```html
<p>Foo</p><p>Bar</p>
```

Normalized sub-trees simplify DOM traversal and also using XPath queries (with other libraries) and traversing XPathResults.

**Describe the solution you'd like**
Please implement `Node.normalize()`

**Describe alternatives you've considered**
Traverse an element's `.childNodes`, check if the child's `.nodeType` === `Node.TEXT_NODE`. If so concatenate with `.nextSibling.nodeValue` if also a `Node.TEXT_NODE` then trim `textContent`, remove that `.nextSibling` from `parentElement`, continue until no more text nodes. 
This should leave other node types like comments intact.
😅

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize
https://dom.spec.whatwg.org/#ref-for-dom-node-normalize①

Thank you

**Comment by danielrentz** [comment]
Duplicate to #300

Please note that `Node.normalize` does *not* trim the text contents (check the example in the MDN docs).
