### ISSUE TITLE
MutationObserver disconnect fails if no elements are observed

### ISSUE THREAD

**Issue by spudly** [capricorn86/happy-dom#659]
**Describe the bug**
If you call `disconnect()` on a MutationObserver instance that is not yet observing any elements, it will fail with this error: `TypeError: Cannot read properties of null (reading '_unobserve')`

**To Reproduce**

```js
import {Window} from 'happy-dom';

const window = new Window();

const observer = new window.MutationObserver(() => {});
observer.disconnect();
```

**Expected behavior**

No error

**Screenshots**

n/a

**Device:**
 - OS: MacOS
 - Browser: N/A (NodeJS / Jest / @happy-dom/jest-environment)

**Additional context**

The bug is here: https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/mutation-observer/MutationObserver.ts#L58

`this.target` is null until observe() is called, so if you call disconnect before that, it throws the error. I think it should probably be looping over a list (WeakSet?) of observed elements and calling `_unobserve` on each one.

**Comment by capricorn86** [comment]
Thank you for reporting @spudly! :slightly_smiling_face: 

Big thanks to @victorwedo for making a fix! :star: 

The fix has now been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.2
