### ISSUE TITLE
ReferenceError: HTMLSelectElement is not defined

### ISSUE THREAD

**Issue by RettentoRectangle** [capricorn86/happy-dom#664]
**Describe the bug**
HTMLSelectElement import is missing from index.ts

**To Reproduce**
const el = document.createElement('select')

const isSelect = el instanceof HTMLSelectElement // <- ReferenceError: HTMLSelectElement is not defined

**Expected behavior**
HTMLSelectElement is part of the globals

**Additional context**
Switching from JSDOM to happy-dom

**Comment by capricorn86** [comment]
Re-opening. Wrong import.

**Comment by capricorn86** [comment]
Sorry for taking so long @RettentoRectangle! :sweat_smile: 

It has finally been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.1.1
