### ISSUE TITLE
Declarative ShadowDOM does not work as shown in Docs

### ISSUE THREAD

**Issue by rossanmol** [capricorn86/happy-dom#668]
**Describe the bug**
I have copied the code written in your [Docs](https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom#server-side-rendering-of-web-components), in Node 14/16/18. And the output was:

```
                <my-custom-element><template shadowroot="open">
                            <style>
                                :host {
                                    display: inline-block;
                                    background: red;
                                }
                            </style>
                            <div><slot></slot></div>
                        </template></my-custom-element>

```

**To Reproduce**
1. Copy code from [Docs](https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom#server-side-rendering-of-web-components)
2. Execute code in node (14/16/18)
3. Notice the output in console

**Expected behavior**
```
<my-custom-element>
    <span>Slotted content</span>
    <template shadowroot="open">
        <style>
            :host {
                display: inline-block;
                background: red;
            }
        </style>
        <div><slot></slot></div>
    </template>
</my-custom-element>
```

**Screenshots**
<img width="479" alt="image" src="https://user-images.githubusercontent.com/18351988/204753251-1e4399c6-9d43-44d2-bb9a-3b1d176245ce.png">

**Device:**
 - OS: MacOS Monterey 12.6
 - Browser Node
 - Version 14/16/18

**Comment by Heydon** [comment]
@rossanmol Thanks for posting this. I have exactly the same experience. The light DOM (`<span>Slotted content</span>`) is not preserved in any of my cases either.

**Comment by capricorn86** [comment]
Thank you for reporting @rossanmol and @Heydon! :slightly_smiling_face: 

The issue has finally been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.20.3
