### ISSUE TITLE
Import typo

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#680]
Import typo at 

https://github.com/capricorn86/happy-dom/blob/c9f5af0bef96ee28c77a28fe9378675614418a4d/packages/happy-dom/src/window/Window.ts#L17

**Comment by capricorn86** [comment]
Thanks for reporting @Mas0nShi! :slightly_smiling_face: 

I found the same issue and fixed it in my ongoing PR.

**Comment by capricorn86** [comment]
It has now been fixed :slightly_smiling_face:
