### ISSUE TITLE
Pollyfill MessageEvent since Node doesn't initialize properties per the spec.

### ISSUE THREAD

**Issue by kalvenschraut** [capricorn86/happy-dom#682]
See my issue over on [vitest ](https://github.com/vitest-dev/vitest/issues/2543)

I could do a PR if all that would be done is what I did in its description.

**Comment by capricorn86** [comment]
Thanks for reporting @kalvenschraut! :slightly_smiling_face: 

`MessageEvent` has never been implemented.

You are very welcome to implement it. All contributions are welcome.

The events are available here and you should find many example of how they are implemented there:
https://github.com/capricorn86/happy-dom/tree/master/packages/happy-dom/src/event/events

**Comment by kalvenschraut** [comment]
Can I extend the global MessageEvent and add the messing functionality. Node doesn't do anything with the second parameter like it is suppose to per the spec. Can see what I am doing currently locally from the vitest issue.

**Comment by capricorn86** [comment]
@kalvenschraut the events in the browsers are expected to inherit from the Event, and it is not possible to extend two classes. Also, I believe they would have different purposes as the MessageEvent is meant for very browser specific functionality.

Do you have any documentation for the Node.js MessageEvent? Because I can't find it.

**Comment by kalvenschraut** [comment]
As far as I understood it, node is attempting to make MessageEvent available to behave like browser contexts, but it is missing the functionality that vitest is trying to use in their web worker package.

https://nodejs.org/api/globals.html#messageevent is the only documentation  I can find.

Vlad at vitest talked that they could look at adding this themselves [here](https://github.com/vitest-dev/vitest/issues/2543#issuecomment-1360933630)

**Comment by capricorn86** [comment]
I think it is safest to implement this in Happy DOM without extending the NodeJS class to ensure that it will be compatible with the rest of the DOM functionality.

Example:
```javascript
import Event from '../Event';
import IMessageEventInit from './IMessageEventInit';

export default class MessageEvent extends Event {
	public readonly data: string | null = null;
	...

	/**
	 * Constructor.
	 *
	 * @param type Event type.
	 * @param [eventInit] Event init.
	 */
	constructor(type: string, eventInit?: IMessageEventInit) {
		super(type, eventInit);
		this.data = eventInit?.data || null;

               ...
	}
}
```

**Comment by capricorn86** [comment]
By implementing this:
https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent

**Comment by kalvenschraut** [comment]
Apparently I was mistaken and Node's MessageEvent does work just fine as vlad reported and I just double checked.

![image](https://user-images.githubusercontent.com/30308012/209369620-3ac27f08-69bc-4b74-8fd7-d934c74a4e52.png)


The linked vitest issue only occurs with happy dom. No idea how happy-dom could be affecting this issue though.

**Comment by capricorn86** [comment]
It's probably because it has not been implemented in Happy DOM yet.

**Comment by kalvenschraut** [comment]
I guess I don't understand, if it hasn't been implemented in happy-dom then it should just fall back to Node's implementation?

[happy-dom stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-xkbczb?file=package.json,test%2Fsuite.test.ts,vite.config.ts&initialPath=__vitest)

[node stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-revwkn?file=package.json,test%2Fsuite.test.ts,vite.config.ts&initialPath=__vitest)

**Comment by kalvenschraut** [comment]
After looking into node's implementation a little bit more, they are defining those getters on the prototype specifically.  Would happy dom the doing anything to overwrite the prototype to an empty object?

In node REPL
![image](https://user-images.githubusercontent.com/30308012/209380643-bfb98a9e-4f44-4417-8c0e-dedfb52db102.png)

Then console.log'ing the prototype in happy-dom + vitest
![image](https://user-images.githubusercontent.com/30308012/209380913-a68e6870-b292-4b9e-801b-b96a2e9c66ed.png)
![image](https://user-images.githubusercontent.com/30308012/209380967-215d000a-df3d-4d5d-ac63-e76f67621524.png)

**Comment by capricorn86** [comment]
@kalvenschraut I have made a fix which adds support for `HTMLIframeElement`, `MessageEvent` and `Window.postMessage()`. This should hopefully solve your issue :slightly_smiling_face: 

I have also added the logo for RTVision :partying_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/issues/682
