### ISSUE TITLE
QuerySelector : infinite loop when there is no number before `n`

### ISSUE THREAD

**Issue by takaya1992** [capricorn86/happy-dom#686]
**Describe the bug**

infinite loop when there is no number before `n` on `nth-child`

for example: `:nth-cihld(n+2)`

**To Reproduce**

```js
window = new Window();
document = window.document;
const container = document.createElement('div');
container.innerHTML = `
  <div>
    <span>a</span>
    <span>b</span>
    <span>c</span>
  </div>
`;
const elements = container.querySelectorAll(':nth-child(n+2)'); // inifinite loop
// Expected : [ '<span>b</span>', '<span>c</span>' ]
```

**Expected behavior**

return the expected value without going into an infinite loop

**Comment by capricorn86** [comment]
Thank you for your contribution @takaya1992! :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.1.3
