### ISSUE TITLE
Element TEXTAREA does not implement "select" (happy-dom + testing-library/user-event)

### ISSUE THREAD

**Issue by sahibalejandro** [capricorn86/happy-dom#691]
This error message is thrown by `@testing-library` when using `@testing-library/user-event` along with `happy-dom`. Issue does not happen with `jsdom`.

I've found that the issue could be due to `happy-dom`'s `HTMLTextAreaElement` does not provide the `select` implementation, which is used by `@testin-library/user-event` `type()` utility API to simulate the user's input.

`@testing-library/user-event` is trying to prepare the `select` "interceptor" for `HTMLInputElement` and `HTMLTextAreaElement`, here is the call stack where it's happening: 
* https://github.com/testing-library/user-event/blob/main/src/document/prepareDocument.ts#L71
* https://github.com/testing-library/user-event/blob/main/src/document/interceptor.ts#L183
* https://github.com/testing-library/user-event/blob/main/src/document/interceptor.ts#L60

I'm reporting the bug here instead of `@testing-library/user-event` repostitory because if I switch from `happy-dom` to `jsdom` the issue is not present, that's why I think this is related to `happy-dom` `HTMLTextAreaElement` implementation.

**To Reproduce**
Using `happy-dom` as a DOM environment for testing and having a Vue component like this:
```vue
<template>
  <textarea data-testid="textarea" />
</template>
```

And a test like this:
```javascript
import { render } from '@testing-library/vue';
import userEvent from '@testing-library/user-event';

import TextareaComponent from 'TextareaComponent.vue';

describe('TextareaComponent', () => {
  it('updates textarea value', async () => {
    const user = userEvent.setup();
    const component = render(TextareaComponent);
    const textarea = component.getByTestId('textarea');

    await user.type(textarea, 'foo bar'); // The error is thrown at this point.
  });
});
```

**Expected behavior**
The textarea value is updated correctly without any errors.

**Screenshots**
![Screen Shot 2023-01-14 at 13 33 52](https://user-images.githubusercontent.com/985268/212492938-934ccbbb-f188-4ced-9866-911e8f408cfe.png)

**Device:**
N/A

**Additional context**
I'm running the tests on:
* MacOS `v12.6`
* NodeJS `v16.16.0`
* Package Manager: PNPM `v7.25.0`
* testing-library/user-event `v14.4.3`
* testing-library/vue `v6.6.1_vue@3.2.45`

**Comment by MiroslavPetrik** [comment]
I have the same issue. I wanted to check it has a focus after clicking it's label.

```ts
    expect(screen.getByRole("textbox")).toHaveFocus();
  // Error: Element TEXTAREA does not implement "select".

```

**Comment by capricorn86** [comment]
Thank you for reporting @sahibalejandro! :slightly_smiling_face: 

There is a fix in.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.1.0

**Comment by sahibalejandro** [comment]
@capricorn86 thank you for the fix!
