### ISSUE TITLE
Jest 29 not supported by jest-environment

### ISSUE THREAD

**Issue by ahuth** [capricorn86/happy-dom#697]
**Describe the bug**

@happy-dom/jest-environment uses v27 of various jest packages.

When using in an app that has jest v29, tests fail with:

```
TypeError: Cannot read properties of undefined (reading 'bind')

      at Runtime._createJestObjectFor (node_modules/jest-runtime/build/index.js:2099:64)
```

The [referenced line in jest-runtime](https://github.com/facebook/jest/blob/9fa2a463a0d5b1a7763ef4a28004db082b8bcf6e/packages/jest-runtime/src/index.ts#L2322) accesses `moduleMocker.replaceProperty`, which doesn't exist on @happy-dom/jest-environment's jest-mock v27.

Updating jest-mock (and the other jest deps) in @happy-dom/jest-environment to v29 fixes this issue for me, and I'll submit a PR making that update.

**To Reproduce**
1. Create or clone an app using Jest v27 and @happy-dom/jest-environment (such as https://github.com/chanzuckerberg/edu-stack).
2. Run tests, which are green.
3. Upgrade Jest to v29.
4. Run tests, which are red.

**Expected behavior**
@happy-dom/jest-environment works in Jest v29.

**Comment by capricorn86** [comment]
Thank you for your contribution @ahuth! :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.1

**Comment by ahuth** [comment]
Thanks!
