### ISSUE TITLE
SVGElement missing focus method

### ISSUE THREAD

**Issue by Codex-** [capricorn86/happy-dom#699]
**Describe the bug**
Currently if you trigger a focus call to an `SVGElement` while using `happy-dom` as the environment (i.e. in vitest or jest), it throws as `focus` is not defined.

**To Reproduce**
Small test reproduction:
```ts
import { render, screen } from '@testing-library/react'
import React from 'react'

test('', () => {
  render(
    <>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" data-testid="icon">
        <path d="M0 0h24v24H0z" fill="none" />
        <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z" />
      </svg>
    </>
  )

  const icon = screen.getByTestId('icon')
  icon.focus()
})
```

**Expected behavior**
focus to be defined

**Additional context**
Upon investigating further, it appears that the focus method is defined on the `IHTMLElement` interface:
[`IHTMLElement`](https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/nodes/html-element/IHTMLElement.ts#L63-L66)
```ts
	/**
	 * Triggers a focus event.
	 */
	focus(): void;
```

But the dom typings from typescript indicate that this method, amongst some others, is common between both HTML and SVG Elements: https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L7727
```ts
interface HTMLOrSVGElement {
    autofocus: boolean;
    readonly dataset: DOMStringMap;
    nonce?: string;
    tabIndex: number;
    blur(): void;
    focus(options?: FocusOptions): void;
}
```

Should the existing implementation of `focus` be moved so it is available to both base implementations for the other children to inherit?

While the MDN is very clear on [`HTMLElement` providing `focus` as an instance method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#parameters), it's less clear on it being available on `SVGElement`, but does show `focus` in the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement#browser_compatibility).

I threw together a quick jsfiddle just to validate that `focus` does actually exist: https://jsfiddle.net/sohewjpg/

Would be great to hear your thoughts 🤔

**Comment by gibbok** [comment]
Hi, we have a similar issue using: 

```
import userEvent from '@testing-library/user-event';

userEvent.click(...)
```

which underneath focus on the element selected.

Could anyone provide some support?

**Comment by gibbok** [comment]
@Codex- Hi, have you find peraphs a workaround on this bug? Thanks

**Comment by Codex-** [comment]
> @Codex- Hi, have you find peraphs a workaround on this bug? Thanks

Unfortunately not, opted to continue using jsdom for now 😔

**Comment by nilscox** [comment]
Here is a quick workaround:
```ts
for (const element of document.getElementsByTagName('svg')) {
  element.focus = () => {}
}
```

**Comment by gibbok** [comment]
Thanks, I also find another work around by using:

`fireEvent.click()` which does not focus the DOM element by default like `userEvent.click()` does.

**Comment by capricorn86** [comment]
Thanks for reporting @Codex-, @gibbok and @nilscox! :slightly_smiling_face: 

We finally have a fix for this.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.9.0

**Comment by capricorn86** [comment]
@Codex- I considered creating an HTMLOrSVGElement class for this, but chose to just extract the focus() and blur() methods to a utility instead as this is what how the spec has defined it. An HTMLOrSVGElement class could be confusing as it indicates that it should be an element part of the DOM if we would put it in the nodes catalog.

**Comment by Codex-** [comment]
You're a legend, thanks heaps, @capricorn86 :) 

I'll give it a test this week coming (hopefully)
