### ISSUE TITLE
CustomEvent does not take falsy detail value

### ISSUE THREAD

**Issue by CSchulz** [capricorn86/happy-dom#701]
**Describe the bug**

**To Reproduce**
1. Create a CustomEvent `new CustomEvent(eventName, { detail: undefined })`
2. Wondering why `detail` is null
![image](https://user-images.githubusercontent.com/1520593/214897798-c2e82aaf-8776-4640-9493-67ec1d06d829.png)

**Expected behavior**
The `detail` value should return the given input `detail` value.

**Device:**
 - Version happy-dom@8.1.5

**Additional context**
Wrong handling of `detail` with falsy check:
https://github.com/capricorn86/happy-dom/blob/4c7ed339323f993d8e1c01c204d524594da15c1c/packages/happy-dom/src/event/events/CustomEvent.ts#L19-L22

**Comment by CSchulz** [comment]
@capricorn86 Did you forget my patch? It seems not to be merged into master.

**Comment by capricorn86** [comment]
Hi @CSchulz! :slightly_smiling_face: 

I'm sorry, it seems like I made a mistake when merging your pull request and just closed it instead :man_facepalming: Not sure how it happened.

It has been merged now and will be released any moment.

**Comment by capricorn86** [comment]
It has been released now:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.4

Thanks again for your contribution! :star2:
