### ISSUE TITLE
setTimeout / setInterval does not pass arguments to callback

### ISSUE THREAD

**Issue by CSchulz** [capricorn86/happy-dom#712]
**Describe the bug**
Arguments to callback function of setTimeout or setInterval doesn't receivce arguments.

**To Reproduce**
Execute in browser:
```
const callback = (message) => {console.log(message)};
setTimeout(callback, 0, 'hello');

VM154:1 hello
```

Execute in happy-dom:
```
const callback = (message) => {console.log(message)};
setTimeout(callback, 0, 'hello');

VM154:1 undefined
```

**Expected behavior**
Should print hello as the browser.

**Screenshots**

**Device:**
 - Version 8.2.3

**Comment by capricorn86** [comment]
Thanks for your contribution @CSchulz! :slightly_smiling_face: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.2.5
