### ISSUE TITLE
toggleAttribute is not a function

### ISSUE THREAD

**Issue by alexbot89** [capricorn86/happy-dom#724]
**Describe the bug**
When attempting to access function `toggleAttribute` after `.querySelector`, an error is displayed:

```
container.toggleAttribute('disabled');
          ^

TypeError: container.toggleAttribute is not a function
    at file:///D:/Projects/happ-dom-repro1/index.js:9:11
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.0
```

According to MDN, this function should be supported:
https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute

**To Reproduce**
Run this code with `node index.js` after basing it off the basic example:

```js
import { Window } from 'happy-dom';

const window = new Window();
const document = window.document;

document.body.innerHTML = '<div class="container"></div>';

const container = document.querySelector('.container');
container.toggleAttribute('disabled');
```

**Expected behavior**
Attributes should be toggle on/off as expected of the spec from MDN.

**Device:**
 - OS: Windows 11

**Comment by capricorn86** [comment]
Thanks for reporting @alexbot89! :slightly_smiling_face: 

Big thanks to @btea for the contribution!

The fix has now been released.

You can read more about it here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.4.0
