### ISSUE TITLE
HTMLInput `valueAsNumber` with value = 0 returns NaN

### ISSUE THREAD

**Issue by MiroslavPetrik** [capricorn86/happy-dom#729]
**Describe the bug**
Changing input value to 0 (number literal), and reading it back with `valueAsNumber` returns `NaN`.

**To Reproduce**
```ts
// 1. test code
await fireEvent.change(input, { target: { value: 10 } }); // note passing number literal, not 'stringy-number' "10"

// 2. app code
const {value, valueAsNumber} = event.target
console.log({value, valueAsNumber}); // {value: 10, valuesAsNumber: 10}

// 3. test code
await fireEvent.change(input, { target: { value: 0 } });

// 4. app code
console.log({value, valueAsNumber}); // {value: 0, valuesAsNumber: NaN}
```

**Expected behavior**
For input value 0, the `valueAsNumber` should return 0.

**Additional context**
As workarround, I set the string value in test instead:

```ts
await fireEvent.change(input, { target: { value: "0" } });
console.log({value, valueAsNumber}); // {value: "0", valuesAsNumber: 0}
```

- the `valueAsDate` should similarly work with 0

**Comment by btea** [comment]
Maybe the code should be adjusted to: 
```ts
return parseFloat(this.value);
```
https://github.com/capricorn86/happy-dom/blob/47dada890fcb5a37c0ba18e3f5a3837bd9cfe59a/packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts#L778

**Comment by btea** [comment]
@MiroslavPetrik Hello, regarding the `fireEvent` in the code you provided, I did a global search and couldn't find it. Can you tell me how it came about?

**Comment by MiroslavPetrik** [comment]
> @MiroslavPetrik Hello, regarding the `fireEvent` in the code you provided, I did a global search and couldn't find it. Can you elaborate on this usage scenario?

that is example from my codebase. https://github.com/MiroslavPetrik/form-atoms-field/commit/aab44813034d020ed7008d8d16129416bc241de6#diff-10a9941191519d185e1921cf27111ad8e4dd0522fd591f11857ec42035a13818R55

It points out that there is number literal -- I was not sure, whether its not bug to just fire event with number value, e.g. even real browsers have string values on number inputs...

put other way, the `fireEvent.change` could be typed to accept only strings...

**Comment by btea** [comment]
The value of input seems to only accept strings
https://github.com/capricorn86/happy-dom/blob/2ea8d39aa5dca86018161eb954d69b2ef04523de/packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts#L598
However, if the input type is number, should it also accept number type values? 😕

**Comment by MiroslavPetrik** [comment]
![image](https://user-images.githubusercontent.com/38855190/218506401-61e8fbee-e816-4f86-b632-df6576c13d76.png)

from the DOM, the value is always `string`, react accepts value of number type, but it gets converted by the DOM eventually

![image](https://user-images.githubusercontent.com/38855190/218506735-e8fa8095-f90a-4924-a6cb-7c01a91ecbf8.png)

**Comment by btea** [comment]
Ok, I get it, so it's not a bug.

**Comment by MiroslavPetrik** [comment]
It certainly is a pitfall. Maybe not bug in strict sense with regards to html spec.

I would still fix it, my reasons:
1. as I can set input value to number without warning, I should be able to do so in tests with firing events having number value.
2. jsdom works in both scenarios, e.g. when I set `"0"` or `0`.  [their implementation parses value right away](https://github.com/jsdom/jsdom/blob/59a8af3288a7ee7a00f4af910644a6c1c9c76f90/lib/jsdom/living/nodes/HTMLInputElement-impl.js#L474)
3. it will be more user friendly to have this covered.

**Comment by btea** [comment]
Agree, type judgment is performed when setting the value, or the value is converted to a string by default.

**Comment by MiroslavPetrik** [comment]
Just installed and it works. Thanks.
