### ISSUE TITLE
`:not()` pseudo class doesn't consider element type

### ISSUE THREAD

**Issue by romansp** [capricorn86/happy-dom#753]
**Describe the bug**
`:not(element)` selector doesn't consider provided element type when matching nodes.

**To Reproduce**
The following reproduction test is currently failing in happy-dom.
```js
it('Returns all elements matching "[tabindex]:not(textarea)".', () => {
  document.body.innerHTML = `
    <div tabindex="-1"></div>
    <div tabindex="0"></div>
    <div tabindex="1"></div>
    <textarea tabindex="-1"></textarea>
  `;
  const elements = document.querySelectorAll('[tabindex]:not(textarea)');
  
  expect(elements.length).toBe(3);   // but actual is 0
});
```

**Expected behavior**
`:not()` pseudo class selector should properly match elements that do not match provided element type selector.

**Comment by capricorn86** [comment]
Thanks for reporting @romansp! :slightly_smiling_face: 

Big thanks to @btea for contributing with a fix :star2: 

The fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.4.3
