### ISSUE TITLE
Chakra UI Incompatability

### ISSUE THREAD

**Issue by jankowiakdj-recharge** [capricorn86/happy-dom#757]
**Describe the bug**
When using Happy DOM as the test environment with certain Chakra UI components the error `TypeError: i.node.isSameNode is not a function` is being thrown. Related to this line in the chakra code https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/descendant/src/descendant.ts#L109 

Running the Chakra test suite with Happy DOM results in:
```
Test Suites: 18 failed, 92 passed, 110 total
Tests:       85 failed, 2 skipped, 949 passed, 1036 total
```

**To Reproduce**
1. Clone https://github.com/jankowiakdj-recharge/chakra-ui/tree/happy-dom
2. `pnpm install`
3. `pnpm test`
4. See errors

**Expected behavior**
Chakra test suite passes as it does with jsdom

**Comment by sam-sbl** [comment]
I hit the exact same issue - I added the following code to my test setup file for a quick workaround. It seems to do the job for now:
```
Node.prototype.isSameNode = function(otherNode) {
    return otherNode === null ? false : this === otherNode
}
```

**Comment by capricorn86** [comment]
Thank you for reporting @jankowiakdj-recharge and @sam-sbl! :slightly_smiling_face: 

A fix has been released:
https://github.com/capricorn86/happy-dom/releases/tag/v10.9.0
