### ISSUE TITLE
Spurious HTML comments in embedded scripts

### ISSUE THREAD

**Issue by fcapolini** [capricorn86/happy-dom#759]
**Describe the bug**

The content of `<script>` and `<style>` tags is parsed with the same logic used for all other tags, which considers `<!--`, `<!` and `<?` as HTML comment markers.

Because of that this fragment from [highlight.js](https://github.com/highlightjs):

```javascript
{className:"meta",begin:/<![a-z]/,end:/>/,contains:[t,i,l,c]}
```

is erroneously parsed and is then serialized as:

```javascript
{className:"meta",begin:/<!--[a-z]/,end:/-->/,contains:[t,i,l,c]}
```

which breaks the script.

**To Reproduce**

```typescript
	const window = new Window({
		settings: {
			disableJavaScriptFileLoading: true,
			disableJavaScriptEvaluation: true,
			disableCSSFileLoading: true,
			enableFileSystemHttpRequests: false
		}
	});
	const domParser = new window.DOMParser();

	const newDocument = domParser.parseFromString(
		`<html>
			<body>
				<script>
					var test = {className:"meta",begin:/<![a-z]/,end:/>/,contains:[t,i,l,c]};
				</script>
			</body>
		</html>`,
		'text/html'
	);

	const output = new XMLSerializer().serializeToString(newDocument);
	// Spurious comment `<!--[a-z]/,end:/-->` appears in output markup
```

**Expected behavior**

In the test code above, the output should preserve the original JS code.

**Comment by capricorn86** [comment]
Thanks again for your contribution @fcapolini! :star:

**Comment by fcapolini** [comment]
Perfect, thanks to you! Super quick 💯
