### ISSUE TITLE
Cannot log after tests are done. Did you forget to wait for something async in your test?

### ISSUE THREAD

**Issue by moltar** [capricorn86/happy-dom#773]
**Describe the bug**

Getting an error in the console:

> Cannot log after tests are done. Did you forget to wait for something async in your test?

Yet all of the tests pass.

And the stack trace does not point to any specific tests.

**To Reproduce**

Not sure.

**Expected behavior**

Produce no error.

**Screenshots**

![screenshot-20230222T121233-g7L1LN2d@2x](https://user-images.githubusercontent.com/491247/220616861-5febeb16-dda0-45f0-b81b-95a3cb182432.png)

**Device:**
 - OS: macOS, linux
 - Browser: N/A
 - Version: 8.7.1

**Additional context**

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Error: Failed to complete fetch request. Task was canceled.
        at /.../node_modules/happy-dom/src/fetch/FetchHandler.ts:70:12
        at processTicksAndRejections (node:internal/process/task_queues:96:5)".

      at node_modules/happy-dom/src/fetch/FetchHandler.ts:70:12
      at processTicksAndRejections (node:internal/process/task_queues:96:5)".
      at console.error (node_modules/@jest/console/build/BufferedConsole.js:127:10)
      at onError (node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts:194:58)
```

**Comment by capricorn86** [comment]
If you want iframe and resources to be loaded, you can add a check to your test, so that it waits for everything to be completed before you do your checks.

```javascript
await window.happyDOM.whenAsyncComplete();
```
