### ISSUE TITLE
document.visibilityState is undefined

### ISSUE THREAD

**Issue by CSchulz** [capricorn86/happy-dom#774]
**Describe the bug**
document.visibilityState is undefined

**To Reproduce**
Try to access the visibilityState of the document. It is undefined.

**Expected behavior**
It should return at least 'visible'.

**Device:**
 - Version 8.7.1

**Comment by capricorn86** [comment]
Thanks again for the contribution! :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.7.3
