### ISSUE TITLE
Element.contains does not check itself

### ISSUE THREAD

**Issue by CSchulz** [capricorn86/happy-dom#776]
**Describe the bug**
The Element contains method does not check if the given element is the element itself resulting in wrong results.

**To Reproduce**
Pseudo code:
```
const element = queryElement();
expect(element.contains(element)).toBeTruthy();
```

**Expected behavior**
contains should return true if the given element is the same element running the method on.

**Device:**
 - Version 8.7.1

**Comment by capricorn86** [comment]
Thanks again for the contribution! :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.7.4
