### ISSUE TITLE
response encoding error when use XmlHttpRequest

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#783]
**Describe the bug**
response encoding error when use XmlHttpRequest

**To Reproduce**
we need to compatible encoding e.g. 'gbk'

```javascript
const window = new Window(), document = window.document;
const xhr = new window.XMLHttpRequest();
xhr.open("GET", "https://blog.shi1011.cn", true);
xhr.send();

xhr.onload = function() {
	console.log(xhr.responseText);
}
```

**Comment by capricorn86** [comment]
Thanks again for the contribution @Mas0nShi! :star2: 

We can add unit tests later. The current unit tests are passing, which means that nothing essential should break.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.7.6
