### ISSUE TITLE
direct write document.title does not work

### ISSUE THREAD

**Issue by lovetingyuan** [capricorn86/happy-dom#785]
**Describe the bug**
I use `document.title = 'title'`, but this does not work.

**To Reproduce**
1. open https://stackblitz.com/edit/node-jyhhtp?file=package.json,index.mjs
2. run `node index.mjs`

**Expected behavior**
described in the link above.

**Device:**
 - nodejs v16.14.2

**Comment by capricorn86** [comment]
Thanks for reporting @lovetingyuan! :slightly_smiling_face: 

Big thanks to @btea for providing with a fix! :star: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v8.8.0

**Comment by lovetingyuan** [comment]
wow, thanks 😊
