### ISSUE TITLE
`background-xxx` style not effective

### ISSUE THREAD

**Issue by qmhc** [capricorn86/happy-dom#787]
**Describe the bug**
It seems any `background-xxx` style not effective.

**To Reproduce**

https://github.com/qmhc/happy-dom-bug.git

Run `pnpm run test`.

And the test will fail.

**Expected behavior**
The test passes.

**Screenshots**

**Device:**
 - OS: windows 10
 - Browser Node
 - Version 8.7.2

**Additional context**
This test works well in v6, and will fail since v7.

**Comment by qmhc** [comment]
It seems all the multiple words style properties not work.

**Comment by malko** [comment]
Need to test if #985 solves this issue.

**Comment by capricorn86** [comment]
Looking at the test in https://github.com/qmhc/happy-dom-bug/blob/main/tests/app.spec.tsx, I think we can assume that your fix solves it :slightly_smiling_face: 

I'm closing this. @qmhc please re-open if the problem hasn't been solved.
