### ISSUE TITLE
testEnvironmentOptions.url of jest config is not taken in account

### ISSUE THREAD

**Issue by CSchulz** [capricorn86/happy-dom#800]
**Describe the bug**
testEnvironmentOptions.url of jest config is not taken in account. This leads to test failures if they rely on the location.href.

**To Reproduce**
Set the url in jest config and test in on test.

**Expected behavior**
The given url in testEnvironmentOptions should be set to the window.

**Device:**
 - Version 8.9.0

**Comment by capricorn86** [comment]
Thanks for your contribution @CSchulz ! :slightly_smiling_face:
