### ISSUE TITLE
Template Content is not handled properly

### ISSUE THREAD

**Issue by ekwoka** [capricorn86/happy-dom#807]
**Describe the bug**
Template contents are treated as nodes in Chrome/browsers. Happy-dom does not treat them as such, so when templates are cloned to use elsewhere, the contents is treated as a text node

**To Reproduce**
```js
import { Window } from 'happy-dom';

const window = new Window();
const { document, happyDOM } = window;

document.write('<div><template><span>test</span></template></div>');

console.log(document.querySelector('template').content.children[0].outerHTML);
```

This will error.

**Expected behavior**

Chrome logs:

```
<span>test</span>
```

It looks like `template` is marked as childless, which is not the case. Removing that does fix the above behavior. will pr later if I can ensure it solves the other issues with cloning template content I'm having.

for context, doing tests with happydom for AlpineJS using the `x-if` on template.

and alpine does this:

```js
const clone = templateEl.content.cloneNode(true).firstElementChild
```
which returns `null` in happydom.

**Comment by capricorn86** [comment]
This has been fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.1.3
