### ISSUE TITLE
Template element has no siblings

### ISSUE THREAD

**Issue by ekwoka** [capricorn86/happy-dom#809]
**Describe the bug**
Template elements always return null for `nextSibling` and `lastSibling` which is against the spec. It should behave as normal and return the next and last siblings.

**To Reproduce**
```js
import { Window } from 'happy-dom';

const window = new Window();
const { document, happyDOM } = window;

document.write('<template></template><span>test</span>');

console.log(document.querySelector('template').nextSibling);
```

**Expected behavior**
It should return the `span` node like it does in browsers

**Comment by capricorn86** [comment]
This has been fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.1.3
