### ISSUE TITLE
`happy-dom` doesn't convert `&gt;` to `>` whereas `jsdom` does

### ISSUE THREAD

**Issue by EvHaus** [capricorn86/happy-dom#818]
**Describe the bug**

When using `happy-dom` to set and then view the contents of a DOM node via `node.textContent`, if the DOM node has a `&gt;` character, `happy-dom` will return its `textContent` as `&gt;` whereas `jsdom` and web browsers will return the `>` character. Looks like `happy-dom` isn't converting those values.

**To Reproduce**

The following code can be used to reproduce the problem:

```js
document.documentElement.innerHTML = '<div id="testnode">&gt;howdy</div>';
expect(document.getElementById('testnode').textContent).toBe('>howdy');
```

Here is a StackBlitz which runs that code in both `jsdom` and `happy-dom` -- note the difference in output: https://stackblitz.com/edit/vitest-dev-vitest-fujcfs?file=test%2Fhappydom.test.ts%3AL6,test%2Fjsdom.test.ts 

**Expected behavior**

I expect `happy-dom` to have the same behaviour as `jsdom` when setting and reading `&gt;` and `&lt;` characters that are injected into a DOM node's body.

**Screenshots**

<img width="668" alt="Screenshot 2023-03-08 at 4 51 52 PM" src="https://user-images.githubusercontent.com/226640/223886741-93600441-ce1b-4619-8eca-669bc5910c3e.png">

**Device:**

N/A

**Comment by KaKi87** [comment]
Same for all other HTML entities.

**Comment by capricorn86** [comment]
Thank you for reporting @EvHaus and @KaKi87! :slightly_smiling_face: 

Big thanks to @btea for your contribution! :star2: 

There is a fix in now:
https://github.com/capricorn86/happy-dom/releases/tag/v9.3.2
