### ISSUE TITLE
Incorrect HTML string generated

### ISSUE THREAD

**Issue by fabiospampinato** [capricorn86/happy-dom#819]
**Describe the bug**

There's a mismatch between what I get with HappyDOM, and what I get with LinkedDOM or the actual DOM, so I'm pretty sure there's some bug in HappyDOM somewhere.

**To Reproduce**

1. `cd` into this folder `https://github.com/vobyjs/voby/tree/master/demo/ssr_esbuild`
2. `npm install`
3. Put this `console.log(document.getElementById ( 'app' ).innerHTML)` [here](https://github.com/vobyjs/voby/blob/d9712d8a9dc770891522591b2548c756c7ca8acd/demo/ssr_esbuild/src/index.tsx#L8), to log the HTML generated.
4. `npm dev`
5. Go to `http:/localhost:3000/counter`
6. Notice how there's a 0 below the `<h1>Counter</h1>`, as expected.
7. `npm install happy-dom-global`.
8. Replace `linkedom-global` for `happy-dom-global` [here](https://github.com/vobyjs/voby/blob/master/demo/ssr_esbuild/server/index.tsx/#L4).
9. Go to `http:/localhost:3000/counter` and notice how the logged HTML doesn't have a 0 anymore. You'll still see one in the page because the page is re-rendered client-side, to turn that off comment out [this line](https://github.com/vobyjs/voby/blob/master/demo/ssr_esbuild/src/index.tsx/#L9).

**Expected behavior**

HappyDOM's output should make LinkeDOM's and the browser's.

**Additional context**

I'm not exactly sure what the issue is, the only thing I can think of is that calling `.nodeValue = 0` maybe doesn't work in Happy DOM, if that's not the issue I'm not sure what it is.

**Comment by capricorn86** [comment]
Thank you for reporting @fabiospampinato! :slightly_smiling_face: 

There is a fix released now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.18.2
