### ISSUE TITLE
Missing window.SubmitEvent

### ISSUE THREAD

**Issue by rmorshea** [capricorn86/happy-dom#820]
**Is your feature request related to a problem? Please describe.**
Presently, there is no `window.SubmitEvent` available.

**Describe the solution you'd like**
Add one, as has been done for other common event types. Seems like the only attribute you'd need to add is a `SubmitEvent.submitter` property as per [these docs](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent).

**Describe alternatives you've considered**
The alternative is to construct a base `Event` and add a `submitter` to it manually.

**Comment by capricorn86** [comment]
Thank you for reporting @rmorshea! 🙂 

Big thanks to @danielrentz for contributing! 🌟 

There is a fix released now:
https://github.com/capricorn86/happy-dom/releases/tag/v9.5.0
