### ISSUE TITLE
`iframe.sandbox` should return a DOMTokenList instead of a string

### ISSUE THREAD

**Issue by saschanaz** [capricorn86/happy-dom#825]
**Describe the bug**
As the title says.

https://github.com/capricorn86/happy-dom/blob/13bcfe77ae9a202a93ce8fddcf4a7c1b43ecde16/packages/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts#L121-L123

**To Reproduce**
On the REPL console:

```js
dom = await import("happy-dom")
(new dom.Window()).document.createElement("iframe").sandbox
```

**Expected behavior**

A DOMTokenList should be returned.

**Screenshots**

**Device:**
 - OS: Windows
 - Browser: Node.js
 - Version: 19.6.0

**Additional context**

See https://html.spec.whatwg.org/multipage/iframe-embed-object.html#htmliframeelement for the spec.

**Comment by capricorn86** [comment]
Thank you for reporting @saschanaz! :slightly_smiling_face: 

Big thanks to @jeffwcx to make a contribution :star: 

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v14.4.0
