### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by godIsAProgrammer** [capricorn86/happy-dom#827]
**Describe the bug**
When I load an ant-design-vue InputNumber component using Vitest and Vue Test Utils, I report Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present. mistake

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11454918/225186923-70b45e3c-f524-4fe2-9738-8acb1d5aa911.png)

**Device:**
 - Version 8.9.0
**Additional context**
```ts
import Antd from "ant-design-vue";

import c from 'example.ts';

const wrapper = mount(c, {
     attachTo: document.body,
     props: mockProps,
     global: {
         plugins: [ Antd ]
      }
 });
```
my custom component:

example.ts

```vue
<template>
  <div>
    <a-input-number
      v-model:value="textValue"
      :size="inputConfig.inputSize"
      :placeholder="inputConfig.placeholder"
      :clearable="inputConfig.clearable"
      :disabled="inputConfig.disabled"
      :max="inputConfig.max"
      :min="inputConfig.min"
      :step="inputConfig.step"
      :controls="inputConfig.controls"
      :style="styleObj"
      @change="change"
    ></a-input-number>
  </div>
</template>
```

**Comment by btea** [comment]
Can you provide a repository address or a link to reproduce it online?

**Comment by AndrewADev** [comment]
I'm seeing this same failure, also with Vitest and Vue Test Utils, albeit with an icon component from `@ant-design/icons-vue`:
```vue
<template>
  <div>
    More information here
    <InfoCircleOutlined />
  </div>
</template>
```


A minimal test repo is available [here](https://github.com/AndrewADev/happy-dom-ant-design-bug-insert).

The test where the issue is thrown is [this one](https://github.com/AndrewADev/happy-dom-ant-design-bug-insert/blob/main/src/components/InfoBox.spec.ts#L8).

**Comment by capricorn86** [comment]
Thank you @godIsAProgrammer and @AndrewADev for reporting! :slightly_smiling_face: 

Big thanks to @btea for your contribution!

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.9.2
