### ISSUE TITLE
Add navigator.clipboard

### ISSUE THREAD

**Issue by himself65** [capricorn86/happy-dom#833]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by capricorn86** [comment]
Thank you for reporting @himself65! :slightly_smiling_face: 

This has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.8.0
