### ISSUE TITLE
Click doesn't work after 9.1

### ISSUE THREAD

**Issue by ekwoka** [capricorn86/happy-dom#834]
**Describe the bug**
In all existing tests I have that involve a click, now nothing happens when the click happens, even if I wait a whole second after

**To Reproduce**
1. clone https://github.com/ekwoka/Alpine-TS
2. update happy-dom
3. run tests

Even a simple test like

```js
import { Window } from 'happy-dom';

describe('click test', () => {
  it('click test', async () => {
    let clicked = false;
    const window = new Window();
    window.clicker = () => {
      clicked = true;
    };
    window.document.body.innerHTML = `<div>
        <button onclick="clicker()">Click me</button>
      </div>`;
    window.document.querySelector('button').click();
    await window.happyDOM.whenAsyncComplete();
    await new Promise((res) => setTimeout(res, 1000));
    expect(clicked).toBe(true);
  });
});
```

fails.

**Expected behavior**
Clicks should work

**Comment by capricorn86** [comment]
Thanks for reporting and contributing @ekwoka! :slightly_smiling_face: 

Too bad we both started to work on this task.

This has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.1.3

**Comment by ekwoka** [comment]
Verified. It's working as is everything else from the other PRs (would have been nice to get the contribution credit though 😄 )

**Comment by capricorn86** [comment]
Great to hear!

I have added you to the release notes as contributor now :slightly_smiling_face: I will start doing that for contributions to highlight it.
