### ISSUE TITLE
FormData.getAll does not respond with all values of elements with same name

### ISSUE THREAD

**Issue by Xiphe** [capricorn86/happy-dom#835]
**Describe the bug**

When submitting a HTML form we can give multiple inputs the same name and they're all part of the submission.

```tsx
// React code
<form
  onSubmit={(ev) => {
    ev.preventDefault();
    const formData = new FormData(ev.target as HTMLFormElement);
    console.log(formData.getAll('one'));
  }}
>
  <input type="hidden" name="one" value="one" />
  <input type="hidden" name="one" value="two" />
  <button type="submit">submit</button>
</form>
```

This will log `['one', 'two']` to the console when the submit button is clicked

In my tests, the new FormData implementation omits the second value and only logs `['one']`.

**To Reproduce**

Run the above code in a test environment such as vite with happy-dom and see `['one']` being logged.

I'm currently short on time but still wanted to report this asap. Let me know when I should provide a test/repo/more elaborate steps

**Expected behavior**

I would expect that `['one', 'two']` is being logged with happy-dom

**Comment by Xiphe** [comment]
That was quick! Thank you so much!

**Comment by PaulCouthouis** [comment]
Sorry, but I am once again encountering this bug in my environment with version 14.12.3.
