### ISSUE TITLE
Wrong patch #677: Cookie

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#836]
https://github.com/capricorn86/happy-dom/blob/10ba5ea449fba4a3ed0f6271169b7040f2a4a767/packages/happy-dom/src/xml-http-request/XMLHttpRequest.ts#L561

this PR #677 change cookie to `document.cookie`, it's wrong! 

it's need to stay as is: `this._cookie.getCookiesString(this.defaultView.location, false); ` 

why????

https://github.com/capricorn86/happy-dom/blob/b83bc1dad2cf1efce541549003b74c6f7162a902/packages/happy-dom/src/cookie/CookieJar.ts#L52-L81

we don't need cookie that has `httponly` attribute when we use `document.cookie`,  so I set `fromDocument` param.

https://github.com/capricorn86/happy-dom/blob/b83bc1dad2cf1efce541549003b74c6f7162a902/packages/happy-dom/src/nodes/document/Document.ts#L261-L268

but we need need to use cookie that has `httponly` attribute when we send http requests, so it's must different with `document.cookie`.

**Comment by capricorn86** [comment]
Thanks for reporting @Mas0nShi! :slightly_smiling_face: 

There is a fix available now:
https://github.com/capricorn86/happy-dom/releases/tag/v9.1.10
