### ISSUE TITLE
Assigned keys to SVGElement.dataset are ignored

### ISSUE THREAD

**Issue by danielrentz** [capricorn86/happy-dom#841]
**Describe the bug**
Code that assigns props to the dataset of an SVG element cannot be tested. I found [issue 405](https://github.com/capricorn86/happy-dom/issues/405) with [PR 438](https://github.com/capricorn86/happy-dom/pull/438) that fixes this for HTMLElement, seems it needs to be done in a similar way for SVGElement.

**Comment by capricorn86** [comment]
Thank you again for your contribution @danielrentz! :star2: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.2.0
