### ISSUE TITLE
Declaration maps are missing.

### ISSUE THREAD

**Issue by ekwoka** [capricorn86/happy-dom#842]
**Describe the bug**
When working with happydom and right clicking and selectiong "go to definition" in vscode, it leads to the .d.ts files instead of the actual source.

**To Reproduce**
Have any project using happydom, right click on something from happydom, and hit "go to definition"

**Expected behavior**
should go to the src ts file

**Comment by capricorn86** [comment]
Thanks for your contribution! :slightly_smiling_face:
