### ISSUE TITLE
`getComputedStyles` not computing styles added to the style object of element

### ISSUE THREAD

**Issue by taylorfsteele** [capricorn86/happy-dom#845]
**Describe the bug**
Calling `window.getComputedStyles(element)` doesn't return the proper style on a given element with inlined styles on the element.

```
  test('getComputedStyles', () => {
    const element = document.createElement('div');
    element.style.color = 'red';

    const computedStyles = window.getComputedStyle(element);

    console.log(computedStyles.color); // ""
    console.log(element.style.color); // "red"
  });
```

**Expected behavior**
Expected the correct values returned from the `getComputedStyle` function.

**Device:**
 - Version 9.1.0
 - Vitest 0.29.8

**Comment by capricorn86** [comment]
Thanks for reporting @taylorfsteele! 🙂 

According to spec, the element must be connected to the DOM (child of the document) in order for computed styles to be calculated.

**Comment by capricorn86** [comment]
I will close this based on the answer.

**Comment by taylorfsteele** [comment]
Ah ha, thank you!!

Just in case then anyone stumbles across this, appending it to the document did solve this:

```
test('getComputedStyles', () => {
  const element = document.createElement('div');
  element.style.color = 'red';

  document.appendChild(element);

  const computedStyles = window.getComputedStyle(element);

  console.log(computedStyles.color); // ""
  console.log(element.style.color); // "red"
});
```
