### ISSUE TITLE
TypeError: The "obj" argument must be an instance of Blob. Received an instance of File vitest

### ISSUE THREAD

**Issue by mirzaahmedov** [capricorn86/happy-dom#847]
**Describe the bug**
I am trying to test file upload functionality but getting this error

```javascript
this.form[name] = URL.createObjectURL(e.target.files[0])
```
test
```javascript
userEvent.upload(input, file)
```
gives me this error `TypeError: The "obj" argument must be an instance of Blob. Received an instance of File Vitest`

**Additional context**
I am using Vitest with happy-dom

**Comment by btea** [comment]
This seems to be a problem with nodejs, only values ​​of type `Blob` are supported. [reference documents](https://nodejs.org/dist/latest-v19.x/docs/api/url.html#urlcreateobjecturlblob)

**Comment by capricorn86** [comment]
I think we will have to extend NodeJS:s URL with our own implementation for methods that depends on Happy DOM classes such as File and Blob.

```javascript
import { URL as NodeJSURL } from 'url';

export default class URL extends NodeJSURL {
       public override createObjectURL(object: Blob): string {
              // TODO: Implement
       }
}
```

**Comment by capricorn86** [comment]
A fix has now been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.1.6
