### ISSUE TITLE
disableJavaScriptFileLoading and script events

### ISSUE THREAD

**Issue by dteoh** [capricorn86/happy-dom#849]
**Is your feature request related to a problem? Please describe.**

Is it possible to get `script.onload` and `script.onerror` events to fire when `disableJavaScriptFileLoading` is used?

I have some code like:

```js
return new Promise((resolve, reject) => {
  const script = document.createElement('script')
  script.src = 'https://something'
 
  script.onload = resolve
  script.onerror = reject

  document.head.appendChild(script)
})

```

When `disableJavaScriptFileLoading` is used, the promise won't resolve since the `load` event doesn't get fired.

**Describe the solution you'd like**

Could we extend the option to be: `disableJavaScriptFileLoading: true | false | 'load' | 'error' | callback`?

* `load`: don't load the file, but fire the `load` event
* `error`: don't load the file, but fire the `error` event
* callback: give the script object as the first argument, the function returns one of `true | false | 'load' | 'error'` to customize the behaviour

WDYT?

**Comment by capricorn86** [comment]
Hi @dteoh! :slightly_smiling_face: 

This is a touch one. I guess the most logical thing here would to trigger an `error` event as the request technically failed. Would that solve your issue?

I'm not sure custom testing logic like this should be handled by Happy DOM, but I also understand that this is not very easy to implement a polyfill for as it would have to override internal logic.

**Comment by dteoh** [comment]
Thank you for your feedback! Yes, I think firing an `error` event would be workable.

**Comment by capricorn86** [comment]
@dteoh I have implemented a fix now that will trigger an error :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.18.0

**Comment by dteoh** [comment]
Thank you very much!
