### ISSUE TITLE
"id" attributes with colons (`:`) break DOM selectors

### ISSUE THREAD

**Issue by EvHaus** [capricorn86/happy-dom#877]
**Describe the bug**

I'm building a React app. In React there's [a `useId()` method](https://react.dev/reference/react/useId) which is used to generate unique `id` attributes for DOM elements. The values that `useId()` generates have colons (`:`), eg. `<div id=":r1:" />`. 

It looks like `happy-dom` doesn't handle these very nicely and when you try to query elements by an ID with colons, `happy-dom` returns you back incorrect results.

**To Reproduce**

Use the following code:

```js
// Create a div with an "id" with a colon
const el = document.createElement('div', { id: ':r1' });

// Append it to the body
document.body.appendChild(el);

// BUG: Query element by id in `happy-dom`
console.log(document.querySelector(CSS.escape(':r1:')).outerHTML);
// -> Expecting this to return the <div> I created, but it actually returns the root <html> element

// BUG: Similarly, if you do this:
console.log(document.body.closest(CSS.escape(':r1:')));
// -> I would expect it to return `null` because document.body doesn't have any parents with such an ID, but it weirdly returns the <body> element
```

**Expected behavior**
See notes above

**Screenshots**
N/A

**Device:**
 - OS: MacOS
 - Browser: Node.js
 - Version: happy-dom@9.9.2

**Comment by capricorn86** [comment]
Thank you for reporting @EvHaus! :slightly_smiling_face: 

The problem has been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.1

**Comment by EvHaus** [comment]
Thanks @capricorn86. Confirmed this works now!
