### ISSUE TITLE
`DOMException` is thrown for selectors with an explicit empty attribute value

### ISSUE THREAD

**Issue by romansp** [capricorn86/happy-dom#881]
**Describe the bug**
`DOMException: Invalid selector` is thrown for an empty attribute value selector, e.g. `[contenteditable=""]` or `[disabled=""]`.

**To Reproduce**
```js
// throws DOMException: Invalid selector: "[contenteditable=""], [contenteditable="true"]"

it('Returns all elements matching "[contenteditable=""], [contenteditable="true"]".', () => {
	document.body.innerHTML = `
		<div contenteditable></div>
		<div contenteditable=""></div>
		<div contenteditable="true"></div>
		<div contenteditable="false"></div>
	`;
	const elements = document.querySelectorAll('[contenteditable=""], [contenteditable="true"]');
	expect(elements.length).toBe(3);
	expect(elements[0] === document.body.children[0]).toBe(true);
});
```

**Expected behavior**
Selector `[contenteditable=""]` should be considered correct.

**Device:**
 - Version `9.10.1`.

**Additional context**
This is a regression introduced in `v9.10.0`.

For reference `testing-library/user-event` uses this quite complex selector with empty attribute value to find focusable elements on the page: https://github.com/testing-library/user-event/blob/7a305dee9ab833d6f338d567fc2e862b4838b76a/src/utils/focus/selector.ts#L1

**Comment by capricorn86** [comment]
Thank you for reporting @romansp! :slightly_smiling_face: 

The issue has been fixed:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.2
