### ISSUE TITLE
`HTMLAnchorElement.toString()` should return `href` instead of `outerHTML`

### ISSUE THREAD

**Issue by Schleuse** [capricorn86/happy-dom#890]
**Describe the bug**
`HTMLAnchorElement` has a specific implementation of `toString()` that differs from `Element`.
`Element.toString()` returns `outerHTML` where `HTMLAnchorElement.toString()` should return `href`.

[HTMLAnchorElement.toString()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/toString)

**To Reproduce**
```js
import { Window } from 'happy-dom';

const window = new Window();
const document = window.document;
const anchor = document.createElement('a');
anchor.setAttribute('href', 'https://github.com/capricorn86/happy-dom');
anchor.innerHTML = 'Happy DOM';

console.log({
  toString: anchor.toString(),
  href: anchor.href
});

/* prints:
{
  toString: '<a href="https://github.com/capricorn86/happy-dom">Happy DOM</a>',
  href: 'https://github.com/capricorn86/happy-dom'
}
*/

/* should be :
{
  toString: 'https://github.com/capricorn86/happy-dom',
  href: 'https://github.com/capricorn86/happy-dom'
}
*/


```

**Expected behavior**
`toString()` should return the same value as the `href` property

**Comment by capricorn86** [comment]
@Schleuse your fix has been released 🙂 

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.8
