### ISSUE TITLE
TypeError: request.clone(...).formData is not a function

### ISSUE THREAD

**Issue by rolandjohann** [capricorn86/happy-dom#892]
**Describe the bug**
The method `formData()` is missing at Request interface and its implementation.

https://developer.mozilla.org/en-US/docs/Web/API/Request/formData

**To Reproduce**
```typescript
it('should work with form data', async () => {
  const formData = new FormData();
  formData.append('some', 'test');
  const request = new Request('http://foo.bar/baz', { method: 'post', body: formData });
  const formDataFromRequest = await request.formData();
  expect(formDataFromRequest).toBe(formDataFromRequest);
});
```

**Actual Behavior**
```
TypeError: request.formData is not a function
```

**Expected behavior**
test should succeed

**Additional context**
We start to migrate a project to remix and to implement the action/loader unit tests where we need to construct `Request`s manually and pass them the form data.

**Comment by capricorn86** [comment]
@rolandjohann your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.9
