### ISSUE TITLE
Test failing with "webkit-keyframes mui-auto-fill" error on version 9.3.0 or above

### ISSUE THREAD

**Issue by usman1947** [capricorn86/happy-dom#894]
When using version 9.3.0 or above am getting error msg **DOMException: Invalid selector: "@-webkit-keyframes mui-auto-fill** when trying to render MUI Select in my test, and my test is failed. Though it works fine if i downgrade to version 9.2.1 

[Here's a condesandBox where is reproduced the bug: ](https://codesandbox.io/p/sandbox/elated-blackwell-kh2vxp?welcome=true)

Test doesn't fail with this error msg as it doesnt on 9.2.1

![Screenshot 2023-05-03 at 5 46 04 PM](https://user-images.githubusercontent.com/110887337/236057020-10dbbbc7-8da1-4197-91ee-25d29d5cc357.png)

**Comment by btea** [comment]
Seems to be the same problem as #889.

**Comment by btea** [comment]
@usman1947 You can try the latest version.

**Comment by usman1947** [comment]
tested @btea, it working fine now on version 9.16.0
