### ISSUE TITLE
`document.links` is undefined

### ISSUE THREAD

**Issue by aleclarson** [capricorn86/happy-dom#896]
**Is your feature request related to a problem? Please describe.**
I'm using this API: https://developer.mozilla.org/en-US/docs/Web/API/Document/links
but it doesn't exist in happy-dom.

**Describe the solution you'd like**
Add `document.links`

**Comment by capricorn86** [comment]
Thank you @aleclarson for reporting! :slightly_smiling_face: 

Big thanks to @btea for your contribution! :star2: 

You can read more about the release:
https://github.com/capricorn86/happy-dom/releases/tag/v9.14.0
