### ISSUE TITLE
Location test suite named 'assign()' actually calls 'replace()'

### ISSUE THREAD

**Issue by BrainCrumbz** [capricorn86/happy-dom#907]
**Describe the bug**
Not sure this is a bug or is intended. When testing Location behavior, there's [a test suite](https://github.com/capricorn86/happy-dom/blob/df270ec3a1cd7f9249455aaa7de96d87d90014de/packages/happy-dom/test/location/Location.test.ts#L23) named `assign()`. But in its expectation, it actually invokes `location.replace(...)`.

Is this intended?

**To Reproduce**
1. Inspect test file https://github.com/capricorn86/happy-dom/blob/df270ec3a1cd7f9249455aaa7de96d87d90014de/packages/happy-dom/test/location/Location.test.ts#L21-L23

**Expected behavior**
Test should call `location.assign(...)'

HTH

**Comment by capricorn86** [comment]
Thanks for reporting @BrainCrumbz! :slightly_smiling_face: 

This is most likely a mistake.
