### ISSUE TITLE
DOMParser().parseFromString(...) doesn't decode html entities

### ISSUE THREAD

**Issue by mreinstein** [capricorn86/happy-dom#908]
setup code for happy-dom:

```javascript
const window = new Window();
const doc = new window.DOMParser().parseFromString('<p>here is some</p> html el&#225;stica ', 'text/html');
console.log('text:', doc.body.textContent);
```

output:
```bash
text: here is some html el&#225;stica
```

similar code, in a browser:
```javascript
const doc = new window.DOMParser().parseFromString('<p>here is some</p> html el&#225;stica ', 'text/html');
console.log('text:', doc.body.textContent);
```

output:
```bash
text: here is some html elástica 
```

le bug? tested with happy-dom@9.12.0 and chrome@113

**Comment by capricorn86** [comment]
Thank you for reporting @mreinstein! :slightly_smiling_face: 

I have implemented a fix for the issue now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.16.0

**Comment by mreinstein** [comment]
wow, the speed!

**Comment by adaboese** [comment]
This change seems to cause a few issues https://github.com/capricorn86/happy-dom/issues/944#issuecomment-1869080464
