### ISSUE TITLE
markupRegexp doesn't parse comments properly if they contain a dash in the text

### ISSUE THREAD

**Issue by gtm-nayan** [capricorn86/happy-dom#916]
**Describe the bug**
Given a comment like `<!-- svelte-xyz -->`, the parser will incorrectly include a trailing `--` in the textContent of the comment.

https://github.com/capricorn86/happy-dom/blob/07448050a759d55f220abbfe85951e9da7c1157c/packages/happy-dom/src/xml-parser/XMLParser.ts#LL14C1-L27C104

**To Reproduce**
Run `MARKUP_REGEXP.exec("<!-- a-b -->")`, third group will have `a-b --`

**Expected behavior**
The third group contains `a-b `

**Comment by capricorn86** [comment]
Thank you for your contribution @gtm-nayan! :star2: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.18.2
