### ISSUE TITLE
MatchMedia.matches support

### ISSUE THREAD

**Issue by belgattitude** [capricorn86/happy-dom#921]
**Is your feature request related to a problem? Please describe.**

Would be great to provide `window.matchMedia().matches` support.

**Describe the solution you'd like**

Currently happy-dom isn't able to work with

```typescript
const browserTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
```

Currently on latest version 9.18.3 it produces 

```
TypeError: Cannot read properties of undefined (reading 'matches')

      12 |
      13 | const getDefaultTheme = () => {
    > 14 |   const browserTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
```

**Describe alternatives you've considered**

N/A

**Additional context**

I'm currently trying to get a faster ci in the strapi repo: one iteration consists of trying to move from js-dom to happy-dom. 

See https://github.com/strapi/strapi/pull/16713#issuecomment-1546857986

**Comment by capricorn86** [comment]
Thank you for reporting @belgattitude! :slightly_smiling_face: 

I have made a fix that adds support for "prefers-color-scheme" and many more media query features.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.19.0

**Comment by belgattitude** [comment]
Thanks a lot, this a great feature.
