### ISSUE TITLE
Selector [attr^=value] without quotes not working with the latest version

### ISSUE THREAD

**Issue by ypconstante** [capricorn86/happy-dom#923]
**Describe the bug**

On happy-dom 9.18.3, the selector [attr^=value] is not working when the value is not wrapped by quotes. This worked on previous versions.

**To Reproduce**

```
const { Window } = require("happy-dom")

const window = new Window();
const document = window.document;

document.body.innerHTML = '<div id="my-container"></div>';

console.log(document.querySelector('[id^="my"]') != null);
console.log(document.querySelector("[id^='my']") != null);
console.log(document.querySelector("[id^=my]") != null);
```

Output:
```
true // [id^="my"]
true // [id^='my']
false // [id^=my]
```

**Expected behavior**

Output with version 9.16.0
```
true // [id^="my"]
true // [id^='my']
true // [id^=my]
```

**Device:**
 - OS: macOS 13.3.1
 - Browser -
 - Version -

**Comment by capricorn86** [comment]
Thank you for reporting @ypconstante! :slightly_smiling_face: 

There is a fix released now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.19.2
