### ISSUE TITLE
querySelectorAll is not always returning elements in document order

### ISSUE THREAD

**Issue by alexgallardo** [capricorn86/happy-dom#928]
**Describe the bug**
Incorrect order of elements when using `document.querySelectorAll` under certain circumstances. See "Additional context" for a technical description.

**To Reproduce**
```js
import { Window } from "happy-dom";

const window = new Window();
const document = window.document;

document.body.innerHTML = `
<div>0</div>
<button>1</button>
<div>2</div>
<div>3</div>
<div>4</div>
<div>5</div>
<div>6</div>
<div>7</div>
<button>8</button>
<button>9</button>
<button>10</button>
<button>11</button>
`;

document
  .querySelectorAll("button")
  .forEach((button) => console.log(button.textContent));

// Output:
// 1
// 10
// 11
// 8
// 9
```

**Expected behavior**
`document.querySelectorAll` [should return the elements in document order](https://www.w3.org/TR/selectors-api/#findelements).

**Additional context**
In the `QuerySelector` class, `findAll` method, when iterating through the elements, the position of every one is stored as a string using its index: https://github.com/capricorn86/happy-dom/blob/2c62156e2bdb98385883e087a9c76629426d00b7/packages/happy-dom/src/query-selector/QuerySelector.ts#L224

Later, in the `querySelectorAll` method, that position is used to sort the results: https://github.com/capricorn86/happy-dom/blob/2c62156e2bdb98385883e087a9c76629426d00b7/packages/happy-dom/src/query-selector/QuerySelector.ts#L62

Given that individual characters are compared when sorting strings, items with an index of 10 to 19, 100 to 199 and so on will appear before items with index of 3, 4...

Something like adding leading zeroes to the position of the elements of every level up to the number of digits of `children.length - 1` would fix the issue without changing the way they are sorted, but since performance is a selling point vs _jsdom_, maybe a more complex solution is preferable.

**Comment by capricorn86** [comment]
Thank you for reporting @alexgallardo! :slightly_smiling_face: 

I have fixed the problem now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.20.1

**Comment by capricorn86** [comment]
The sorting mechanism was sorting incorrectly as it sorted by characters and numbers came in the wrong order (1, 10, 11, 2, 3, 4 etc.). The unit test did not cover this.
