### ISSUE TITLE
Missing support for /ChildNode/replaceWith and Document/createElementNS

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#93]
Excellent work!

Is it possible to add functionality for:
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith

and 
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS
?

**Comment by davidortnercybercom** [comment]
Thank you @jgonte!

Yes, sure! I will add it later Today :slightly_smiling_face:

**Comment by capricorn86** [comment]
Thank you @jgonte!

Yes, sure! I will add it later Today slightly_smiling_face

**Comment by capricorn86** [comment]
@jgonte ChildNode.replaceWith() is now supported in v1.2.0. Thank you for reporting this issue.

**Comment by jgonte** [comment]
Verified that ChildNode.replaceWith() is working ... Excellent :-)
