### ISSUE TITLE
Read css vars with getComputedStyle don't work

### ISSUE THREAD

**Issue by pserrer1** [capricorn86/happy-dom#932]
**Describe the bug**
`getComputedStyle` don't returns the value of css vars.
This might be related to the fact that `CSSStyleDeclarationElementStyle` don't store the value of the already evaluated `cssVariables` inside the `PropertyManager`.

**To Reproduce**
```
document.documentElement.style.setProperty("--foo", "1rem")
assert(getComputedStyle(document.documentElement).getPropertyValue("--foo") == "1rem")
```

**Comment by capricorn86** [comment]
Thank you for reporting @pserrer1! :slightly_smiling_face: 

The issue has been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.20.2
