### ISSUE TITLE
DOMException: Invalid selector, when parsing tailwindcss

### ISSUE THREAD

**Issue by rinux55** [capricorn86/happy-dom#939]
I'm testing a nuxt 3 application with `vite` and `nuxt-vitest`, which uses `happy-dom`. When installing the `@nuxtjs/tailwindcss` nuxt module, I'm getting the following error when asserting `expect().toBeVisible()`:

```
DOMException: Invalid selector: "::-webkit-inner-spin-button,::-webkit-outer-spin-button"
 ❯ Function.getSelectorGroups ../../../node_modules/happy-dom/src/query-selector/SelectorParser.ts:186:10
 ❯ Function.match ../../../node_modules/happy-dom/src/query-selector/QuerySelector.ts:119:38
 ❯ CSSStyleDeclarationElementStyle.parseCSSRules ../../../node_modules/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts:274:42
 ❯ CSSStyleDeclarationElementStyle.getComputedElementStyle ../../../node_modules/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts:128:12
 ❯ CSSStyleDeclarationElementStyle.getElementStyle ../../../node_modules/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts:63:16
 ❯ CSSStyleDeclaration.getPropertyValue ../../../node_modules/happy-dom/src/css/declaration/AbstractCSSStyleDeclaration.ts:193:37
 ❯ CSSStyleDeclaration.get visibility [as visibility] ../../../node_modules/happy-dom/src/css/declaration/CSSStyleDeclaration.ts:4625:15
 ❯ isInaccessible ../../../node_modules/@testing-library/dom/dist/role-helpers.js:67:39
 ❯ ../../../node_modules/@testing-library/dom/dist/queries/role.js:195:63
```

I've narrowed it down to the `@nuxtjs/tailwindcss` module. Installing tailwind as is on a project does not give this error.
I know it's a bit specific, but any help in the right direction would be greatly appreciated!

**To Reproduce**
1. Install `@nuxtjs/nuxt` version 3
2. Install the `@nuxtjs/tailwindcss` module
3. Install `vitest`, `nuxt-vitest`, `jest-dom`, `@testing-library/jest-dom`
4. Supply the property `css:true` in the vitest config, so css will be parsed
5. Run an assertion that an element is visible

**Comment by btea** [comment]
@rinux55 Hello, can you provide a simple code address?

**Comment by rinux55** [comment]
@btea thanks a lot for picking this up. I've created a demo for you.

https://stackblitz.com/edit/nuxt-starter-hgbacm?file=pages%2Findex.spec.ts

Running `npm run test` will trigger the error.

**Comment by btea** [comment]
#943 should have fixed this issue.

**Comment by capricorn86** [comment]
Thank you for reporting @rinux55! :slightly_smiling_face: 

Big thanks to @btea for your contribution :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.0.5
