### ISSUE TITLE
Can't render portals sometimes

### ISSUE THREAD

**Issue by llllvvuu** [capricorn86/happy-dom#940]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/radix-ui/primitives/issues/2166#issuecomment-1564398796)

**To Reproduce**
I don't have anything more minimal than the above sandbox, I suppose a more minimal repro would be to try to reproduce it in plain DOM. The `@radix-ui/react-select` code is pretty small though.

**Expected behavior**
`jsdom` renders this with no issue.

**Screenshots**
N/A

**Device:**
See linked issue

**Additional context**
Linked issue provides a bunch of context

**Comment by capricorn86** [comment]
Thank you for reporting @llllvvuu! :slightly_smiling_face: 

The issue has now been fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v12.5.1
