### ISSUE TITLE
DOMParser parseFromString outputting improper HTML (attributes do not keep necessary entities)

### ISSUE THREAD

**Issue by vknowles-rv** [capricorn86/happy-dom#944]
**Describe the bug**
parseFromString improperly handling html entities. I believe it stems from changes via https://github.com/capricorn86/happy-dom/issues/908. parseFromString is working as expected in version 9.15. If outerHTML is used via happy-dom after a parse, it will output improper HTML (ex. `<ul data-obj="{"missUseOfQuotes":true}"></ul>`)

**To Reproduce**

 ```javascript
 let parser = new DOMParser();
 
parser.parseFromString('<ul data-obj="{&quot;id&quot;:&quot;8im09mactz8v3d8&quot;,&quot;type&quot;:&quot;html&quot;}"></ul>', 'text/html').body.outerHTML
```

**Expected behavior**
Chrome:
```html
<body><ul data-obj="{&quot;id&quot;:&quot;8im09mactz8v3d8&quot;,&quot;type&quot;:&quot;html&quot;}"></ul></body>
```

happy-dom 9.15
```html
<body><ul data-obj="{&quot;id&quot;:&quot;8im09mactz8v3d8&quot;,&quot;type&quot;:&quot;html&quot;}"></ul></body>
```

happy-dom latest
```html
<body><ul data-obj="{"id":"8im09mactz8v3d8","type":"html"}"></ul></body>
```

**Device:**
 - OS: macOS Ventura
 - Browser: Node v16.20

**Additional context**
I'm using happy dom via vitest.

**Comment by adaboese** [comment]
Is there a workaround?

**Comment by adaboese** [comment]
Can confirm that pinning v9.15 fixes my issue as well.

```
const window = new Window();

const document = new window.DOMParser().parseFromString(`<code>&lt;html&gt;</code>`, 'text/html');

document.documentElement.outerHTML
```

Expecting output to be `<code>&lt;html&gt;</code>`, but getting `<code><html></code>`

**Comment by asprouse5** [comment]
This is also breaking our code. We have <pre> blocks in our HTML that uses &lt; and &gt; entities that get transformed into < and >. Using v14.12.3.

**Comment by asprouse5** [comment]
As a workaround, I base64 encode `&lt;` before writing the body to the document, then right before I return the final HTML I decode it back to `&lt;`

**Comment by capricorn86** [comment]
Thank you for reporting @vknowles-rv and @adaboese! :slightly_smiling_face: 

I believe this has been fixed in v15 of Happy DOM. Can you please verify?
