### ISSUE TITLE
Calling getRootNode on document should return document but returns null 

### ISSUE THREAD

**Issue by Schleuse** [capricorn86/happy-dom#950]
**Describe the bug**
Calling `getRootNode()` on `document` should return the document but returns `null`

**To Reproduce**
Call `getRootNode()` on `document`

**Expected behavior**
It should return `document` but return's `null`

See Note above `getRootNode` in the [Spec](https://dom.spec.whatwg.org/#dom-node-getrootnode)

**Comment by capricorn86** [comment]
Your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.1.1
