### ISSUE TITLE
Missing the movement values in MouseEvent

### ISSUE THREAD

**Issue by mertcan** [capricorn86/happy-dom#953]
**Describe the bug**
Currently, it passes default values for movementX and movementY. I can't pass my movement values.

**To Reproduce**
`fireEvent.mouseMove(window, { movementX: 10, movementY: 10 });`

**Expected behavior**
`expect(mockSpy).toHaveBeenCalledWith(10, 10);`

**Comment by capricorn86** [comment]
@mertcan your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.4.0
