### ISSUE TITLE
`queueMicrotask` is not a function

### ISSUE THREAD

**Issue by loreanvictor** [capricorn86/happy-dom#959]
**Describe the bug**
[`window.queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask) is undefined, causing issues with running some custom components that use the functionality.

**To Reproduce**
Run the following code ([sandbox](https://codesandbox.io/p/sandbox/sad-borg-67qxtm?file=%2Findex.mjs%3A6%2C5)):

```js
import { Window } from "happy-dom";
import { JSDOM } from "jsdom";

const jsdwindow = new JSDOM().window;
const happywindow = new Window();

console.log(jsdwindow.queueMicrotask);
console.log(happywindow.queueMicrotask);
```

**Expected behavior**
`window.queueMicrotask` exists and behaves according to specification (or perhaps a rough proxy of it, e.g. `cb => Promise.resolve().then(cb)`, is enough for most use cases that happy dom is to cover?)

**Additional context**
I am unsure if this should be considered a feature request or a bug. Currently I listed this as a bug since `happy-dom` aims to be useful for testing and server-side rendering of custom elements, but lacking this feature means it cannot run custom elements relying on the functionality (that's how I encountered the issue actually).

**Comment by capricorn86** [comment]
Thank you for reporting @loreanvictor! :slightly_smiling_face: 

There is a fix out now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.2.0
