### ISSUE TITLE
Implement `childNodes` and `children` as getters

### ISSUE THREAD

**Issue by edoardocavazza** [capricorn86/happy-dom#960]
**Is your feature request related to a problem? Please describe.**
I am working to a DOM library that is using the `childNodes` prototype descriptor, but in the happy-dom environment it is missing since it is implemented as class field.

**Describe the solution you'd like**
Espose `childNodes` and `children` as getters, transforming read/write class fields to `_childNodes` and `_children`.

**Describe alternatives you've considered**
I don't know.

**Additional context**
I am going to open a PR with an implementation proposal.

**Comment by capricorn86** [comment]
Your fix has been released @edoardocavazza :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.11.0
