### ISSUE TITLE
Does not work with urls encoded in base64 or svg

### ISSUE THREAD

**Issue by lsroman** [capricorn86/happy-dom#976]
**Describe the bug**
happy-dom does not work with urls encoded in base64 or svg((

**To Reproduce**
1. Create `test.js` file
2. Copy this code 
```js 
const { Window } = require('happy-dom');
const window = new Window();
const document = window.document;
const _tmp = document.createElement('div');
_tmp.style.setProperty('--test_1', "url(data:image/svg+xml;base64,TEST)");
_tmp.style.backgroundImage = "url(data:image/svg+xml;base64,TEST)"
console.log(_tmp.outerHTML);
```
4. Run `node test.js`
5. See console `<div style="--test_1: url(data;"></div>`

**Expected behavior**
`<div style="--test_1: url(data:image/svg+xml;base64,TEST); background-image: url(data:image/svg+xml;base64,TEST)"></div>`

**Additional context**
The problem [here](https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/css/declaration/css-parser/CSSStyleDeclarationCSSParser.ts#L15-L19) is because of the primitive cssText parsing.

**Comment by capricorn86** [comment]
Thank you @lsroman for reporting! :slightly_smiling_face: 

Big thanks to @malko for your contribution! :star2: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.5.0
