### ISSUE TITLE
Implement HTMIInputElement setter for valueAsDate 

### ISSUE THREAD

**Issue by malko** [capricorn86/happy-dom#977]
**Is your feature request related to a problem? Please describe.**
For now HTMLInputElement doesn't implement a setter for valueAsDate for input type that should support it

**Describe the solution you'd like**
Implement setter for valueAsDate

this is a follow up of work made about valueAsNumber #945 #946 #974

**Comment by malko** [comment]
@capricorn86 you can assign me this one if you want to

**Comment by malko** [comment]
PR #980 proposed

**Comment by capricorn86** [comment]
@malko your fix has been released :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.3.0
