### ISSUE TITLE
`labels` attribute misses labels without IDs

### ISSUE THREAD

**Issue by joshkel** [capricorn86/happy-dom#988]
**Describe the bug**

The `labels` attribute (for HTMLInputElement, HTMLSelectElement, etc.) is supposed to include enclosing labels, but it incorrectly only includes enclosing labels if the labelable element has an ID.

**To Reproduce**

```
<label>
This is a checkbox
<input type="checkbox" data-test-d="foo">
</label>
```

`document.querySelector("[data-test-id='foo']").labels` is empty.

**Expected behavior**

`document.querySelector("[data-test-id='foo']").labels` contains one label.

**Comment by capricorn86** [comment]
Your fix has been released @joshkel :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.6.1
