### ISSUE TITLE
Add support for document.createElementNS()

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#99]

**Comment by capricorn86** [comment]
@jgonte I have created this issue for adding support for document.createElementNS(). I will add support for it tomorrow.

**Comment by capricorn86** [comment]
@jgonte I did not manage to finish the update Today as I said.

It is related to other missing functionality regarding namespacing that is missing. I will add that functionality as well as part of this fix. It is only some unit tests left now, so I feel confident it will be in Tomorrow.

**Comment by capricorn86** [comment]
@jgonte Document.createElementNS() together with a bunch of other namespace related features is now supported in the latest release :slightly_smiling_face: 

[Read more about whats included in the release](https://github.com/capricorn86/happy-dom/releases/tag/v1.3.0)

**Comment by jgonte** [comment]
Great job!
I can imagine that is not a trivial thing to do!

It is working now

The only thing is that: (I haven't gone to the specs to verify this, it might be equivalent or yours even the correct way, but FYI)
Expected: "<svg><use xlink:href=\"http://icons/icons.svg#my-icon\"></use></svg>"
Received: "<svg><use xlink:href=\"http://icons/icons.svg#my-icon\"/></svg>"

**Comment by jgonte** [comment]
Also I think the issue with replaceWith() came back :-(

**Comment by capricorn86** [comment]
@jgonte thats weird, I have unit tests that tests that should check replaceWith(). I have created an issue to check if there is any problem with it: #122

**Comment by capricorn86** [comment]
@jgonte the recieved result is according to spec for the SVG:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

**Comment by capricorn86** [comment]
@jgonte I am currently working on updating Happy DOM in a big application. I found some issues in the latest updates with the apps integration. Not sure if it is related to any of your issues though, but just letting you know that I am working on resolving it :slightly_smiling_face:

**Comment by capricorn86** [comment]
I will close this issue. Lets have all discussions in #117 instead.
