### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'write')

### ISSUE THREAD

**Issue by saschanaz** [capricorn86/happy-dom#992]
**Describe the bug**

```
TypeError: Cannot read properties of undefined (reading 'write')
 ❯ Function.loadPage ../../node_modules/.pnpm/happy-dom@10.3.2/node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameUtility.ts:81:28
```

**To Reproduce**
(No repro steps right now, found in https://github.com/misskey-dev/misskey/issues/11287 https://github.com/misskey-dev/misskey/actions/runs/5561125165/jobs/10158584989 while updating from happy-dom@10.0.3 to 10.3.2)

**Expected behavior**
No error or at least some descriptive one

**Screenshots**

**Device:**
 - OS: [e.g. iOS] Ubuntu 22.04.2 (per the CI configuration)
 - Browser [e.g. chrome, safari] Node.js 20.4.0
 - Version [e.g. 22] happy-dom 10.3.2

**Additional context**
It was okay in 10.0.3.

**Comment by capricorn86** [comment]
I suspect that there is some patch applied on top of Happy DOM., because I don't know how it else would be possible that "document" would be undefined when executing `window.document.write()`. Also there are unit tests covering this.

**Comment by capricorn86** [comment]
I think the only way of knowing is to debug the code and set a breakpoint there.

**Comment by capricorn86** [comment]
Maybe changing from `new element.ownerDocument.defaultView.constructor()` to `new Window()` would solve it in case something has been overriding `defaultView` with another object.

https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/nodes/html-iframe-element/HTMLIFrameUtility.ts#L26

**Comment by capricorn86** [comment]
@saschanaz I have released a fix :slightly_smiling_face: 

Hopefully it will work. I have not tested it in your library.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v10.5.1

**Comment by capricorn86** [comment]
Please re-open if it doesn't work.
